export { dictionaryStats, dictionaryTranslate, lookupPhrase } from './dictionary.js'
export { lexiconTranslate, lexiconStats, glossLemmas } from './lexiconTranslate.js'
export { hardenYueOutput } from './postProcess.js'
export { scrubMandarinToYue, looksMandarinHeavy } from './scrub.js'
export { colloquialScore } from './colloquialScore.js'
export { normalizeLookupKey, uniqStrings } from './normalize.js'
export { glossStats, lookupGloss, segmentGlosses, eachLexiconEntry } from './gloss.js'
export { attestAgainstLexicon, ATTESTATION_REWRITE_THRESHOLD } from './attest.js'
export { activeGlossSources, wordshkEnabled, nonCommercialDictsAllowed } from './licenseGate.js'
export type { PhraseEntry, PostProcessMeta, TargetLang, TranslateStage } from './types.js'
export type { LexiconTranslateHit } from './lexiconTranslate.js'
