/**
 * Offline smoke for Practice Partner lab UI polish (no browser / paid APIs).
 */
import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = dirname(fileURLToPath(import.meta.url))
const tsx = readFileSync(join(root, 'AdminPracticePartnerLab.tsx'), 'utf8')
const css = readFileSync(join(root, 'AdminPracticePartnerLab.css'), 'utf8')
const vhs = readFileSync(join(root, 'vhs/createVHS.ts'), 'utf8')
const vhsView = readFileSync(join(root, 'vhs/PartnerVhsTransition.tsx'), 'utf8')

assert.match(tsx, /Begin drill! Follow along with the practice partner and advance!/)
assert.match(tsx, /Follow along! The practice partner will start off and repeat\./)
assert.match(tsx, /Choose difficulty & topic/)
assert.match(tsx, /Change topic/)
assert.match(tsx, /partner-lab--topic/)
assert.match(tsx, /partner-lab--companion/)
assert.match(tsx, /partner-outer-ring/)
assert.match(tsx, /partner-companion-mic/)
assert.match(tsx, /partner-lab-topic-list/)
assert.match(tsx, /partner-lab-diff-list/)
assert.match(tsx, /PRACTICE_PARTNER_DIFFICULTIES/)
assert.match(tsx, /onDifficultyPick/)
assert.match(tsx, /partner-lab-scores-crown|CROWN_ICON/)
assert.match(tsx, /old-falcon-43|popup-window/)
assert.match(tsx, /is-pulse/)
assert.doesNotMatch(tsx, /partner-lab-bottom/)
assert.doesNotMatch(tsx, /partner-lab-compose/)
assert.doesNotMatch(tsx, /Tap Begin drill\. No trophies\./)
assert.doesNotMatch(tsx, /speakerName[\s\S]*'Lab'/)
assert.match(
  tsx,
  /const speakerName\s*=\s*\n?\s*displayPrimary\.role === 'you' \? 'You' : partnerSpeaker/,
)

assert.match(tsx, /bilingualYueEn:\s*true/)
assert.match(tsx, /playPracticePartnerFailSfx/)
assert.match(tsx, /partner-lab-fail-burst/)
assert.match(tsx, /prepareLoudTtsPlayback/)
assert.match(tsx, /speakText\([^)]*loud:\s*true/, 'Partner replies always request loud TTS')
assert.match(
  readFileSync(new URL('../lib/tts.ts', import.meta.url), 'utf8'),
  /Same boost for every loud clip/,
  'loud TTS no longer softens post-mic turns',
)
assert.match(css, /partner-lab-fail-x/)
assert.match(css, /partner-lab-fail-edge-flash/)
assert.match(css, /is-fail-flash/)
assert.match(css, /partner-lab-talk-pulse/)
assert.match(css, /partner-lab-crown-spark/)
assert.match(css, /partner-lab-topic-list/)
assert.match(css, /partner-lab-diff-list/)
assert.match(css, /partner-lab-diff-item--mainlander/)
assert.match(tsx, /partner-lab-drill-zh/)
assert.match(tsx, /flashDrillZh/)
assert.match(tsx, /setZhFlash\(\(n\) => n \+ 1\)/)
assert.match(tsx, /zhFlashTimerRef[\s\S]{0,180}replayPhrase\(\)/)
assert.match(tsx, /speakText\(zh, 'yue', partnerVoice, \{ loud: true \}\)/)
assert.match(tsx, /const SILENCE_MS = 1600/)
assert.match(tsx, /mood === 'speaking' \|\| mood === 'reacting' \|\| isTtsPlaying\(\)/)
assert.match(tsx, /Heard \{missCard\.said\}/)
assert.match(tsx, /id: 'reacting'/)
assert.match(css, /partner-lab-stage--reacting/)
assert.match(tsx, /partner-lab-orbit-ring/)
assert.doesNotMatch(tsx, /setAmp/)
assert.match(css, /partner-lab-aura-pulse/)
assert.match(css, /backdrop-filter: none/)
assert.match(tsx, /partner-lab-presence/)
assert.match(css, /#050816/)
assert.doesNotMatch(tsx, /Fluency score|Pronunciation score/)
assert.match(tsx, /placement:\s*'stage'/)
assert.match(tsx, /practicePartnerCardShows/)
assert.match(tsx, /planPracticePartnerAdvance/)
assert.match(tsx, /Listen, then say it back/)
assert.match(tsx, /JyutpingChaoText[\s\S]{0,80}text=\{activeDrill\.jyutping\}/)
assert.match(tsx, /Open chat/)
assert.match(tsx, /PRACTICE_PARTNER_SITUATION_GROUPS/)
assert.match(tsx, /beginSituation/)
assert.match(tsx, /partner-companion-whisper/)
assert.match(tsx, /speakWithHarbor/)
assert.match(tsx, /data-cast/)
assert.match(tsx, /partner-lab-thread/)
assert.match(tsx, /beat: spokenBeat/)
assert.match(tsx, /partner-lab-place-rail/)
assert.match(tsx, /partner-lab-beats/)
assert.match(tsx, /data-wash/)
assert.match(tsx, /is-lit/)
assert.match(css, /partner-lab-place--food/)
assert.match(tsx, /Who you meet/)
assert.match(tsx, /What you want/)
assert.match(tsx, /choosePersonality/)
assert.match(tsx, /Use your lines/)
assert.match(tsx, />\s*A line\s*</)
assert.match(tsx, /missReasonFallback/)
assert.match(tsx, /hint: true/)
assert.match(tsx, /自由講/)
assert.match(tsx, /This sitting/)
assert.match(tsx, /Lines you kept/)
assert.match(tsx, /glossForChar/)
assert.match(tsx, /toneNoteForSyllable/)
assert.match(tsx, /Enter the|Enter/)
assert.match(tsx, /mode: kind/)
assert.match(tsx, /yue-practice-partner-lines-v1|readPartnerSitting/)
assert.match(tsx, /partnerCaptionLayout/)
assert.match(tsx, /difficulty !== 'mainlander'/)
assert.match(tsx, /learningCaption\.secondaryScript/)
assert.match(tsx, /learningCaption\.primaryScript/)
assert.match(css, /partner-lab-subtitles-secondary\.is-reading/)
assert.match(
  tsx,
  /if \(!activeDrill\) \{[\s\S]*unlockTtsPlayback\(\{ force: true \}\)[\s\S]*setFullscreen\(true\)[\s\S]*prefersReducedMotion\(\)[\s\S]*setVhsCue[\s\S]*void startDrill\(\)/,
)
assert.match(tsx, /PartnerVhsTransition/)
assert.match(vhsView, /Pointer-events stay off/)
assert.match(vhsView, /aria-hidden="true"/)
assert.match(vhsView, /className="partner-vhs-output"/)
assert.match(vhsView, /paintFrame:/)
assert.match(vhs, /useManual/)
assert.match(vhs, /contentMaxX = 1/)
assert.match(vhs, /texImage2D/)
assert.match(css, /\.partner-vhs \{[\s\S]*z-index:\s*120/)
assert.match(css, /\.partner-vhs \{[\s\S]*pointer-events:\s*none/)
assert.match(css, /prefers-reduced-motion: reduce\) \{[\s\S]*\.partner-vhs \{\s*display:\s*none/)
assert.match(tsx, /verdict === 'fail'[\s\S]{0,220}zh: target\.zh/)
assert.match(tsx, /PracticePartnerPodium/)
assert.match(tsx, /PracticePartnerPath/)
assert.match(tsx, /creditPracticePartnerPath/)
assert.match(tsx, /listClassName="partner-lab-topic-list"/)
assert.match(css, /partner-map-scroll/)
assert.match(css, /partner-map-scroll\.is-sealed[\s\S]*grayscale\(1\)/)
assert.match(css, /partner-map\.is-fullscreen/)
assert.match(css, /touch-action:\s*none/)
const map = readFileSync(join(root, 'PracticePartnerPathMap.tsx'), 'utf8')
const mapLayout = readFileSync(join(root, '../lib/practicePartnerMapLayout.ts'), 'utf8')
assert.match(map, /addEventListener\('wheel'/)
assert.match(map, /pointers\.current\.size === 2/)
assert.match(map, /Drag the Ink Road/)
assert.match(map, /Hover or tap a stop/)
assert.match(map, /partner-map-card/)
assert.match(map, /setPinnedId/)
assert.match(map, /onPointerEnter/)
assert.match(map, /Practice \{shownCard\.placeEn\}/)
assert.match(map, /hoverTimer/)
assert.match(map, /clearTimeout/)
assert.match(css, /\.partner-map-card \{[\s\S]*pointer-events:\s*auto/)
assert.match(css, /\.partner-map-card\.is-preview \.partner-map-card-actions \{[\s\S]*display:\s*none/)
const story = readFileSync(join(root, '../lib/practicePartnerMapStory.ts'), 'utf8')
assert.match(story, /The drill has not started/)
assert.doesNotMatch(story, /harbor-quest|harbor-continent/)
assert.match(map, /ResizeObserver/)
assert.doesNotMatch(map, /scale > 1\.02/)
assert.match(map, /partnerMapLayerSize/)
assert.match(map, /WuxiaJourneyArt/)
assert.match(map, /WuxiaFarPeaks/)
assert.match(css, /prefers-reduced-motion: reduce\) \{[\s\S]*\.wuxia-sway/)
assert.match(mapLayout, /Lantern Gate/)
assert.match(mapLayout, /Cloud Terrace/)
assert.doesNotMatch(map, /harbor-quest|harbor-continent/)
assert.doesNotMatch(mapLayout, /harbor-quest|harbor-continent/)
assert.match(css, /partner-wuxia/)
assert.match(css, /wuxia-chapter/)
assert.match(map, /WuxiaCloudFrame/)
const clouds = readFileSync(join(root, 'WuxiaClouds.tsx'), 'utf8')
assert.match(clouds, /pan\.x \* layer\.factor/)
assert.doesNotMatch(clouds, /harbor-quest|harbor-continent/)
assert.match(css, /partner-map-clouds/)
assert.match(css, /wuxia-cloud-drift-far/)
assert.match(css, /prefers-reduced-motion: reduce\) \{[\s\S]*\.partner-map-cloud-drift/)
assert.match(tsx, /putPracticePartnerLeaderboard/)
assert.match(tsx, /xpGain: gained/)
assert.match(css, /\.partner-medal\.is-gold/)
assert.match(css, /\.partner-medal\.is-silver/)
assert.match(css, /\.partner-medal\.is-bronze/)
assert.match(css, /partner-medal-name-sheen/)
assert.match(tsx, /partner-lab-replay/)
assert.match(tsx, /replayPartnerVoice/)
assert.match(tsx, /partner-lab-replay-eq/)
assert.match(tsx, /disabled=\{mood === 'speaking' \|\| mood === 'reacting' \|\| listening\}/)
assert.match(css, /partner-lab-jade-char/)
assert.match(css, /partner-lab-drill-zh-line/)
assert.match(css, /partner-lab-jade-line/)
assert.doesNotMatch(css, /partner-lab-drill-zh\.is-jade-flash::after/)
assert.match(tsx, /partner-lab-subtitles-speaker/)
assert.match(tsx, /fullscreen && partnerHold[\s\S]*partner-lab-replay[\s\S]*partner-lab-subtitles-speaker/)
assert.match(css, /partner-lab-replay-eq/)
assert.match(css, /\.partner-lab-replay\.is-speaking/)
assert.doesNotMatch(css, /\.partner-lab-compose\s*\{/)
assert.doesNotMatch(css, /\.partner-lab-bottom\s*\{/)

const adminApi = readFileSync(join(root, '../lib/adminApi.ts'), 'utf8')
assert.match(adminApi, /id:\s*'new_learner'/)
assert.match(adminApi, /id:\s*'abc'/)
assert.match(adminApi, /id:\s*'mainlander'/)
assert.match(adminApi, /labelEn:\s*'New Learner'/)
assert.match(adminApi, /labelEn:\s*'Mainlander'/)
assert.match(adminApi, /difficulty:\s*resolvePracticePartnerDifficulty/)

console.log('AdminPracticePartnerLab.ui.smoke: ok')
