/** Curated Azure Neural TTS voices — re-export shared catalog. */
export {
  DEFAULT_YUE_VOICE,
  DEFAULT_EN_VOICE,
  DEFAULT_CMN_VOICE,
  DEFAULT_TL_VOICE,
  YUE_VOICES,
  EN_VOICES,
  CMN_VOICES,
  TL_VOICES,
  isYueVoice,
  isEnVoice,
  isCmnVoice,
  resolveYueVoice,
  resolveEnVoice,
  resolveCmnVoice,
  resolveTlVoice,
  voiceMeta,
  resolveSpeakVoice,
  type YueVoiceId,
  type EnVoiceId,
  type CmnVoiceId,
  type TtsVoiceId,
  type TtsVoiceOption,
} from '@jyut/shared/ttsVoices'
