/** Curated Azure Neural TTS voices — re-export shared catalog. */
export {
  DEFAULT_YUE_VOICE,
  DEFAULT_EN_VOICE,
  DEFAULT_CMN_VOICE,
  DEFAULT_WUU_VOICE,
  DEFAULT_TL_VOICE,
  DEFAULT_ES_VOICE,
  DEFAULT_VI_VOICE,
  YUE_VOICES,
  EN_VOICES,
  CMN_VOICES,
  WUU_VOICES,
  TL_VOICES,
  ES_VOICES,
  VI_VOICES,
  isYueVoice,
  isEnVoice,
  isCmnVoice,
  isWuuVoice,
  isTlVoice,
  isEsVoice,
  isViVoice,
  resolveYueVoice,
  resolveEnVoice,
  resolveCmnVoice,
  resolveWuuVoice,
  resolveTlVoice,
  resolveEsVoice,
  resolveViVoice,
  voiceMeta,
  resolveSpeakVoice,
  type YueVoiceId,
  type EnVoiceId,
  type CmnVoiceId,
  type WuuVoiceId,
  type TlVoiceId,
  type EsVoiceId,
  type ViVoiceId,
  type TtsVoiceId,
  type TtsVoiceOption,
} from '@jyut/shared/ttsVoices'
