/**
 * HarborRPG mount catalogue — free CC0 animals wired as soft rideables.
 * Sources: Quaternius Ultimate Animated Animals · Gobkit · farm pack · OGA notes.
 */
export const HARBOR_RPG_MOUNT_BASE = '/assets/harbor-quest/mounts'

export const HARBOR_RPG_MOUNT_IDS = [
  // Quaternius Ultimate Animated Animals (CC0)
  'horse',
  'horse-white',
  'deer',
  'donkey',
  'stag',
  'fox',
  'husky',
  'shiba',
  'wolf',
  'alpaca',
  'bull',
  'cow',
  // Farm pack (Quaternius lineage / godotcraft, CC0)
  'farm-horse',
  'farm-dog',
  'farm-pig',
  'farm-sheep',
  'farm-wolf',
  'farm-cat',
  'farm-chicken',
  'farm-raccoon',
  // Gobkit Free Animal Pack (CC0) — whimsical rides
  'corgi',
  'goat',
  'boar',
  'rhino',
  'hippo',
  'platypus',
  'red-panda',
  'duck',
  'owl',
  'seal',
] as const

export type HarborRpgMountId = (typeof HARBOR_RPG_MOUNT_IDS)[number]

export type HarborRpgMountDef = {
  id: HarborRpgMountId
  name: { en: string; zh: string }
  /** Public URL under Vite. */
  src: string
  pack: 'quaternius' | 'farm' | 'gobkit'
  /** Uniform scale after load. */
  scale: number
  /** Walk speed multiplier vs HARBOR_WALK_SPEED. */
  speedMult: number
  /** Rider sit height above mount root (world units). */
  saddleY: number
  /** Prefer these clip name substrings (case-insensitive). */
  clips: { idle: string[]; walk: string[]; gallop: string[] }
  /** Gold cost at Town stable (0 = starter unlock). */
  cost: number
  /** Soft unlock hint. */
  blurb: { en: string; zh: string }
}

const Q = `${HARBOR_RPG_MOUNT_BASE}/quaternius`
const F = `${HARBOR_RPG_MOUNT_BASE}/farm`
const G = `${HARBOR_RPG_MOUNT_BASE}/gobkit`

const Q_CLIPS = {
  idle: ['Idle', 'Idle_2'],
  walk: ['Walk'],
  gallop: ['Gallop', 'Run'],
}

const FARM_CLIPS = {
  idle: ['Idle', 'Idle_Eating'],
  walk: ['Walk'],
  gallop: ['Run', 'Jump_Loop'],
}

const GOB_CLIPS = {
  idle: ['idle'],
  walk: ['walk'],
  gallop: ['walk', 'attack'],
}

export const HARBOR_RPG_MOUNT_DEFS: Record<HarborRpgMountId, HarborRpgMountDef> = {
  horse: {
    id: 'horse',
    name: { en: 'Tide Horse', zh: '潮馬' },
    src: `${Q}/horse.glb`,
    pack: 'quaternius',
    scale: 0.42,
    speedMult: 1.85,
    saddleY: 1.35,
    clips: Q_CLIPS,
    cost: 0,
    blurb: { en: 'Starter ferry steed — Quaternius CC0.', zh: '入門渡馬——Quaternius CC0。' },
  },
  'horse-white': {
    id: 'horse-white',
    name: { en: 'Pearl Horse', zh: '珠馬' },
    src: `${Q}/horse_white.glb`,
    pack: 'quaternius',
    scale: 0.42,
    speedMult: 1.9,
    saddleY: 1.35,
    clips: Q_CLIPS,
    cost: 120,
    blurb: { en: 'Pale steed from the mirrored pier.', zh: '鏡碼頭的淡色坐騎。' },
  },
  deer: {
    id: 'deer',
    name: { en: 'Reed Deer', zh: '蘆鹿' },
    src: `${Q}/deer.glb`,
    pack: 'quaternius',
    scale: 0.4,
    speedMult: 1.75,
    saddleY: 1.2,
    clips: Q_CLIPS,
    cost: 90,
    blurb: { en: 'Marsh-path runner.', zh: '澤徑奔者。' },
  },
  donkey: {
    id: 'donkey',
    name: { en: 'Pier Donkey', zh: '碼頭驢' },
    src: `${Q}/donkey.glb`,
    pack: 'quaternius',
    scale: 0.4,
    speedMult: 1.55,
    saddleY: 1.15,
    clips: Q_CLIPS,
    cost: 60,
    blurb: { en: 'Steady pack mount for Town runs.', zh: '穩妥馱騎，適合小鎮往返。' },
  },
  stag: {
    id: 'stag',
    name: { en: 'Ash Stag', zh: '灰牡鹿' },
    src: `${Q}/stag.glb`,
    pack: 'quaternius',
    scale: 0.4,
    speedMult: 1.8,
    saddleY: 1.25,
    clips: Q_CLIPS,
    cost: 140,
    blurb: { en: 'Antlers like ruin ash.', zh: '角似遺址灰燼。' },
  },
  fox: {
    id: 'fox',
    name: { en: 'Lantern Fox', zh: '燈狐' },
    src: `${Q}/fox.glb`,
    pack: 'quaternius',
    scale: 0.55,
    speedMult: 1.7,
    saddleY: 0.85,
    clips: Q_CLIPS,
    cost: 100,
    blurb: { en: 'Quick and sly on pine trails.', zh: '松徑上迅捷狡黠。' },
  },
  husky: {
    id: 'husky',
    name: { en: 'Frost Husky', zh: '霜哈士奇' },
    src: `${Q}/husky.glb`,
    pack: 'quaternius',
    scale: 0.5,
    speedMult: 1.65,
    saddleY: 0.9,
    clips: Q_CLIPS,
    cost: 95,
    blurb: { en: 'Loyal dock companion.', zh: '忠誠碼頭夥伴。' },
  },
  shiba: {
    id: 'shiba',
    name: { en: 'Jade Shiba', zh: '玉柴犬' },
    src: `${Q}/shibainu.glb`,
    pack: 'quaternius',
    scale: 0.55,
    speedMult: 1.6,
    saddleY: 0.8,
    clips: Q_CLIPS,
    cost: 85,
    blurb: { en: 'Small but proud.', zh: '嬌小而傲。' },
  },
  wolf: {
    id: 'wolf',
    name: { en: 'Pine Wolf', zh: '松狼' },
    src: `${Q}/wolf.glb`,
    pack: 'quaternius',
    scale: 0.48,
    speedMult: 1.8,
    saddleY: 0.95,
    clips: Q_CLIPS,
    cost: 130,
    blurb: { en: 'Reach hunter’s mount.', zh: '松林境獵者坐騎。' },
  },
  alpaca: {
    id: 'alpaca',
    name: { en: 'Cloud Alpaca', zh: '雲駝羊' },
    src: `${Q}/alpaca.glb`,
    pack: 'quaternius',
    scale: 0.45,
    speedMult: 1.5,
    saddleY: 1.1,
    clips: Q_CLIPS,
    cost: 70,
    blurb: { en: 'Soft fleece, soft ride.', zh: '軟毛軟騎。' },
  },
  bull: {
    id: 'bull',
    name: { en: 'Iron Bull', zh: '鐵牛' },
    src: `${Q}/bull.glb`,
    pack: 'quaternius',
    scale: 0.38,
    speedMult: 1.45,
    saddleY: 1.4,
    clips: Q_CLIPS,
    cost: 110,
    blurb: { en: 'Heavy charge through ruins.', zh: '重衝遺址。' },
  },
  cow: {
    id: 'cow',
    name: { en: 'Meadow Cow', zh: '草原牛' },
    src: `${Q}/cow.glb`,
    pack: 'quaternius',
    scale: 0.38,
    speedMult: 1.4,
    saddleY: 1.35,
    clips: Q_CLIPS,
    cost: 55,
    blurb: { en: 'Pastoral and patient.', zh: '田牧而穩。' },
  },
  'farm-horse': {
    id: 'farm-horse',
    name: { en: 'Farm Horse', zh: '農莊馬' },
    src: `${F}/Horse.glb`,
    pack: 'farm',
    scale: 0.55,
    speedMult: 1.7,
    saddleY: 1.15,
    clips: FARM_CLIPS,
    cost: 75,
    blurb: { en: 'Compact farm pack steed.', zh: '精巧農莊坐騎。' },
  },
  'farm-dog': {
    id: 'farm-dog',
    name: { en: 'Farm Dog', zh: '農莊犬' },
    src: `${F}/Dog.glb`,
    pack: 'farm',
    scale: 0.65,
    speedMult: 1.55,
    saddleY: 0.75,
    clips: FARM_CLIPS,
    cost: 40,
    blurb: { en: 'Pier mutt with heart.', zh: '碼頭雜犬有心。' },
  },
  'farm-pig': {
    id: 'farm-pig',
    name: { en: 'Lucky Pig', zh: '福豬' },
    src: `${F}/Pig.glb`,
    pack: 'farm',
    scale: 0.6,
    speedMult: 1.35,
    saddleY: 0.7,
    clips: FARM_CLIPS,
    cost: 35,
    blurb: { en: 'Oddly rideable.', zh: '意外可騎。' },
  },
  'farm-sheep': {
    id: 'farm-sheep',
    name: { en: 'Cloud Sheep', zh: '雲羊' },
    src: `${F}/Sheep.glb`,
    pack: 'farm',
    scale: 0.6,
    speedMult: 1.3,
    saddleY: 0.7,
    clips: FARM_CLIPS,
    cost: 30,
    blurb: { en: 'Fluffy meadow bounce.', zh: '蓬鬆草原彈跳。' },
  },
  'farm-wolf': {
    id: 'farm-wolf',
    name: { en: 'Farm Wolf', zh: '農狼' },
    src: `${F}/Wolf.glb`,
    pack: 'farm',
    scale: 0.55,
    speedMult: 1.65,
    saddleY: 0.85,
    clips: FARM_CLIPS,
    cost: 80,
    blurb: { en: 'Smaller pack cousin.', zh: '較小的狼族表親。' },
  },
  'farm-cat': {
    id: 'farm-cat',
    name: { en: 'Pier Cat', zh: '碼頭貓' },
    src: `${F}/Cat.glb`,
    pack: 'farm',
    scale: 0.7,
    speedMult: 1.5,
    saddleY: 0.55,
    clips: FARM_CLIPS,
    cost: 45,
    blurb: { en: 'Judges your posture.', zh: '審視你的坐姿。' },
  },
  'farm-chicken': {
    id: 'farm-chicken',
    name: { en: 'Giant Chicken', zh: '巨雞' },
    src: `${F}/Chicken.glb`,
    pack: 'farm',
    scale: 0.9,
    speedMult: 1.25,
    saddleY: 0.65,
    clips: FARM_CLIPS,
    cost: 25,
    blurb: { en: 'Comedy mount. Still counts.', zh: '搞笑坐騎——仍算數。' },
  },
  'farm-raccoon': {
    id: 'farm-raccoon',
    name: { en: 'Bandit Raccoon', zh: '盜匪浣熊' },
    src: `${F}/Raccoon.glb`,
    pack: 'farm',
    scale: 0.7,
    speedMult: 1.45,
    saddleY: 0.6,
    clips: FARM_CLIPS,
    cost: 50,
    blurb: { en: 'Steals snacks mid-ride.', zh: '騎乘中偷零食。' },
  },
  corgi: {
    id: 'corgi',
    name: { en: 'Harbor Corgi', zh: '港灣柯基' },
    src: `${G}/Corgi.glb`,
    pack: 'gobkit',
    scale: 0.85,
    speedMult: 1.4,
    saddleY: 0.55,
    clips: GOB_CLIPS,
    cost: 40,
    blurb: { en: 'Gobkit CC0 loaf on legs.', zh: 'Gobkit CC0 短腿麵包。' },
  },
  goat: {
    id: 'goat',
    name: { en: 'Cliff Goat', zh: '崖羊' },
    src: `${G}/Goat.glb`,
    pack: 'gobkit',
    scale: 0.75,
    speedMult: 1.5,
    saddleY: 0.7,
    clips: GOB_CLIPS,
    cost: 55,
    blurb: { en: 'Ruins climber.', zh: '遺址攀者。' },
  },
  boar: {
    id: 'boar',
    name: { en: 'Tusk Boar', zh: '獠野豬' },
    src: `${G}/Boar.glb`,
    pack: 'gobkit',
    scale: 0.7,
    speedMult: 1.55,
    saddleY: 0.75,
    clips: GOB_CLIPS,
    cost: 65,
    blurb: { en: 'Charges first, asks later.', zh: '先衝再問。' },
  },
  rhino: {
    id: 'rhino',
    name: { en: 'Jade Rhino', zh: '玉犀' },
    src: `${G}/Rhino.glb`,
    pack: 'gobkit',
    scale: 0.55,
    speedMult: 1.35,
    saddleY: 1.1,
    clips: GOB_CLIPS,
    cost: 150,
    blurb: { en: 'Armored parade mount.', zh: '甲胄遊行坐騎。' },
  },
  hippo: {
    id: 'hippo',
    name: { en: 'River Hippo', zh: '河馬' },
    src: `${G}/Hippo.glb`,
    pack: 'gobkit',
    scale: 0.5,
    speedMult: 1.2,
    saddleY: 1.0,
    clips: GOB_CLIPS,
    cost: 100,
    blurb: { en: 'Slow. Unstoppable. Damp.', zh: '慢。不可擋。潮濕。' },
  },
  platypus: {
    id: 'platypus',
    name: { en: 'Mist Platypus', zh: '霧鴨嘴獸' },
    src: `${G}/Platypus.glb`,
    pack: 'gobkit',
    scale: 0.8,
    speedMult: 1.3,
    saddleY: 0.5,
    clips: GOB_CLIPS,
    cost: 70,
    blurb: { en: 'Marsh oddity.', zh: '澤地奇物。' },
  },
  'red-panda': {
    id: 'red-panda',
    name: { en: 'Red Panda', zh: '小熊貓' },
    src: `${G}/Red.glb`,
    pack: 'gobkit',
    scale: 0.8,
    speedMult: 1.35,
    saddleY: 0.55,
    clips: GOB_CLIPS,
    cost: 80,
    blurb: { en: 'Cute chaos.', zh: '可愛混亂。' },
  },
  duck: {
    id: 'duck',
    name: { en: 'Ferry Duck', zh: '渡鴨' },
    src: `${G}/Duck.glb`,
    pack: 'gobkit',
    scale: 0.95,
    speedMult: 1.15,
    saddleY: 0.45,
    clips: GOB_CLIPS,
    cost: 20,
    blurb: { en: 'Honk-powered.', zh: '呱力驅動。' },
  },
  owl: {
    id: 'owl',
    name: { en: 'Night Owl', zh: '夜梟' },
    src: `${G}/Owl.glb`,
    pack: 'gobkit',
    scale: 0.85,
    speedMult: 1.45,
    saddleY: 0.6,
    clips: GOB_CLIPS,
    cost: 90,
    blurb: { en: 'Silent pier wings.', zh: '靜默碼頭羽翼。' },
  },
  seal: {
    id: 'seal',
    name: { en: 'Harbor Seal', zh: '港灣海豹' },
    src: `${G}/Seal.glb`,
    pack: 'gobkit',
    scale: 0.7,
    speedMult: 1.25,
    saddleY: 0.55,
    clips: GOB_CLIPS,
    cost: 60,
    blurb: { en: 'Best on wet stone.', zh: '濕石上最佳。' },
  },
}

export function isHarborRpgMountId(raw: unknown): raw is HarborRpgMountId {
  return typeof raw === 'string' && (HARBOR_RPG_MOUNT_IDS as readonly string[]).includes(raw)
}

export function harborRpgMountById(id: string): HarborRpgMountDef | null {
  return isHarborRpgMountId(id) ? HARBOR_RPG_MOUNT_DEFS[id] : null
}

/** Town stable interactable. */
export const HARBOR_RPG_STABLE = {
  id: 'rpg-stable' as const,
  zone: 'town' as const,
  x: -4,
  z: 10,
  radius: 2.4,
  name: { en: 'Ferry Stable', zh: '渡船馬廄' },
}
