/** Extra Match-the-Definition entries — expands arena variety. */
import type { MatchDifficulty, MatchTopic } from './matchDefinitionBank'

type ExtraWord = {
  id: string
  han: string
  jp: string
  def: string
  topic: MatchTopic
  difficulty: MatchDifficulty
}

export const MATCH_DEFINITION_BANK_EXTRA: ExtraWord[] = [
  { id: 'k-e-x0-ye4', han: '爺', jp: 'ye4', def: 'grandpa', topic: 'kids', difficulty: 'easy' },
  { id: 'k-e-x1-po4', han: '婆', jp: 'po4', def: 'grandma', topic: 'kids', difficulty: 'easy' },
  { id: 'k-e-x2-suk1', han: '叔', jp: 'suk1', def: 'uncle', topic: 'kids', difficulty: 'easy' },
  { id: 'k-e-x3-gu1', han: '姑', jp: 'gu1', def: 'aunt', topic: 'kids', difficulty: 'easy' },
  { id: 'k-e-x4-gung1', han: '公', jp: 'gung1', def: 'grandpa (maternal)', topic: 'kids', difficulty: 'easy' },
  { id: 'k-e-x5-hoi1sam1', han: '開心', jp: 'hoi1 sam1', def: 'happy', topic: 'kids', difficulty: 'easy' },
  { id: 'k-e-x6-sau3', han: '笑', jp: 'siu3', def: 'to smile / laugh', topic: 'kids', difficulty: 'easy' },
  { id: 'k-e-x7-ham3', han: '喊', jp: 'haam3', def: 'to cry', topic: 'kids', difficulty: 'easy' },
  { id: 'k-e-x8-paau2', han: '跑', jp: 'paau2', def: 'to run', topic: 'kids', difficulty: 'easy' },
  { id: 'k-e-x9-tiu3', han: '跳', jp: 'tiu3', def: 'to jump', topic: 'kids', difficulty: 'easy' },
  { id: 'k-e-x10-zoek3', han: '著', jp: 'zoek3', def: 'to wear', topic: 'kids', difficulty: 'easy' },
  { id: 'k-e-x11-haai4', han: '鞋', jp: 'haai4', def: 'shoe', topic: 'kids', difficulty: 'easy' },
  { id: 'k-e-x12-mou2', han: '帽', jp: 'mou2', def: 'hat', topic: 'kids', difficulty: 'easy' },
  { id: 'k-e-x13-jin1', han: '衣', jp: 'ji1', def: 'clothes', topic: 'kids', difficulty: 'easy' },
  { id: 'k-e-x14-toi2', han: '枱', jp: 'toi2', def: 'table', topic: 'kids', difficulty: 'easy' },
  { id: 'k-e-x15-dang3', han: '凳', jp: 'dang3', def: 'stool / chair', topic: 'kids', difficulty: 'easy' },
  { id: 'k-e-x16-mun4', han: '門', jp: 'mun4', def: 'door', topic: 'kids', difficulty: 'easy' },
  { id: 'k-e-x17-coeng1', han: '窗', jp: 'coeng1', def: 'window', topic: 'kids', difficulty: 'easy' },
  { id: 'k-e-x18-tong4', han: '堂', jp: 'tong4', def: 'classroom / hall', topic: 'kids', difficulty: 'easy' },
  { id: 'k-e-x19-lou5si1', han: '老師', jp: 'lou5 si1', def: 'teacher', topic: 'kids', difficulty: 'easy' },
  { id: 'k-e-x20-hok6saang1', han: '學生', jp: 'hok6 saang1', def: 'student', topic: 'kids', difficulty: 'easy' },
  { id: 'k-e-x21-pang4', han: '朋', jp: 'pang4', def: 'friend (short)', topic: 'kids', difficulty: 'easy' },
  { id: 'k-e-x22-waan2', han: '玩', jp: 'waan2', def: 'to play', topic: 'kids', difficulty: 'easy' },
  { id: 'k-e-x23-zung1', han: '鐘', jp: 'zung1', def: 'clock / bell', topic: 'kids', difficulty: 'easy' },
  { id: 'k-e-x24-zi2', han: '紙', jp: 'zi2', def: 'paper', topic: 'kids', difficulty: 'easy' },
  { id: 'k-e-x25-baau1', han: '包', jp: 'baau1', def: 'bag / bun', topic: 'kids', difficulty: 'easy' },
  { id: 'k-e-x26-seoi2', han: '水', jp: 'seoi2', def: 'water', topic: 'kids', difficulty: 'easy' },
  { id: 'k-e-x27-naai5', han: '奶', jp: 'naai5', def: 'milk', topic: 'kids', difficulty: 'easy' },
  { id: 'k-e-x28-tong4gwo2', han: '糖果', jp: 'tong4 gwo2', def: 'candy', topic: 'kids', difficulty: 'easy' },
  { id: 'k-e-x29-ping4', han: '平', jp: 'ping4', def: 'cheap / flat', topic: 'kids', difficulty: 'easy' },
  { id: 'k-m-x0-ngo5dei6', han: '我哋', jp: 'ngo5 dei6', def: 'we / us', topic: 'kids', difficulty: 'medium' },
  { id: 'k-m-x1-nei5dei6', han: '你哋', jp: 'nei5 dei6', def: 'you (plural)', topic: 'kids', difficulty: 'medium' },
  { id: 'k-m-x2-keoi5dei6', han: '佢哋', jp: 'keoi5 dei6', def: 'they / them', topic: 'kids', difficulty: 'medium' },
  { id: 'k-m-x3-jat1cai4', han: '一齊', jp: 'jat1 cai4', def: 'together', topic: 'kids', difficulty: 'medium' },
  { id: 'k-m-x4-fong3hok6', han: '放學', jp: 'fong3 hok6', def: 'school is over', topic: 'kids', difficulty: 'medium' },
  { id: 'k-m-x5-soeng5tong4', han: '上課', jp: 'soeng5 fo3', def: 'to attend class', topic: 'kids', difficulty: 'medium' },
  { id: 'k-m-x6-zou6gung1fo3', han: '做功課', jp: 'zou6 gung1 fo3', def: 'to do homework', topic: 'kids', difficulty: 'medium' },
  { id: 'k-m-x7-tai2syu1', han: '睇書', jp: 'tai2 syu1', def: 'to read a book', topic: 'kids', difficulty: 'medium' },
  { id: 'k-m-x8-waak6waa2', han: '畫畫', jp: 'waak6 waa2', def: 'to draw', topic: 'kids', difficulty: 'medium' },
  { id: 'k-m-x9-coeng3go1', han: '唱歌', jp: 'coeng3 go1', def: 'to sing', topic: 'kids', difficulty: 'medium' },
  { id: 'k-m-x10-tiu3mou5', han: '跳舞', jp: 'tiu3 mou5', def: 'to dance', topic: 'kids', difficulty: 'medium' },
  { id: 'k-m-x11-daa2kau4', han: '打球', jp: 'daa2 kau4', def: 'to play ball', topic: 'kids', difficulty: 'medium' },
  { id: 'k-m-x12-sik6tong4', han: '食糖', jp: 'sik6 tong4', def: 'to eat candy', topic: 'kids', difficulty: 'medium' },
  { id: 'k-m-x13-jam2seoi2', han: '飲水', jp: 'jam2 seoi2', def: 'to drink water', topic: 'kids', difficulty: 'medium' },
  { id: 'k-m-x14-sai2sau2', han: '洗手', jp: 'sai2 sau2', def: 'to wash hands', topic: 'kids', difficulty: 'medium' },
  { id: 'k-m-x15-sai2min6', han: '洗面', jp: 'sai2 min6', def: 'to wash face', topic: 'kids', difficulty: 'medium' },
  { id: 'k-m-x16-fan3gaau3', han: '瞓覺', jp: 'fan3 gaau3', def: 'to sleep', topic: 'kids', difficulty: 'medium' },
  { id: 'k-m-x17-hei2san1', han: '起身', jp: 'hei2 san1', def: 'to get up', topic: 'kids', difficulty: 'medium' },
  { id: 'k-m-x18-ceot1mun4', han: '出門', jp: 'ceot1 mun4', def: 'to go out', topic: 'kids', difficulty: 'medium' },
  { id: 'k-m-x19-faa1saang1', han: '花生', jp: 'faa1 saang1', def: 'peanut', topic: 'kids', difficulty: 'medium' },
  { id: 'k-m-x20-hou2pang4jau5', han: '好朋友', jp: 'hou2 pang4 jau5', def: 'good friend', topic: 'kids', difficulty: 'medium' },
  { id: 'k-m-x21-siu2pang4jau5', han: '小朋友', jp: 'siu2 pang4 jau5', def: 'child / kid', topic: 'kids', difficulty: 'medium' },
  { id: 'k-m-x22-daai6jan4', han: '大人', jp: 'daai6 jan4', def: 'adult', topic: 'kids', difficulty: 'medium' },
  { id: 'k-m-x23-lou5si1fu2', han: '老師傅', jp: 'lou5 si1 fu2', def: 'master teacher', topic: 'kids', difficulty: 'medium' },
  { id: 'k-m-x24-bat1hap6', han: '筆盒', jp: 'bat1 hap6', def: 'pencil case', topic: 'kids', difficulty: 'medium' },
  { id: 'k-m-x25-syu1baau1', han: '書包', jp: 'syu1 baau1', def: 'schoolbag', topic: 'kids', difficulty: 'medium' },
  { id: 'k-m-x26-baak6baan2', han: '白板', jp: 'baak6 baan2', def: 'whiteboard', topic: 'kids', difficulty: 'medium' },
  { id: 'k-m-x27-hak1baan2', han: '黑板', jp: 'hak1 baan2', def: 'blackboard', topic: 'kids', difficulty: 'medium' },
  { id: 'k-m-x28-fung1kau4', han: '風箏', jp: 'fung1 zang1', def: 'kite', topic: 'kids', difficulty: 'medium' },
  { id: 'k-m-x29-daan1ce1', han: '單車', jp: 'daan1 ce1', def: 'bicycle', topic: 'kids', difficulty: 'medium' },
  {
    id: 'k-h-x0',
    han: '今日我好開心。',
    jp: 'gam1 jat6 ngo5 hou2 hoi1 sam1',
    def: 'I’m really happy today.',
    topic: 'kids',
    difficulty: 'hard',
  },
  {
    id: 'k-h-x1',
    han: '老師教我哋讀唐詩。',
    jp: 'lou5 si1 gaau3 ngo5 dei6 duk6 tong4 si1',
    def: 'The teacher teaches us Tang poems.',
    topic: 'kids',
    difficulty: 'hard',
  },
  {
    id: 'k-h-x2',
    han: '放學之後我去做功課。',
    jp: 'fong3 hok6 zi1 hau6 ngo5 heoi3 zou6 gung1 fo3',
    def: 'After school I’m going to do homework.',
    topic: 'kids',
    difficulty: 'hard',
  },
  {
    id: 'k-h-x3',
    han: '妹妹鍾意畫彩色圖畫。',
    jp: 'mui6 mui2 zung1 ji3 waak6 coi2 sik1 tou4 waa2',
    def: 'Little sister likes drawing colorful pictures.',
    topic: 'kids',
    difficulty: 'hard',
  },
  {
    id: 'k-h-x4',
    han: '哥哥同我一齊踢足球。',
    jp: 'go1 go1 tung4 ngo5 jat1 cai4 tek3 zuk1 kau4',
    def: 'Big brother and I play soccer together.',
    topic: 'kids',
    difficulty: 'hard',
  },
  {
    id: 'k-h-x5',
    han: '請你坐低聽我講故事。',
    jp: 'cing2 nei5 co5 dai1 teng1 ngo5 gong2 gu3 si6',
    def: 'Please sit down and listen to my story.',
    topic: 'kids',
    difficulty: 'hard',
  },
  {
    id: 'k-h-x6',
    han: '媽咪整咗好味嘅蛋糕。',
    jp: 'maa1 mi4 zing2 zo2 hou2 mei6 ge3 daan6 gou1',
    def: 'Mommy made a delicious cake.',
    topic: 'kids',
    difficulty: 'hard',
  },
  {
    id: 'k-h-x7',
    han: '阿爺帶我去公園玩。',
    jp: 'aa3 ye4 daai3 ngo5 heoi3 gung1 jyun2 waan2',
    def: 'Grandpa took me to play in the park.',
    topic: 'kids',
    difficulty: 'hard',
  },
  {
    id: 'k-h-x8',
    han: '書包裏面有三本書。',
    jp: 'syu1 baau1 leoi5 min6 jau5 saam1 bun2 syu1',
    def: 'There are three books in the schoolbag.',
    topic: 'kids',
    difficulty: 'hard',
  },
  {
    id: 'k-h-x9',
    han: '唔好喺課堂度講笑呀。',
    jp: 'm4 hou2 hai2 fo3 tong4 dou6 gong2 siu3 aa3',
    def: 'Don’t joke around in class.',
    topic: 'kids',
    difficulty: 'hard',
  },
  {
    id: 'k-h-x10',
    han: '我鍾意同朋友一齊畫畫。',
    jp: 'ngo5 zung1 ji3 tung4 pang4 jau5 jat1 cai4 waak6 waa2',
    def: 'I like drawing with friends.',
    topic: 'kids',
    difficulty: 'hard',
  },
  {
    id: 'k-h-x11',
    han: '細佬仔要早啲瞓覺。',
    jp: 'sai3 lou2 zai2 jiu3 zou2 di1 fan3 gaau3',
    def: 'Little kids should go to sleep earlier.',
    topic: 'kids',
    difficulty: 'hard',
  },
  {
    id: 'k-h-x12',
    han: '今日上堂學咗新字。',
    jp: 'gam1 jat6 soeng5 tong4 hok6 zo2 san1 zi6',
    def: 'We learned new characters in class today.',
    topic: 'kids',
    difficulty: 'hard',
  },
  {
    id: 'k-h-x13',
    han: '可唔可以借支筆畀我？',
    jp: 'ho2 m4 ho2 ji5 ze3 zi1 bat1 bei2 ngo5',
    def: 'Can you lend me a pen?',
    topic: 'kids',
    difficulty: 'hard',
  },
  {
    id: 'k-h-x14',
    han: '我哋一齊唱生日歌啦。',
    jp: 'ngo5 dei6 jat1 cai4 coeng3 saang1 jat6 go1 laa1',
    def: 'Let’s sing the birthday song together.',
    topic: 'kids',
    difficulty: 'hard',
  },
  {
    id: 'k-h-x15',
    han: '爸比教我踏單車。',
    jp: 'baa1 bi1 gaau3 ngo5 daap6 daan1 ce1',
    def: 'Daddy is teaching me to ride a bike.',
    topic: 'kids',
    difficulty: 'hard',
  },
  {
    id: 'k-h-x16',
    han: '雨衣同雨鞋擺喺門口。',
    jp: 'jyu5 ji1 tung4 jyu5 haai4 baai2 hai2 mun4 hau2',
    def: 'The raincoat and rain boots are by the door.',
    topic: 'kids',
    difficulty: 'hard',
  },
  {
    id: 'k-h-x17',
    han: '老師讚我讀得好好。',
    jp: 'lou5 si1 zaan3 ngo5 duk6 dak1 hou2 hou2',
    def: 'The teacher praised me for reading well.',
    topic: 'kids',
    difficulty: 'hard',
  },
  {
    id: 'k-h-x18',
    han: '下課之後記得洗手。',
    jp: 'haa6 fo3 zi1 hau6 gei3 dak1 sai2 sau2',
    def: 'Remember to wash your hands after class.',
    topic: 'kids',
    difficulty: 'hard',
  },
  {
    id: 'k-h-x19',
    han: '呢本故事書好好睇。',
    jp: 'ni1 bun2 gu3 si6 syu1 hou2 hou2 tai2',
    def: 'This storybook is really good.',
    topic: 'kids',
    difficulty: 'hard',
  },
  { id: 'a-e-x0-si1', han: '獅', jp: 'si1', def: 'lion', topic: 'animals', difficulty: 'easy' },
  { id: 'a-e-x1-fu2', han: '虎', jp: 'fu2', def: 'tiger', topic: 'animals', difficulty: 'easy' },
  { id: 'a-e-x2-hung4', han: '熊', jp: 'hung4', def: 'bear', topic: 'animals', difficulty: 'easy' },
  { id: 'a-e-x3-lou5syu2', han: '老鼠', jp: 'lou5 syu2', def: 'mouse / rat', topic: 'animals', difficulty: 'easy' },
  { id: 'a-e-x4-jap6', han: '鴨', jp: 'aap3', def: 'duck', topic: 'animals', difficulty: 'easy' },
  { id: 'a-e-x5-gai1', han: '雞', jp: 'gai1', def: 'chicken', topic: 'animals', difficulty: 'easy' },
  { id: 'a-e-x6-ngo4', han: '鵝', jp: 'ngo4', def: 'goose', topic: 'animals', difficulty: 'easy' },
  { id: 'a-e-x7-joeng4', han: '羊', jp: 'joeng4', def: 'sheep / goat', topic: 'animals', difficulty: 'easy' },
  { id: 'a-e-x8-se4', han: '蛇', jp: 'se4', def: 'snake', topic: 'animals', difficulty: 'easy' },
  { id: 'a-e-x9-wai1', han: '蛙', jp: 'waa1', def: 'frog', topic: 'animals', difficulty: 'easy' },
  { id: 'a-e-x10-haai5', han: '蟹', jp: 'haai5', def: 'crab', topic: 'animals', difficulty: 'easy' },
  { id: 'a-e-x11-haa1', han: '蝦', jp: 'haa1', def: 'shrimp', topic: 'animals', difficulty: 'easy' },
  { id: 'a-e-x12-wu1jing1', han: '烏鴉', jp: 'wu1 aa1', def: 'crow', topic: 'animals', difficulty: 'easy' },
  { id: 'a-e-x13-baak6gop3', han: '白鴿', jp: 'baak6 gap3', def: 'pigeon / dove', topic: 'animals', difficulty: 'easy' },
  { id: 'a-e-x14-jing1mou5', han: '鸚鵡', jp: 'jing1 mou5', def: 'parrot', topic: 'animals', difficulty: 'easy' },
  { id: 'a-e-x15-dai6', han: '蝶', jp: 'dip6', def: 'butterfly', topic: 'animals', difficulty: 'easy' },
  { id: 'a-e-x16-ngai4', han: '蟻', jp: 'ngai5', def: 'ant', topic: 'animals', difficulty: 'easy' },
  { id: 'a-e-x17-wu4dip6', han: '蝴蝶', jp: 'wu4 dip6', def: 'butterfly', topic: 'animals', difficulty: 'easy' },
  { id: 'a-e-x18-lung4haa1', han: '龍蝦', jp: 'lung4 haa1', def: 'lobster', topic: 'animals', difficulty: 'easy' },
  { id: 'a-e-x19-hoi2cung4', han: '海蟲', jp: 'hoi2 cung4', def: 'sea worm', topic: 'animals', difficulty: 'easy' },
  { id: 'a-e-x20-zyu1zai2', han: '豬仔', jp: 'zyu1 zai2', def: 'piglet', topic: 'animals', difficulty: 'easy' },
  { id: 'a-e-x21-ngau4zai2', han: '牛仔', jp: 'ngau4 zai2', def: 'calf', topic: 'animals', difficulty: 'easy' },
  { id: 'a-e-x22-maa5zai2', han: '馬仔', jp: 'maa5 zai2', def: 'foal', topic: 'animals', difficulty: 'easy' },
  { id: 'a-e-y0-cung4', han: '蟲', jp: 'cung4', def: 'insect / bug', topic: 'animals', difficulty: 'easy' },
  { id: 'a-e-y1-wu1gwai1', han: '烏龜', jp: 'wu1 gwai1', def: 'turtle', topic: 'animals', difficulty: 'easy' },
  { id: 'a-e-y2-king4', han: '鯨', jp: 'king4', def: 'whale', topic: 'animals', difficulty: 'easy' },
  { id: 'a-e-y3-hoi2tun4', han: '海豚', jp: 'hoi2 tyun4', def: 'dolphin', topic: 'animals', difficulty: 'easy' },
  { id: 'a-e-y4-sai1ngau4', han: '犀牛', jp: 'sai1 ngau4', def: 'rhino', topic: 'animals', difficulty: 'easy' },
  { id: 'a-e-y5-lo4to4', han: '駱駝', jp: 'lok3 to4', def: 'camel', topic: 'animals', difficulty: 'easy' },
  { id: 'a-m-x0-daai6si1', han: '大獅', jp: 'daai6 si1', def: 'big lion', topic: 'animals', difficulty: 'medium' },
  { id: 'a-m-x1-siu2fu2', han: '小虎', jp: 'siu2 fu2', def: 'little tiger', topic: 'animals', difficulty: 'medium' },
  { id: 'a-m-x2-baak6hung4', han: '白熊', jp: 'baak6 hung4', def: 'polar bear', topic: 'animals', difficulty: 'medium' },
  { id: 'a-m-x3-wong4ngau4', han: '黃牛', jp: 'wong4 ngau4', def: 'yellow cattle', topic: 'animals', difficulty: 'medium' },
  { id: 'a-m-x4-hak1maa5', han: '黑馬', jp: 'hak1 maa5', def: 'black horse', topic: 'animals', difficulty: 'medium' },
  { id: 'a-m-x5-baak6joeng4', han: '白羊', jp: 'baak6 joeng4', def: 'white sheep', topic: 'animals', difficulty: 'medium' },
  { id: 'a-m-x6-cuk1se4', han: '毒蛇', jp: 'duk6 se4', def: 'venomous snake', topic: 'animals', difficulty: 'medium' },
  { id: 'a-m-x7-cing1waa1', han: '青蛙', jp: 'cing1 waa1', def: 'green frog', topic: 'animals', difficulty: 'medium' },
  { id: 'a-m-x8-hung4haai5', han: '紅蟹', jp: 'hung4 haai5', def: 'red crab', topic: 'animals', difficulty: 'medium' },
  { id: 'a-m-x9-daai6haa1', han: '大蝦', jp: 'daai6 haa1', def: 'prawn', topic: 'animals', difficulty: 'medium' },
  { id: 'a-m-x10-fei1lung4', han: '飛龍', jp: 'fei1 lung4', def: 'flying dragon', topic: 'animals', difficulty: 'medium' },
  { id: 'a-m-x11-seoi2niu5', han: '水鳥', jp: 'seoi2 niu5', def: 'waterbird', topic: 'animals', difficulty: 'medium' },
  { id: 'a-m-x12-san1jyu2', han: '鮮魚', jp: 'sin1 jyu2', def: 'fresh fish', topic: 'animals', difficulty: 'medium' },
  { id: 'a-m-x13-loeng4jyu2', han: '鯉魚', jp: 'lei5 jyu2', def: 'carp', topic: 'animals', difficulty: 'medium' },
  { id: 'a-m-x14-waan4hung4', han: '熊貓', jp: 'hung4 maau1', def: 'panda', topic: 'animals', difficulty: 'medium' },
  { id: 'a-m-x15-daai6zoeng6', han: '大象', jp: 'daai6 zoeng6', def: 'elephant', topic: 'animals', difficulty: 'medium' },
  { id: 'a-m-y0-hou2gau2', han: '好狗', jp: 'hou2 gau2', def: 'good dog', topic: 'animals', difficulty: 'medium' },
  { id: 'a-m-y1-waan2maau1', han: '玩貓', jp: 'waan2 maau1', def: 'to play with a cat', topic: 'animals', difficulty: 'medium' },
  { id: 'a-m-y2-wai6jyu2', han: '餵魚', jp: 'wai3 jyu2', def: 'to feed fish', topic: 'animals', difficulty: 'medium' },
  { id: 'a-m-y3-tai2niu5', han: '睇鳥', jp: 'tai2 niu5', def: 'to watch birds', topic: 'animals', difficulty: 'medium' },
  { id: 'a-m-y4-zung1ji3gau2', han: '鍾意狗', jp: 'zung1 ji3 gau2', def: 'to like dogs', topic: 'animals', difficulty: 'medium' },
  { id: 'a-m-y5-pa3se4', han: '怕蛇', jp: 'paa3 se4', def: 'to fear snakes', topic: 'animals', difficulty: 'medium' },
  { id: 'a-m-y6-juk1maau1', han: '抱貓', jp: 'pou5 maau1', def: 'to hold a cat', topic: 'animals', difficulty: 'medium' },
  { id: 'a-m-y7-teoi1gau2', han: '推狗', jp: 'teoi1 gau2', def: 'to push a dog', topic: 'animals', difficulty: 'medium' },
  { id: 'a-m-y8-daai6baak6hip3', han: '大白鯊', jp: 'daai6 baak6 saa1', def: 'great white shark', topic: 'animals', difficulty: 'medium' },
  { id: 'a-m-y9-siu2baak6tou3', han: '小白兔', jp: 'siu2 baak6 tou3', def: 'little white rabbit', topic: 'animals', difficulty: 'medium' },
  { id: 'a-m-y10-cim4seoi2jyu2', han: '潛水魚', jp: 'cim4 seoi2 jyu2', def: 'diving fish', topic: 'animals', difficulty: 'medium' },
  { id: 'a-m-y11-tin1hung1niu5', han: '天空鳥', jp: 'tin1 hung1 niu5', def: 'sky bird', topic: 'animals', difficulty: 'medium' },
  { id: 'a-m-y12-naam4gik6hung4', han: '南極熊', jp: 'naam4 gik6 hung4', def: 'Antarctic bear', topic: 'animals', difficulty: 'medium' },
  { id: 'a-m-y13-sai1fong1si1', han: '西方獅', jp: 'sai1 fong1 si1', def: 'western lion', topic: 'animals', difficulty: 'medium' },
  { id: 'a-m-y14-zung1gwok3lung4', han: '中國龍', jp: 'zung1 gwok3 lung4', def: 'Chinese dragon', topic: 'animals', difficulty: 'medium' },
  { id: 'a-m-y15-gung1jyun2gau2', han: '公園狗', jp: 'gung1 jyun2 gau2', def: 'park dog', topic: 'animals', difficulty: 'medium' },
  { id: 'a-m-y16-hoi2bin1haai5', han: '海邊蟹', jp: 'hoi2 bin1 haai5', def: 'seaside crab', topic: 'animals', difficulty: 'medium' },
  { id: 'a-m-y17-saan1deoi1fu2', han: '山地虎', jp: 'saan1 dei6 fu2', def: 'mountain tiger', topic: 'animals', difficulty: 'medium' },
  {
    id: 'a-h-x0',
    han: '動物園有獅子同老虎。',
    jp: 'dung6 mat6 jyun2 jau5 si1 zi2 tung4 lou5 fu2',
    def: 'The zoo has lions and tigers.',
    topic: 'animals',
    difficulty: 'hard',
  },
  {
    id: 'a-h-x1',
    han: '熊貓淨係喺中國先有。',
    jp: 'hung4 maau1 zing6 hai6 hai2 zung1 gwok3 sin1 jau5',
    def: 'Pandas are only found in China.',
    topic: 'animals',
    difficulty: 'hard',
  },
  {
    id: 'a-h-x2',
    han: '海豚好聰明，識跳躍。',
    jp: 'hoi2 tyun4 hou2 cung1 ming4, sik1 tiu3 joek3',
    def: 'Dolphins are smart and can leap.',
    topic: 'animals',
    difficulty: 'hard',
  },
  {
    id: 'a-h-x3',
    han: '小心啲，條蛇好毒。',
    jp: 'siu2 sam1 di1, tiu4 se4 hou2 duk6',
    def: 'Be careful — that snake is venomous.',
    topic: 'animals',
    difficulty: 'hard',
  },
  {
    id: 'a-h-x4',
    han: '農場裏面養咗好多雞鴨。',
    jp: 'nung4 coeng4 leoi5 min6 joeng5 zo2 hou2 do1 gai1 aap3',
    def: 'The farm raises lots of chickens and ducks.',
    topic: 'animals',
    difficulty: 'hard',
  },
  {
    id: 'a-h-x5',
    han: '小貓喺窗邊曬太陽。',
    jp: 'siu2 maau1 hai2 coeng1 bin1 saai3 taai3 joeng4',
    def: 'The kitten sunbathes by the window.',
    topic: 'animals',
    difficulty: 'hard',
  },
  {
    id: 'a-h-x6',
    han: '大魚游得好快。',
    jp: 'daai6 jyu2 jau4 dak1 hou2 faai3',
    def: 'The big fish swims very fast.',
    topic: 'animals',
    difficulty: 'hard',
  },
  {
    id: 'a-h-x7',
    han: '白鴿飛返屋企。',
    jp: 'baak6 gap3 fei1 faan1 uk1 kei2',
    def: 'The pigeon flies back home.',
    topic: 'animals',
    difficulty: 'hard',
  },
  {
    id: 'a-h-x8',
    han: '蜜蜂喺花叢度採蜜。',
    jp: 'mat6 fung1 hai2 faa1 cung4 dou6 coi2 mat6',
    def: 'Bees gather honey among the flowers.',
    topic: 'animals',
    difficulty: 'hard',
  },
  {
    id: 'a-h-x9',
    han: '馬仔喺草地度跑。',
    jp: 'maa5 zai2 hai2 cou2 dei6 dou6 paau2',
    def: 'The foal runs on the grass.',
    topic: 'animals',
    difficulty: 'hard',
  },
  {
    id: 'a-h-x10',
    han: '烏龜爬得好慢。',
    jp: 'wu1 gwai1 paa4 dak1 hou2 maan6',
    def: 'The turtle crawls very slowly.',
    topic: 'animals',
    difficulty: 'hard',
  },
  {
    id: 'a-h-x11',
    han: '夜晩貓頭鷹會叫。',
    jp: 'je6 maan5 maau1 tau4 jing1 wui5 giu3',
    def: 'Owls hoot at night.',
    topic: 'animals',
    difficulty: 'hard',
  },
  {
    id: 'a-h-x12',
    han: '河裏面有青蛙同小魚。',
    jp: 'ho4 leoi5 min6 jau5 cing1 waa1 tung4 siu2 jyu2',
    def: 'There are frogs and little fish in the river.',
    topic: 'animals',
    difficulty: 'hard',
  },
  {
    id: 'a-h-x13',
    han: '龍蝦生猛又新鮮。',
    jp: 'lung4 haa1 saang1 maang5 jau6 san1 sin1',
    def: 'The lobster is lively and fresh.',
    topic: 'animals',
    difficulty: 'hard',
  },
  {
    id: 'a-h-x14',
    han: '大象用鼻捲樹葉。',
    jp: 'daai6 zoeng6 jung6 bei6 gyun2 syu6 jip6',
    def: 'Elephants wrap leaves with their trunks.',
    topic: 'animals',
    difficulty: 'hard',
  },
  {
    id: 'a-h-x15',
    han: '蝴蝶停喺花上面。',
    jp: 'wu4 dip6 ting4 hai2 faa1 soeng6 min6',
    def: 'A butterfly lands on a flower.',
    topic: 'animals',
    difficulty: 'hard',
  },
  {
    id: 'a-h-x16',
    han: '鯊魚喺深海度游。',
    jp: 'saa1 jyu4 hai2 sam1 hoi2 dou6 jau4',
    def: 'Sharks swim in the deep sea.',
    topic: 'animals',
    difficulty: 'hard',
  },
  {
    id: 'a-h-x17',
    han: '羊群喺山坡食草。',
    jp: 'joeng4 kwan4 hai2 saan1 po1 sik6 cou2',
    def: 'The flock grazes on the hillside.',
    topic: 'animals',
    difficulty: 'hard',
  },
  {
    id: 'a-h-x18',
    han: '鸚鵡識學人講嘢。',
    jp: 'jing1 mou5 sik1 hok6 jan4 gong2 je5',
    def: 'Parrots can mimic speech.',
    topic: 'animals',
    difficulty: 'hard',
  },
  {
    id: 'a-h-x19',
    han: '今晚我喺水族館睇鯨。',
    jp: 'gam1 maan5 ngo5 hai2 seoi2 zuk1 gun2 tai2 king4',
    def: 'Tonight I’m watching whales at the aquarium.',
    topic: 'animals',
    difficulty: 'hard',
  },
  { id: 'n-e-x0-wan4', han: '雲', jp: 'wan4', def: 'cloud', topic: 'nature', difficulty: 'easy' },
  { id: 'n-e-x1-syut3', han: '雪', jp: 'syut3', def: 'snow', topic: 'nature', difficulty: 'easy' },
  { id: 'n-e-x2-lou6', han: '露', jp: 'lou6', def: 'dew', topic: 'nature', difficulty: 'easy' },
  { id: 'n-e-x3-mou6', han: '霧', jp: 'mou6', def: 'fog', topic: 'nature', difficulty: 'easy' },
  { id: 'n-e-x4-leoi4', han: '雷', jp: 'leoi4', def: 'thunder', topic: 'nature', difficulty: 'easy' },
  { id: 'n-e-x5-din6', han: '電', jp: 'din6', def: 'lightning / electricity', topic: 'nature', difficulty: 'easy' },
  { id: 'n-e-x6-bing1', han: '冰', jp: 'bing1', def: 'ice', topic: 'nature', difficulty: 'easy' },
  { id: 'n-e-x7-fo2', han: '火', jp: 'fo2', def: 'fire', topic: 'nature', difficulty: 'easy' },
  { id: 'n-e-x8-tou2', han: '土', jp: 'tou2', def: 'earth / soil', topic: 'nature', difficulty: 'easy' },
  { id: 'n-e-x9-sek6', han: '石', jp: 'sek6', def: 'stone', topic: 'nature', difficulty: 'easy' },
  { id: 'n-e-x10-saa1', han: '沙', jp: 'saa1', def: 'sand', topic: 'nature', difficulty: 'easy' },
  { id: 'n-e-x11-cou2', han: '草', jp: 'cou2', def: 'grass', topic: 'nature', difficulty: 'easy' },
  { id: 'n-e-x12-jip6', han: '葉', jp: 'jip6', def: 'leaf', topic: 'nature', difficulty: 'easy' },
  { id: 'n-e-x13-zi1', han: '枝', jp: 'zi1', def: 'branch', topic: 'nature', difficulty: 'easy' },
  { id: 'n-e-x14-gan1', han: '根', jp: 'gan1', def: 'root', topic: 'nature', difficulty: 'easy' },
  { id: 'n-e-x15-gwo2', han: '果', jp: 'gwo2', def: 'fruit', topic: 'nature', difficulty: 'easy' },
  { id: 'n-e-x16-zuk1', han: '竹', jp: 'zuk1', def: 'bamboo', topic: 'nature', difficulty: 'easy' },
  { id: 'n-e-x17-cung4', han: '松', jp: 'cung4', def: 'pine', topic: 'nature', difficulty: 'easy' },
  { id: 'n-e-x18-mui4', han: '梅', jp: 'mui4', def: 'plum blossom', topic: 'nature', difficulty: 'easy' },
  { id: 'n-e-x19-lin4', han: '蓮', jp: 'lin4', def: 'lotus', topic: 'nature', difficulty: 'easy' },
  { id: 'n-e-x20-heoi2', han: '曉', jp: 'hiu2', def: 'dawn', topic: 'nature', difficulty: 'easy' },
  { id: 'n-e-x21-je6', han: '夜', jp: 'je6', def: 'night', topic: 'nature', difficulty: 'easy' },
  { id: 'n-e-x22-ziu1', han: '朝', jp: 'ziu1', def: 'morning', topic: 'nature', difficulty: 'easy' },
  { id: 'n-e-x23-maan5', han: '晚', jp: 'maan5', def: 'evening', topic: 'nature', difficulty: 'easy' },
  { id: 'n-e-x24-dung1', han: '冬', jp: 'dung1', def: 'winter', topic: 'nature', difficulty: 'easy' },
  { id: 'n-e-x25-haa6', han: '夏', jp: 'haa6', def: 'summer', topic: 'nature', difficulty: 'easy' },
  { id: 'n-e-x26-ceon1', han: '春', jp: 'ceon1', def: 'spring', topic: 'nature', difficulty: 'easy' },
  { id: 'n-e-x27-cau1', han: '秋', jp: 'cau1', def: 'autumn', topic: 'nature', difficulty: 'easy' },
  { id: 'n-e-x28-nam4', han: '南', jp: 'naam4', def: 'south', topic: 'nature', difficulty: 'easy' },
  { id: 'n-e-x29-bak1', han: '北', jp: 'bak1', def: 'north', topic: 'nature', difficulty: 'easy' },
  { id: 'n-m-x0-lok6syut3', han: '落雪', jp: 'lok6 syut3', def: 'to snow', topic: 'nature', difficulty: 'medium' },
  { id: 'n-m-x1-daa2fung1', han: '打風', jp: 'daa2 fung1', def: 'typhoon / stormy', topic: 'nature', difficulty: 'medium' },
  { id: 'n-m-x2-mou6seoi2', han: '霧水', jp: 'mou6 seoi2', def: 'mist / dew', topic: 'nature', difficulty: 'medium' },
  { id: 'n-m-x3-bing1syut3', han: '冰雪', jp: 'bing1 syut3', def: 'ice and snow', topic: 'nature', difficulty: 'medium' },
  { id: 'n-m-x4-hung4jat6', han: '紅日', jp: 'hung4 jat6', def: 'red sun', topic: 'nature', difficulty: 'medium' },
  { id: 'n-m-x5-jyut6gwong1', han: '月光', jp: 'jyut6 gwong1', def: 'moonlight', topic: 'nature', difficulty: 'medium' },
  { id: 'n-m-x6-sing1sing1', han: '星星', jp: 'sing1 sing1', def: 'stars', topic: 'nature', difficulty: 'medium' },
  { id: 'n-m-x7-baak6saa1', han: '白沙', jp: 'baak6 saa1', def: 'white sand', topic: 'nature', difficulty: 'medium' },
  { id: 'n-m-x8-lou5syu6', han: '老樹', jp: 'lou5 syu6', def: 'old tree', topic: 'nature', difficulty: 'medium' },
  { id: 'n-m-x9-san1faa1', han: '新花', jp: 'san1 faa1', def: 'new blossom', topic: 'nature', difficulty: 'medium' },
  { id: 'n-m-x10-cing1saan1', han: '青山', jp: 'cing1 saan1', def: 'green mountain', topic: 'nature', difficulty: 'medium' },
  { id: 'n-m-x11-luk6seoi2', han: '綠水', jp: 'luk6 seoi2', def: 'green water', topic: 'nature', difficulty: 'medium' },
  { id: 'n-m-x12-dung1tin1', han: '冬天', jp: 'dung1 tin1', def: 'winter', topic: 'nature', difficulty: 'medium' },
  { id: 'n-m-x13-haa6tin1', han: '夏天', jp: 'haa6 tin1', def: 'summer', topic: 'nature', difficulty: 'medium' },
  { id: 'n-m-x14-ceon1jyu5', han: '春雨', jp: 'ceon1 jyu5', def: 'spring rain', topic: 'nature', difficulty: 'medium' },
  { id: 'n-m-x15-cau1fung1', han: '秋風', jp: 'cau1 fung1', def: 'autumn wind', topic: 'nature', difficulty: 'medium' },
  { id: 'n-m-x16-seoi2pou5', han: '水泡', jp: 'seoi2 pou5', def: 'bubble', topic: 'nature', difficulty: 'medium' },
  { id: 'n-m-x17-fo2saan1', han: '火山', jp: 'fo2 saan1', def: 'volcano', topic: 'nature', difficulty: 'medium' },
  { id: 'n-m-x18-bing1saan1', han: '冰山', jp: 'bing1 saan1', def: 'iceberg', topic: 'nature', difficulty: 'medium' },
  { id: 'n-m-x19-saa1kau1', han: '沙丘', jp: 'saa1 jau1', def: 'sand dune', topic: 'nature', difficulty: 'medium' },
  { id: 'n-m-x20-zuk1lin4', han: '竹簾', jp: 'zuk1 lim4', def: 'bamboo blind', topic: 'nature', difficulty: 'medium' },
  { id: 'n-m-x21-mui4faa1', han: '梅花', jp: 'mui4 faa1', def: 'plum blossom', topic: 'nature', difficulty: 'medium' },
  { id: 'n-m-x22-lin4faa1', han: '蓮花', jp: 'lin4 faa1', def: 'lotus flower', topic: 'nature', difficulty: 'medium' },
  { id: 'n-m-x23-cung4syu6', han: '松樹', jp: 'cung4 syu6', def: 'pine tree', topic: 'nature', difficulty: 'medium' },
  { id: 'n-m-x24-jip6zi2', han: '葉子', jp: 'jip6 zi2', def: 'leaf', topic: 'nature', difficulty: 'medium' },
  { id: 'n-m-x25-syu6gan1', han: '樹根', jp: 'syu6 gan1', def: 'tree root', topic: 'nature', difficulty: 'medium' },
  { id: 'n-m-x26-tin1hung1', han: '天空', jp: 'tin1 hung1', def: 'the sky', topic: 'nature', difficulty: 'medium' },
  { id: 'n-m-x27-daai6hoi2', han: '大海', jp: 'daai6 hoi2', def: 'the ocean', topic: 'nature', difficulty: 'medium' },
  { id: 'n-m-x28-siu2ho4', han: '小河', jp: 'siu2 ho4', def: 'brook / stream', topic: 'nature', difficulty: 'medium' },
  { id: 'n-m-x29-gou1saan1', han: '高山', jp: 'gou1 saan1', def: 'high mountain', topic: 'nature', difficulty: 'medium' },
  { id: 'n-m-x30-cing4hung4', han: '晴空', jp: 'cing4 hung1', def: 'clear sky', topic: 'nature', difficulty: 'medium' },
  { id: 'n-m-x31-hak1je6', han: '黑夜', jp: 'hak1 je6', def: 'dark night', topic: 'nature', difficulty: 'medium' },
  {
    id: 'n-h-x0',
    han: '春天啲花開得好靚。',
    jp: 'ceon1 tin1 di1 faa1 hoi1 dak1 hou2 leng3',
    def: 'Spring flowers bloom beautifully.',
    topic: 'nature',
    difficulty: 'hard',
  },
  {
    id: 'n-h-x1',
    han: '夏天熱到要食雪糕。',
    jp: 'haa6 tin1 jit6 dou3 jiu3 sik6 syut3 gou1',
    def: 'Summer is so hot you need ice cream.',
    topic: 'nature',
    difficulty: 'hard',
  },
  {
    id: 'n-h-x2',
    han: '秋風一吹，樹葉黃晒。',
    jp: 'cau1 fung1 jat1 ceoi1, syu6 jip6 wong4 saai3',
    def: 'When autumn wind blows, leaves turn yellow.',
    topic: 'nature',
    difficulty: 'hard',
  },
  {
    id: 'n-h-x3',
    han: '冬天下雪，山上一片白。',
    jp: 'dung1 tin1 haa6 syut3, saan1 soeng6 jat1 pin3 baak6',
    def: 'It snows in winter — the mountain is all white.',
    topic: 'nature',
    difficulty: 'hard',
  },
  {
    id: 'n-h-x4',
    han: '今夜月光好光。',
    jp: 'gam1 je6 jyut6 gwong1 hou2 gwong1',
    def: 'The moonlight is bright tonight.',
    topic: 'nature',
    difficulty: 'hard',
  },
  {
    id: 'n-h-x5',
    han: '聽朝可能會打風。',
    jp: 'ting1 ziu1 ho2 nang4 wui5 daa2 fung1',
    def: 'There might be a storm tomorrow morning.',
    topic: 'nature',
    difficulty: 'hard',
  },
  {
    id: 'n-h-x6',
    han: '河水涼涼地流過石頭。',
    jp: 'ho4 seoi2 loeng4 loeng2 dei2 lau4 gwo3 sek6 tau4',
    def: 'Cool river water flows over the stones.',
    topic: 'nature',
    difficulty: 'hard',
  },
  {
    id: 'n-h-x7',
    han: '霧大到睇唔清路。',
    jp: 'mou6 daai6 dou3 tai2 m4 cing1 lou6',
    def: 'The fog is so thick you can’t see the road.',
    topic: 'nature',
    difficulty: 'hard',
  },
  {
    id: 'n-h-x8',
    han: '榕樹下好陰涼。',
    jp: 'jung4 syu6 haa6 hou2 jam1 loeng4',
    def: 'It’s shady and cool under the banyan.',
    topic: 'nature',
    difficulty: 'hard',
  },
  {
    id: 'n-h-x9',
    han: '海邊吹住鹹鹹嘅風。',
    jp: 'hoi2 bin1 ceoi1 zyu6 haam4 haam2 ge3 fung1',
    def: 'A salty wind blows by the sea.',
    topic: 'nature',
    difficulty: 'hard',
  },
  {
    id: 'n-h-x10',
    han: '竹林裏面有蟬聲。',
    jp: 'zuk1 lam4 leoi5 min6 jau5 sim4 seng1',
    def: 'There are cicadas chirping in the bamboo grove.',
    topic: 'nature',
    difficulty: 'hard',
  },
  {
    id: 'n-h-x11',
    han: '夜空掛滿閃閃星星。',
    jp: 'je6 hung1 gwaa3 mun5 sim2 sim2 sing1 sing1',
    def: 'The night sky is full of twinkling stars.',
    topic: 'nature',
    difficulty: 'hard',
  },
  {
    id: 'n-h-x12',
    han: '雷公響完就落大雨。',
    jp: 'leoi4 gung1 hoeng2 jyun4 zau6 lok6 daai6 jyu5',
    def: 'After thunder, heavy rain falls.',
    topic: 'nature',
    difficulty: 'hard',
  },
  {
    id: 'n-h-x13',
    han: '沙灘腳印一排排。',
    jp: 'saa1 taan1 goek3 jan3 jat1 paai4 paai4',
    def: 'Footprints line the beach.',
    topic: 'nature',
    difficulty: 'hard',
  },
  {
    id: 'n-h-x14',
    han: '火山口冒住煙。',
    jp: 'fo2 saan1 hau2 mou6 zyu6 jin1',
    def: 'Smoke rises from the volcano crater.',
    topic: 'nature',
    difficulty: 'hard',
  },
  {
    id: 'n-h-x15',
    han: '露水喺葉尖閃光。',
    jp: 'lou6 seoi2 hai2 jip6 zim1 sim2 gwong1',
    def: 'Dew sparkles on leaf tips.',
    topic: 'nature',
    difficulty: 'hard',
  },
  {
    id: 'n-h-x16',
    han: '高山上面空氣好清新。',
    jp: 'gou1 saan1 soeng6 min6 hung1 hei3 hou2 cing1 san1',
    def: 'The air is fresh up on the high mountain.',
    topic: 'nature',
    difficulty: 'hard',
  },
  {
    id: 'n-h-x17',
    han: '秋天楓葉紅得好靚。',
    jp: 'cau1 tin1 fung1 jip6 hung4 dak1 hou2 leng3',
    def: 'Autumn maple leaves are a gorgeous red.',
    topic: 'nature',
    difficulty: 'hard',
  },
  {
    id: 'n-h-x18',
    han: '河中央有一塊大石。',
    jp: 'ho4 zung1 joeng1 jau5 jat1 faai3 daai6 sek6',
    def: 'There’s a big rock in the middle of the river.',
    topic: 'nature',
    difficulty: 'hard',
  },
  {
    id: 'n-h-x19',
    han: '朝早太陽慢慢升起。',
    jp: 'ziu1 zou2 taai3 joeng4 maan6 maan2 sing1 hei2',
    def: 'The sun rises slowly in the morning.',
    topic: 'nature',
    difficulty: 'hard',
  },
  { id: 'f-e-x0-tong1', han: '湯', jp: 'tong1', def: 'soup', topic: 'food', difficulty: 'easy' },
  { id: 'f-e-x1-zap1', han: '汁', jp: 'zap1', def: 'juice / sauce', topic: 'food', difficulty: 'easy' },
  { id: 'f-e-x2-jau4', han: '油', jp: 'jau4', def: 'oil', topic: 'food', difficulty: 'easy' },
  { id: 'f-e-x3-cou2', han: '醋', jp: 'cou3', def: 'vinegar', topic: 'food', difficulty: 'easy' },
  { id: 'f-e-x4-zoek3', han: '醬', jp: 'zoeng3', def: 'sauce / paste', topic: 'food', difficulty: 'easy' },
  { id: 'f-e-x5-min6baau1', han: '麵包', jp: 'min6 baau1', def: 'bread', topic: 'food', difficulty: 'easy' },
  { id: 'f-e-x6-beng2', han: '餅', jp: 'beng2', def: 'cake / biscuit', topic: 'food', difficulty: 'easy' },
  { id: 'f-e-x7-gou1', han: '糕', jp: 'gou1', def: 'cake / pudding', topic: 'food', difficulty: 'easy' },
  { id: 'f-e-x8-zyu1juk6', han: '豬肉', jp: 'zyu1 juk6', def: 'pork', topic: 'food', difficulty: 'easy' },
  { id: 'f-e-x9-ngau4juk6', han: '牛肉', jp: 'ngau4 juk6', def: 'beef', topic: 'food', difficulty: 'easy' },
  { id: 'f-e-x10-gai1juk6', han: '雞肉', jp: 'gai1 juk6', def: 'chicken meat', topic: 'food', difficulty: 'easy' },
  { id: 'f-e-x11-jyu2pin2', han: '魚片', jp: 'jyu2 pin2', def: 'fish fillet', topic: 'food', difficulty: 'easy' },
  { id: 'f-e-x12-haa1yan2', han: '蝦仁', jp: 'haa1 jan4', def: 'shrimp meat', topic: 'food', difficulty: 'easy' },
  { id: 'f-e-x13-daan6gou1', han: '蛋糕', jp: 'daan6 gou1', def: 'cake', topic: 'food', difficulty: 'easy' },
  { id: 'f-e-x14-syut3gou1', han: '雪糕', jp: 'syut3 gou1', def: 'ice cream', topic: 'food', difficulty: 'easy' },
  { id: 'f-e-x15-naai5caai4', han: '奶茶', jp: 'naai5 caa4', def: 'milk tea', topic: 'food', difficulty: 'easy' },
  { id: 'f-e-x16-gafaa1', han: '咖啡', jp: 'gaa3 fe1', def: 'coffee', topic: 'food', difficulty: 'easy' },
  { id: 'f-e-x17-be1zau2', han: '啤酒', jp: 'be1 zau2', def: 'beer', topic: 'food', difficulty: 'easy' },
  { id: 'f-e-x18-hung4zau2', han: '紅酒', jp: 'hung4 zau2', def: 'red wine', topic: 'food', difficulty: 'easy' },
  { id: 'f-e-x19-baak6faan6', han: '白飯', jp: 'baak6 faan6', def: 'white rice', topic: 'food', difficulty: 'easy' },
  { id: 'f-e-x20-caau2faan6', han: '炒飯', jp: 'caau2 faan6', def: 'fried rice', topic: 'food', difficulty: 'easy' },
  { id: 'f-e-x21-caau2min6', han: '炒麵', jp: 'caau2 min6', def: 'fried noodles', topic: 'food', difficulty: 'easy' },
  { id: 'f-e-x22-wan4tan1', han: '雲吞', jp: 'wan4 tan1', def: 'wonton', topic: 'food', difficulty: 'easy' },
  { id: 'f-e-x23-siu1maai2', han: '燒賣', jp: 'siu1 maai2', def: 'siu mai', topic: 'food', difficulty: 'easy' },
  { id: 'f-e-x24-haa2gaau2', han: '蝦餃', jp: 'haa1 gaau2', def: 'har gow', topic: 'food', difficulty: 'easy' },
  { id: 'f-m-x0-jat1wun2', han: '一碗', jp: 'jat1 wun2', def: 'one bowl', topic: 'food', difficulty: 'medium' },
  { id: 'f-m-x1-loeng5dip6', han: '兩碟', jp: 'loeng5 dip6', def: 'two plates', topic: 'food', difficulty: 'medium' },
  { id: 'f-m-x2-saat3ziu1', han: '辣椒', jp: 'laat6 ziu1', def: 'chili', topic: 'food', difficulty: 'medium' },
  { id: 'f-m-x3-tim4syun1', han: '甜酸', jp: 'tim4 syun1', def: 'sweet and sour', topic: 'food', difficulty: 'medium' },
  { id: 'f-m-x4-haam4sin1', han: '鹹鮮', jp: 'haam4 sin1', def: 'savory / salty-fresh', topic: 'food', difficulty: 'medium' },
  { id: 'f-m-x5-jit6lat6', han: '熱辣', jp: 'jit6 laat6', def: 'hot and spicy', topic: 'food', difficulty: 'medium' },
  { id: 'f-m-x6-dung3jam2', han: '凍飲', jp: 'dung3 jam2', def: 'cold drink', topic: 'food', difficulty: 'medium' },
  { id: 'f-m-x7-jit6tong1', han: '熱湯', jp: 'jit6 tong1', def: 'hot soup', topic: 'food', difficulty: 'medium' },
  { id: 'f-m-x8-caau2coi3', han: '炒菜', jp: 'caau2 coi3', def: 'stir-fried vegetables', topic: 'food', difficulty: 'medium' },
  { id: 'f-m-x9-zing1jyu2', han: '蒸魚', jp: 'zing1 jyu2', def: 'steamed fish', topic: 'food', difficulty: 'medium' },
  { id: 'f-m-x10-siu1ngo4', han: '燒鵝', jp: 'siu1 ngo2', def: 'roast goose', topic: 'food', difficulty: 'medium' },
  { id: 'f-m-x11-baak6cit3', han: '白切', jp: 'baak6 cit3', def: 'poached (chicken)', topic: 'food', difficulty: 'medium' },
  { id: 'f-m-x12-daan1daan1min6', han: '蛋蛋麵', jp: 'daan2 daan2 min6', def: 'egg noodles', topic: 'food', difficulty: 'medium' },
  { id: 'f-m-x13-ngau4lam1min6', han: '牛腩麵', jp: 'ngau4 naam5 min6', def: 'beef brisket noodles', topic: 'food', difficulty: 'medium' },
  { id: 'f-m-x14-caau2sin1ho2', han: '炒鮮蠔', jp: 'caau2 sin1 hou4', def: 'stir-fried oysters', topic: 'food', difficulty: 'medium' },
  { id: 'f-m-x15-lou5fo2gwai3', han: '老火湯', jp: 'lou5 fo2 tong1', def: 'slow-cooked soup', topic: 'food', difficulty: 'medium' },
  { id: 'f-m-x16-jin4wo1', han: '燕窩', jp: 'jin3 wo1', def: 'bird’s nest', topic: 'food', difficulty: 'medium' },
  { id: 'f-m-x17-baak6gwo2', han: '百果', jp: 'baak6 gwo2', def: 'assorted fruit', topic: 'food', difficulty: 'medium' },
  { id: 'f-m-x18-ping4gwo2zap1', han: '蘋果汁', jp: 'ping4 gwo2 zap1', def: 'apple juice', topic: 'food', difficulty: 'medium' },
  { id: 'f-m-x19-caang2zap1', han: '橙汁', jp: 'caang2 zap1', def: 'orange juice', topic: 'food', difficulty: 'medium' },
  { id: 'f-m-x20-syut3beng2', han: '雪餅', jp: 'syut3 beng2', def: 'snow biscuit', topic: 'food', difficulty: 'medium' },
  { id: 'f-m-x21-faa1saang1tong4', han: '花生糖', jp: 'faa1 saang1 tong4', def: 'peanut candy', topic: 'food', difficulty: 'medium' },
  { id: 'f-m-x22-lou5jau4caau2min6', han: '撈麵', jp: 'lou1 min6', def: 'tossed noodles', topic: 'food', difficulty: 'medium' },
  { id: 'f-m-x23-tong4seoi2', han: '糖水', jp: 'tong4 seoi2', def: 'sweet soup dessert', topic: 'food', difficulty: 'medium' },
  { id: 'f-m-x24-bou1din1', han: '布丁', jp: 'bou1 din1', def: 'pudding', topic: 'food', difficulty: 'medium' },
  { id: 'f-m-x25-zyu1gu1lik1', han: '朱古力', jp: 'zyu1 gu1 lik1', def: 'chocolate', topic: 'food', difficulty: 'medium' },
  { id: 'f-m-x26-hoeng1liu2', han: '香料', jp: 'hoeng1 liu2', def: 'spice', topic: 'food', difficulty: 'medium' },
  { id: 'f-m-x27-jim4juk6', han: '鹽焗', jp: 'jim4 guk6', def: 'salt-baked', topic: 'food', difficulty: 'medium' },
  { id: 'f-m-x28-sik6baau2', han: '食飽', jp: 'sik6 baau2', def: 'to eat until full', topic: 'food', difficulty: 'medium' },
  { id: 'f-m-x29-ngo6', han: '餓', jp: 'ngo6', def: 'hungry', topic: 'food', difficulty: 'medium' },
  { id: 'f-m-x30-hau2hot3', han: '口渴', jp: 'hau2 hot3', def: 'thirsty', topic: 'food', difficulty: 'medium' },
  { id: 'f-m-x31-hou2jam2', han: '好飲', jp: 'hou2 jam2', def: 'tasty to drink', topic: 'food', difficulty: 'medium' },
  {
    id: 'f-h-x0',
    han: '呢碗雲吞麵好熱辣。',
    jp: 'ni1 wun2 wan4 tan1 min6 hou2 jit6 laat6',
    def: 'This bowl of wonton noodles is piping hot.',
    topic: 'food',
    difficulty: 'hard',
  },
  {
    id: 'f-h-x1',
    han: '我想叫一碟蝦餃。',
    jp: 'ngo5 soeng2 giu3 jat1 dip6 haa1 gaau2',
    def: 'I’d like to order a plate of har gow.',
    topic: 'food',
    difficulty: 'hard',
  },
  {
    id: 'f-h-x2',
    han: '燒鵝配白切雞最好食。',
    jp: 'siu1 ngo2 pui3 baak6 cit3 gai1 zeoi3 hou2 sik6',
    def: 'Roast goose with poached chicken is the best.',
    topic: 'food',
    difficulty: 'hard',
  },
  {
    id: 'f-h-x3',
    han: '凍奶茶加珍珠好香。',
    jp: 'dung3 naai5 caa4 gaa1 zan1 zyu1 hou2 hoeng1',
    def: 'Iced milk tea with pearls smells great.',
    topic: 'food',
    difficulty: 'hard',
  },
  {
    id: 'f-h-x4',
    han: '老闆，有冇蒸魚？',
    jp: 'lou5 baan2, jau5 mou5 zing1 jyu2',
    def: 'Boss — do you have steamed fish?',
    topic: 'food',
    difficulty: 'hard',
  },
  {
    id: 'f-h-x5',
    han: '糖水要少甜少冰。',
    jp: 'tong4 seoi2 jiu3 siu2 tim4 siu2 bing1',
    def: 'Make the sweet soup less sweet and less ice.',
    topic: 'food',
    difficulty: 'hard',
  },
  {
    id: 'f-h-x6',
    han: '今日特價係牛腩麵。',
    jp: 'gam1 jat6 dak6 gaa3 hai6 ngau4 naam5 min6',
    def: 'Today’s special is beef brisket noodles.',
    topic: 'food',
    difficulty: 'hard',
  },
  {
    id: 'f-h-x7',
    han: '朱古力蛋糕甜到入心。',
    jp: 'zyu1 gu1 lik1 daan6 gou1 tim4 dou3 jap6 sam1',
    def: 'The chocolate cake is sweetly rich.',
    topic: 'food',
    difficulty: 'hard',
  },
  {
    id: 'f-h-x8',
    han: '唔該再添一碗白飯。',
    jp: 'm4 goi1 zoi3 tim1 jat1 wun2 baak6 faan6',
    def: 'Please add another bowl of rice.',
    topic: 'food',
    difficulty: 'hard',
  },
  {
    id: 'f-h-x9',
    han: '呢杯咖啡要走甜。',
    jp: 'ni1 bui1 gaa3 fe1 jiu3 zau2 tim4',
    def: 'This coffee — no sugar, please.',
    topic: 'food',
    difficulty: 'hard',
  },
  {
    id: 'f-h-x10',
    han: '點心推車過嚟喇。',
    jp: 'dim2 sam1 teoi1 ce1 gwo3 lai4 laa3',
    def: 'The dim sum cart is coming.',
    topic: 'food',
    difficulty: 'hard',
  },
  {
    id: 'f-h-x11',
    han: '海鮮要新鮮先好食。',
    jp: 'hoi2 sin1 jiu3 san1 sin1 sin1 hou2 sik6',
    def: 'Seafood only tastes good when fresh.',
    topic: 'food',
    difficulty: 'hard',
  },
  {
    id: 'f-h-x12',
    han: '辣椒放少啲，我怕辣。',
    jp: 'laat6 ziu1 fong3 siu2 di1, ngo5 paa3 laat6',
    def: 'Go easy on the chili — I can’t take spice.',
    topic: 'food',
    difficulty: 'hard',
  },
  {
    id: 'f-h-x13',
    han: '早餐食麵包同雞蛋。',
    jp: 'zou2 caan1 sik6 min6 baau1 tung4 gai1 daan2',
    def: 'Breakfast is bread and eggs.',
    topic: 'food',
    difficulty: 'hard',
  },
  {
    id: 'f-h-x14',
    han: '晚餐我想飲老火湯。',
    jp: 'maan5 caan1 ngo5 soeng2 jam2 lou5 fo2 tong1',
    def: 'I want slow-cooked soup for dinner.',
    topic: 'food',
    difficulty: 'hard',
  },
  {
    id: 'f-h-x15',
    han: '蘋果同香蕉擺喺枱上。',
    jp: 'ping4 gwo2 tung4 hoeng1 ziu1 baai2 hai2 toi2 soeng6',
    def: 'Apples and bananas are on the table.',
    topic: 'food',
    difficulty: 'hard',
  },
  {
    id: 'f-h-x16',
    han: '埋單用八達通得唔得？',
    jp: 'maai4 daan1 jung6 baat3 daat6 tung1 dak1 m4 dak1',
    def: 'Can I pay the bill with Octopus?',
    topic: 'food',
    difficulty: 'hard',
  },
  {
    id: 'f-h-x17',
    han: '呢碟炒飯油分有啲重。',
    jp: 'ni1 dip6 caau2 faan6 jau4 fan6 jau5 di1 cung5',
    def: 'This fried rice is a bit oily.',
    topic: 'food',
    difficulty: 'hard',
  },
  {
    id: 'f-h-x18',
    han: '甜品我想食雪糕。',
    jp: 'tim4 ban2 ngo5 soeng2 sik6 syut3 gou1',
    def: 'For dessert I want ice cream.',
    topic: 'food',
    difficulty: 'hard',
  },
  {
    id: 'f-h-x19',
    han: '請再畀一壺熱茶。',
    jp: 'cing2 zoi3 bei2 jat1 wu4 jit6 caa4',
    def: 'Please bring another pot of hot tea.',
    topic: 'food',
    difficulty: 'hard',
  },
  { id: 'h-e-x0-long6', han: '浪', jp: 'long6', def: 'wave', topic: 'harbor', difficulty: 'easy' },
  { id: 'h-e-x1-ciu4', han: '潮', jp: 'ciu4', def: 'tide', topic: 'harbor', difficulty: 'easy' },
  { id: 'h-e-x2-gau2', han: '錨', jp: 'naau4', def: 'anchor', topic: 'harbor', difficulty: 'easy' },
  { id: 'h-e-x3-so2', han: '鎖', jp: 'so2', def: 'lock', topic: 'harbor', difficulty: 'easy' },
  { id: 'h-e-x4-sing4', han: '繩', jp: 'sing4', def: 'rope', topic: 'harbor', difficulty: 'easy' },
  { id: 'h-e-x5-buk1', han: '泊', jp: 'bok1', def: 'to moor', topic: 'harbor', difficulty: 'easy' },
  { id: 'h-e-x6-hang4', han: '航', jp: 'hong4', def: 'to sail / voyage', topic: 'harbor', difficulty: 'easy' },
  { id: 'h-e-x7-gong2', han: '港', jp: 'gong2', def: 'harbor / port', topic: 'harbor', difficulty: 'easy' },
  { id: 'h-e-x8-wau1', han: '灣', jp: 'waan1', def: 'bay', topic: 'harbor', difficulty: 'easy' },
  { id: 'h-e-x9-tou4', han: '島', jp: 'dou2', def: 'island', topic: 'harbor', difficulty: 'easy' },
  { id: 'h-e-x10-zek3', han: '隻', jp: 'zek3', def: 'classifier for boats', topic: 'harbor', difficulty: 'easy' },
  { id: 'h-e-x11-soeng1', han: '艙', jp: 'cong1', def: 'cabin / hold', topic: 'harbor', difficulty: 'easy' },
  { id: 'h-e-x12-daai3', han: '舵', jp: 'to4', def: 'rudder', topic: 'harbor', difficulty: 'easy' },
  { id: 'h-e-x13-lei5', han: '里', jp: 'lei5', def: 'mile / distance', topic: 'harbor', difficulty: 'easy' },
  { id: 'h-e-x14-lei5ceng4', han: '里程', jp: 'lei5 cing4', def: 'mileage', topic: 'harbor', difficulty: 'easy' },
  { id: 'h-e-x15-fung1hoeng3', han: '風向', jp: 'fung1 hoeng3', def: 'wind direction', topic: 'harbor', difficulty: 'easy' },
  { id: 'h-e-x16-seoi2ping4', han: '水平', jp: 'seoi2 ping4', def: 'water level', topic: 'harbor', difficulty: 'easy' },
  { id: 'h-e-x17-ngon6bin1', han: '岸邊', jp: 'ngon6 bin1', def: 'waterside', topic: 'harbor', difficulty: 'easy' },
  { id: 'h-e-x18-syun4tau2', han: '船頭', jp: 'syun4 tau4', def: 'bow (of a boat)', topic: 'harbor', difficulty: 'easy' },
  { id: 'h-e-x19-syun4mei5', han: '船尾', jp: 'syun4 mei5', def: 'stern', topic: 'harbor', difficulty: 'easy' },
  { id: 'h-e-y0-dang1lung4', han: '燈籠', jp: 'dang1 lung4', def: 'lantern', topic: 'harbor', difficulty: 'easy' },
  { id: 'h-e-y1-lou5gung1', han: '老工', jp: 'lou5 gung1', def: 'old worker', topic: 'harbor', difficulty: 'easy' },
  { id: 'h-e-y2-seoi2sau2', han: '水手', jp: 'seoi2 sau2', def: 'sailor', topic: 'harbor', difficulty: 'easy' },
  { id: 'h-e-y3-syun4zoeng2', han: '船長', jp: 'syun4 zoeng2', def: 'captain', topic: 'harbor', difficulty: 'easy' },
  { id: 'h-m-y4-maa5tau4gung1', han: '碼頭工', jp: 'maa5 tau4 gung1', def: 'docker', topic: 'harbor', difficulty: 'medium' },
  { id: 'h-e-y5-faan4bou3', han: '帆布', jp: 'faan4 bou3', def: 'canvas', topic: 'harbor', difficulty: 'easy' },
  { id: 'h-m-y6-seoi2lou6zi2', han: '水路誌', jp: 'seoi2 lou6 zi3', def: 'waterway log', topic: 'harbor', difficulty: 'medium' },
  { id: 'h-m-y7-hang4hoi2tou4', han: '航海圖', jp: 'hong4 hoi2 tou4', def: 'nautical chart', topic: 'harbor', difficulty: 'medium' },
  { id: 'h-m-y8-fung1jyu5biu1', han: '風雨標', jp: 'fung1 jyu5 biu1', def: 'weather mark', topic: 'harbor', difficulty: 'medium' },
  { id: 'h-m-y9-gam1cin2doi2', han: '金幣袋', jp: 'gam1 bai6 doi2', def: 'gold pouch', topic: 'harbor', difficulty: 'medium' },
  { id: 'h-m-x0-ceoi1fung1', han: '吹風', jp: 'ceoi1 fung1', def: 'windy / to blow', topic: 'harbor', difficulty: 'medium' },
  { id: 'h-m-x1-hei2long6', han: '起浪', jp: 'hei2 long6', def: 'waves rising', topic: 'harbor', difficulty: 'medium' },
  { id: 'h-m-x2-lok6ciu4', han: '落潮', jp: 'lok6 ciu4', def: 'ebb tide', topic: 'harbor', difficulty: 'medium' },
  { id: 'h-m-x3-soeng5ciu4', han: '上潮', jp: 'soeng5 ciu4', def: 'rising tide', topic: 'harbor', difficulty: 'medium' },
  { id: 'h-m-x4-bok1syun4', han: '泊船', jp: 'bok1 syun4', def: 'to moor a boat', topic: 'harbor', difficulty: 'medium' },
  { id: 'h-m-x5-hei2faan4', han: '起帆', jp: 'hei2 faan4', def: 'to raise sail', topic: 'harbor', difficulty: 'medium' },
  { id: 'h-m-x6-sau1faan4', han: '收帆', jp: 'sau1 faan4', def: 'to lower sail', topic: 'harbor', difficulty: 'medium' },
  { id: 'h-m-x7-waak6zoeng2', han: '划槳', jp: 'waak6 zoeng2', def: 'to paddle', topic: 'harbor', difficulty: 'medium' },
  { id: 'h-m-x8-taai1syun4', han: '睇船', jp: 'tai2 syun4', def: 'to watch the boat', topic: 'harbor', difficulty: 'medium' },
  { id: 'h-m-x9-sau2dang1', han: '手燈', jp: 'sau2 dang1', def: 'hand lantern', topic: 'harbor', difficulty: 'medium' },
  { id: 'h-m-x10-je6hong4', han: '夜航', jp: 'je6 hong4', def: 'night voyage', topic: 'harbor', difficulty: 'medium' },
  { id: 'h-m-x11-ping4on1', han: '平安', jp: 'ping4 on1', def: 'safe / peace', topic: 'harbor', difficulty: 'medium' },
  { id: 'h-m-x12-seoi2lou6zi1', han: '水路紙', jp: 'seoi2 lou6 zi2', def: 'passage slip', topic: 'harbor', difficulty: 'medium' },
  { id: 'h-m-x13-gong2hau2', han: '港口', jp: 'gong2 hau2', def: 'harbor mouth', topic: 'harbor', difficulty: 'medium' },
  { id: 'h-m-x14-dou2jyu4', han: '島嶼', jp: 'dou2 zeoi6', def: 'islands', topic: 'harbor', difficulty: 'medium' },
  { id: 'h-m-x15-waan1kok3', han: '灣角', jp: 'waan1 gok3', def: 'bay corner', topic: 'harbor', difficulty: 'medium' },
  { id: 'h-m-x16-syun4dui6', han: '船隊', jp: 'syun4 deoi2', def: 'fleet', topic: 'harbor', difficulty: 'medium' },
  { id: 'h-m-x17-hung4dang1', han: '紅燈', jp: 'hung4 dang1', def: 'red light', topic: 'harbor', difficulty: 'medium' },
  { id: 'h-m-x18-luk6dang1', han: '綠燈', jp: 'luk6 dang1', def: 'green light', topic: 'harbor', difficulty: 'medium' },
  { id: 'h-m-x19-baak6dang1', han: '白燈', jp: 'baak6 dang1', def: 'white light', topic: 'harbor', difficulty: 'medium' },
  { id: 'h-m-x20-gam1pau4', han: '金牌', jp: 'gam1 paai4', def: 'gold medal', topic: 'harbor', difficulty: 'medium' },
  { id: 'h-m-x21-ngan4pau4', han: '銀牌', jp: 'ngan4 paai4', def: 'silver medal', topic: 'harbor', difficulty: 'medium' },
  { id: 'h-m-x22-leoi4toi4zyu2', han: '擂台主', jp: 'leoi4 toi4 zyu2', def: 'arena master', topic: 'harbor', difficulty: 'medium' },
  { id: 'h-m-x23-hang4sam1', han: '航心', jp: 'hong4 sam1', def: 'voyage spirit', topic: 'harbor', difficulty: 'medium' },
  { id: 'h-m-x24-seoi2sau2go1', han: '水手歌', jp: 'seoi2 sau2 go1', def: 'sailor song', topic: 'harbor', difficulty: 'medium' },
  { id: 'h-m-x25-maa5tau4dang1', han: '碼頭燈', jp: 'maa5 tau4 dang1', def: 'pier light', topic: 'harbor', difficulty: 'medium' },
  { id: 'h-m-x26-lung4zau1deoi2', han: '龍舟隊', jp: 'lung4 zau1 deoi2', def: 'dragon boat team', topic: 'harbor', difficulty: 'medium' },
  { id: 'h-m-x27-faan4syun4sei3', han: '帆船賽', jp: 'faan4 syun4 coi3', def: 'sailing race', topic: 'harbor', difficulty: 'medium' },
  { id: 'h-m-x28-hoi2fung1', han: '海風', jp: 'hoi2 fung1', def: 'sea breeze', topic: 'harbor', difficulty: 'medium' },
  { id: 'h-m-x29-ho4fung1', han: '河風', jp: 'ho4 fung1', def: 'river wind', topic: 'harbor', difficulty: 'medium' },
  { id: 'h-m-x30-ngon6seoi2', han: '岸水', jp: 'ngon6 seoi2', def: 'shore water', topic: 'harbor', difficulty: 'medium' },
  { id: 'h-m-x31-sam1seoi2', han: '深水', jp: 'sam1 seoi2', def: 'deep water', topic: 'harbor', difficulty: 'medium' },
  {
    id: 'h-h-x0',
    han: '船長叫大家準備起錨。',
    jp: 'syun4 zoeng2 giu3 daai6 gaa1 zeon2 bei6 hei2 naau4',
    def: 'The captain told everyone to prepare to weigh anchor.',
    topic: 'harbor',
    difficulty: 'hard',
  },
  {
    id: 'h-h-x1',
    han: '今晚夜航要點齊燈。',
    jp: 'gam1 maan5 je6 hong4 jiu3 dim2 cai4 dang1',
    def: 'Tonight’s night voyage needs all lights on.',
    topic: 'harbor',
    difficulty: 'hard',
  },
  {
    id: 'h-h-x2',
    han: '潮水漲起，小心泊船。',
    jp: 'ciu4 seoi2 zoeng3 hei2, siu2 sam1 bok1 syun4',
    def: 'The tide is rising — moor carefully.',
    topic: 'harbor',
    difficulty: 'hard',
  },
  {
    id: 'h-h-x3',
    han: '水手喺船頭睇風向。',
    jp: 'seoi2 sau2 hai2 syun4 tau4 tai2 fung1 hoeng3',
    def: 'The sailor checks the wind at the bow.',
    topic: 'harbor',
    difficulty: 'hard',
  },
  {
    id: 'h-h-x4',
    han: '龍舟隊齊聲劃槳。',
    jp: 'lung4 zau1 deoi2 cai4 seng1 waak6 zoeng2',
    def: 'The dragon boat team paddles in unison.',
    topic: 'harbor',
    difficulty: 'hard',
  },
  {
    id: 'h-h-x5',
    han: '燈塔光芒掃過海面。',
    jp: 'dang1 taap3 gwong1 mong4 sou3 gwo3 hoi2 min6',
    def: 'The lighthouse beam sweeps the sea.',
    topic: 'harbor',
    difficulty: 'hard',
  },
  {
    id: 'h-h-x6',
    han: '我哋沿住灣角慢駛。',
    jp: 'ngo5 dei6 jyun4 zyu6 waan1 gok3 maan6 sai2',
    def: 'We steam slowly along the bay corner.',
    topic: 'harbor',
    difficulty: 'hard',
  },
  {
    id: 'h-h-x7',
    han: '港口入面泊滿帆船。',
    jp: 'gong2 hau2 jap6 min6 bok1 mun5 faan4 syun4',
    def: 'The harbor mouth is full of moored sailboats.',
    topic: 'harbor',
    difficulty: 'hard',
  },
  {
    id: 'h-h-x8',
    han: '擂台今晚有金幣獎。',
    jp: 'leoi4 toi4 gam1 maan5 jau5 gam1 bai6 zoeng2',
    def: 'The arena has a gold prize tonight.',
    topic: 'harbor',
    difficulty: 'hard',
  },
  {
    id: 'h-h-x9',
    han: '河風涼涼，適合出航。',
    jp: 'ho4 fung1 loeng4 loeng2, sik1 hap6 ceot1 hong4',
    def: 'The cool river wind is perfect for casting off.',
    topic: 'harbor',
    difficulty: 'hard',
  },
  {
    id: 'h-h-x10',
    han: '船尾嗰盞紅燈喺閃。',
    jp: 'syun4 mei5 go2 zaan2 hung4 dang1 hai2 sim2',
    def: 'The red light at the stern is flashing.',
    topic: 'harbor',
    difficulty: 'hard',
  },
  {
    id: 'h-h-x11',
    han: '水手歌響徹整個碼頭。',
    jp: 'seoi2 sau2 go1 hoeng2 cit3 zing2 go3 maa5 tau4',
    def: 'The sailor song echoes across the pier.',
    topic: 'harbor',
    difficulty: 'hard',
  },
  {
    id: 'h-h-x12',
    han: '島嶼遠看好似一點綠。',
    jp: 'dou2 zeoi6 jyun5 hon3 hou2 ci5 jat1 dim2 luk6',
    def: 'From afar the islands look like a speck of green.',
    topic: 'harbor',
    difficulty: 'hard',
  },
  {
    id: 'h-h-x13',
    han: '錨落水之後船先定。',
    jp: 'naau4 lok6 seoi2 zi1 hau6 syun4 sin1 ding6',
    def: 'The boat steadies only after the anchor drops.',
    topic: 'harbor',
    difficulty: 'hard',
  },
  {
    id: 'h-h-x14',
    han: '我哋用槳慢慢靠近岸。',
    jp: 'ngo5 dei6 jung6 zoeng2 maan6 maan2 kaau3 gan6 ngon6',
    def: 'We paddle slowly toward the shore.',
    topic: 'harbor',
    difficulty: 'hard',
  },
  {
    id: 'h-h-x15',
    han: '航海圖標記咗暗礁。',
    jp: 'hong4 hoi2 tou4 biu1 gei3 zo2 am3 ziu1',
    def: 'The chart marks the reefs.',
    topic: 'harbor',
    difficulty: 'hard',
  },
  {
    id: 'h-h-x16',
    han: '綠燈亮起就可以入港。',
    jp: 'luk6 dang1 loeng6 hei2 zau6 ho2 ji5 jap6 gong2',
    def: 'When the green light is on, you may enter port.',
    topic: 'harbor',
    difficulty: 'hard',
  },
  {
    id: 'h-h-x17',
    han: '船隊一齊向東航行。',
    jp: 'syun4 deoi2 jat1 cai4 hoeng3 dung1 hong4 hang4',
    def: 'The fleet sails east together.',
    topic: 'harbor',
    difficulty: 'hard',
  },
  {
    id: 'h-h-x18',
    han: '碼頭工人搬貨物上落。',
    jp: 'maa5 tau4 gung1 jan4 bun1 fo3 mat6 soeng5 lok6',
    def: 'Dockers load and unload cargo.',
    topic: 'harbor',
    difficulty: 'hard',
  },
  {
    id: 'h-h-x19',
    han: '平安返航最緊要。',
    jp: 'ping4 on1 faan1 hong4 zeoi3 gan2 jiu3',
    def: 'A safe return voyage matters most.',
    topic: 'harbor',
    difficulty: 'hard',
  },
]
