import type { MatchWord } from './matchDefinitionBank'

/**
 * Native arena bank — broadcast / news-desk Cantonese (書面語腔口語化),
 * themed to each Match topic. Prompt is the English gloss; choices are `han`.
 */
export const MATCH_DEFINITION_BANK_NATIVE: MatchWord[] = [
  // ════════ Kids · 教育 / 家庭新聞腔 ════════
  {
    id: 'k-n-01',
    han: '教育局呼籲家長關注子女學業壓力',
    jp: 'gaau3 juk6 guk6 fu1 jyu6 gaa1 zoeng2 gwaan1 zyu3 zi2 neoi5 hok6 jip6 aat3 lik6',
    def: 'Education Bureau urges parents to watch kids’ study stress',
    topic: 'kids',
    difficulty: 'native',
  },
  {
    id: 'k-n-02',
    han: '學校將於下周舉行開放日',
    jp: 'hok6 haau6 zoeng1 jyu1 haa6 zau1 geoi2 hang4 hoi1 fong3 jat6',
    def: 'The school will hold an open day next week',
    topic: 'kids',
    difficulty: 'native',
  },
  {
    id: 'k-n-03',
    han: '當局提醒市民慎防流感傳播',
    jp: 'dong2 guk6 tai4 sing2 si5 man4 san6 fong4 lau4 gam2 cyun4 bo3',
    def: 'Authorities remind the public to guard against flu spread',
    topic: 'kids',
    difficulty: 'native',
  },
  {
    id: 'k-n-04',
    han: '兒童圖書節吸引大批親子參加',
    jp: 'ji4 tung4 tou4 syu1 zit3 kap1 jan5 daai6 pai1 can1 zi2 caam1 gaa1',
    def: 'Children’s book festival draws many parent–child visitors',
    topic: 'kids',
    difficulty: 'native',
  },
  {
    id: 'k-n-05',
    han: '學童需佩戴口罩乘搭校車',
    jp: 'hok6 tung4 seoi1 pui3 daai3 hau2 ziu3 sing4 daap3 haau6 ce1',
    def: 'Pupils must wear masks when riding the school bus',
    topic: 'kids',
    difficulty: 'native',
  },
  {
    id: 'k-n-06',
    han: '家長教師會促請增撥課後支援',
    jp: 'gaa1 zoeng2 gaau3 si1 wui2 cuk1 cing2 zang1 but3 fo3 hau6 zi1 wun4',
    def: 'PTA urges more after-school support funding',
    topic: 'kids',
    difficulty: 'native',
  },
  {
    id: 'k-n-07',
    han: '幼稚園招生申請明日起接受',
    jp: 'jau3 zi2 jyun2 ziu1 sang1 san1 cing2 ming4 jat6 hei2 zip3 sau6',
    def: 'Kindergarten enrollment applications open from tomorrow',
    topic: 'kids',
    difficulty: 'native',
  },
  {
    id: 'k-n-08',
    han: '青少年暑期活動報名反應踴躍',
    jp: 'cing1 siu3 nin4 syu2 kei4 wut6 dung6 bou3 ming4 faan2 jing3 jung2 joek6',
    def: 'Youth summer-activity sign-ups are enthusiastic',
    topic: 'kids',
    difficulty: 'native',
  },
  {
    id: 'k-n-09',
    han: '專家建議兒童每日保持適量運動',
    jp: 'zyun1 gaa1 gin3 ji5 ji4 tung4 mui5 jat6 bou2 ci4 sik1 loeng6 wan6 dung6',
    def: 'Experts advise children to keep daily moderate exercise',
    topic: 'kids',
    difficulty: 'native',
  },
  {
    id: 'k-n-10',
    han: '圖書館延長週末開放時間',
    jp: 'tou4 syu1 gun2 jin4 coeng4 zau1 mut6 hoi1 fong3 si4 gaan3',
    def: 'The library extends weekend opening hours',
    topic: 'kids',
    difficulty: 'native',
  },
  {
    id: 'k-n-11',
    han: '校方公布新學年校服安排',
    jp: 'haau6 fong1 gung1 bou3 san1 hok6 nin4 haau6 fuk6 on1 paai4',
    def: 'School announces new-year uniform arrangements',
    topic: 'kids',
    difficulty: 'native',
  },
  {
    id: 'k-n-12',
    han: '義工為弱勢學童提供功課輔導',
    jp: 'ji6 gung1 wai6 joek6 sai3 hok6 tung4 tai4 gung1 gung1 fo3 fu6 dou6',
    def: 'Volunteers tutor disadvantaged pupils with homework',
    topic: 'kids',
    difficulty: 'native',
  },

  // ════════ Animals · 漁護 / 生態新聞腔 ════════
  {
    id: 'a-n-01',
    han: '漁護署接報發現受傷野豬',
    jp: 'jyu4 wu6 cyu5 zip3 bou3 faat3 jin6 sau6 soeng1 je5 zyu1',
    def: 'AFCD receives report of an injured wild boar',
    topic: 'animals',
    difficulty: 'native',
  },
  {
    id: 'a-n-02',
    han: '海洋公園公布大熊貓最新近況',
    jp: 'hoi2 joeng4 gung1 jyun2 gung1 bou3 daai6 hung4 maau1 zeoi3 san1 gan6 fong3',
    def: 'Ocean Park releases the latest giant-panda update',
    topic: 'animals',
    difficulty: 'native',
  },
  {
    id: 'a-n-03',
    han: '保育團體關注瀕危雀鳥棲息地',
    jp: 'bou2 juk6 tyun4 tai2 gwaan1 zyu3 ban1 ngai4 zoek3 niu5 cai1 sik1 dei6',
    def: 'Conservation groups watch endangered bird habitats',
    topic: 'animals',
    difficulty: 'native',
  },
  {
    id: 'a-n-04',
    han: '流浪貓絕育計劃擴展至新界',
    jp: 'lau4 long6 maau1 zyut6 juk6 gai3 waak6 kong3 zin2 zi3 san1 gaai3',
    def: 'Stray-cat neutering scheme expands to the New Territories',
    topic: 'animals',
    difficulty: 'native',
  },
  {
    id: 'a-n-05',
    han: '海豚觀賞活動須遵守海上守則',
    jp: 'hoi2 tyun4 gun1 soeng2 wut6 dung6 seoi1 zeon2 sau6 hoi2 soeng6 sau2 zak1',
    def: 'Dolphin-watching activities must follow sea codes',
    topic: 'animals',
    difficulty: 'native',
  },
  {
    id: 'a-n-06',
    han: '農場加強禽流感防疫措施',
    jp: 'nung4 coeng4 gaa1 koeng4 kam4 lau4 gam2 fong4 jik6 cou3 si1',
    def: 'Farms tighten avian-flu prevention measures',
    topic: 'animals',
    difficulty: 'native',
  },
  {
    id: 'a-n-07',
    han: '動物園重新開放熊貓展館',
    jp: 'dung6 mat6 jyun2 cung4 san1 hoi1 fong3 hung4 maau1 zin2 gun2',
    def: 'Zoo reopens the panda exhibition hall',
    topic: 'animals',
    difficulty: 'native',
  },
  {
    id: 'a-n-08',
    han: '市民勿餵飼野生猴子',
    jp: 'si5 man4 mat6 wai3 zi6 je5 sang1 hau4 zi2',
    def: 'Public must not feed wild monkeys',
    topic: 'animals',
    difficulty: 'native',
  },
  {
    id: 'a-n-09',
    han: '漁民反映近海漁獲量有所回升',
    jp: 'jyu4 man4 faan2 jing3 gan6 hoi2 jyu4 wok6 loeng6 jau5 so2 wui4 sing1',
    def: 'Fishers report a rebound in nearshore catch',
    topic: 'animals',
    difficulty: 'native',
  },
  {
    id: 'a-n-10',
    han: '候鳥遷徙季節開始來臨',
    jp: 'hau6 niu5 cin1 sai2 gwai3 zit3 hoi1 ci2 loi4 lam4',
    def: 'Migratory bird season is beginning',
    topic: 'animals',
    difficulty: 'native',
  },
  {
    id: 'a-n-11',
    han: '寵物診所籲主人定期帶犬隻接種疫苗',
    jp: 'cung4 mat6 zan2 so2 jyu6 zyu2 jan4 ding6 kei4 daai3 hyun2 zek3 zap1 zung3 jik6 miu4',
    def: 'Pet clinics urge owners to vaccinate dogs on schedule',
    topic: 'animals',
    difficulty: 'native',
  },
  {
    id: 'a-n-12',
    han: '珊瑚礁調查顯示物種多樣性改善',
    jp: 'saan1 wu4 ziu1 diu6 caa4 hin2 si6 mat6 zung2 do1 joeng6 sing3 goi2 sin6',
    def: 'Coral-reef survey shows improved species diversity',
    topic: 'animals',
    difficulty: 'native',
  },

  // ════════ Nature · 天氣 / 郊野新聞腔 ════════
  {
    id: 'n-n-01',
    han: '天文台預料本港明日有驟雨及雷暴',
    jp: 'tin1 man4 toi4 jyu6 liu6 bun2 gong2 ming4 jat6 jau5 zau6 jyu5 kap6 leoi4 bou6',
    def: 'Observatory expects showers and thunderstorms tomorrow',
    topic: 'nature',
    difficulty: 'native',
  },
  {
    id: 'n-n-02',
    han: '郊野公園因山火風險暫時封閉部分山徑',
    jp: 'gaau1 je5 gung1 jyun2 jan1 saan1 fo2 fung1 him2 zaam6 si4 fung1 bai3 bou6 fan6 saan1 ging3',
    def: 'Country park closes some trails over wildfire risk',
    topic: 'nature',
    difficulty: 'native',
  },
  {
    id: 'n-n-03',
    han: '空氣質素健康指數達高水平',
    jp: 'hung1 hei3 zat1 sou3 gin6 hong1 zi2 sou3 daat6 gou1 seoi2 ping4',
    def: 'Air quality health index reaches a high level',
    topic: 'nature',
    difficulty: 'native',
  },
  {
    id: 'n-n-04',
    han: '熱帶氣旋逼近南海北部海域',
    jp: 'jit6 daai3 hei3 zyun4 bik1 gan6 naam4 hoi2 bak1 bou6 hoi2 wik6',
    def: 'A tropical cyclone nears northern South China Sea waters',
    topic: 'nature',
    difficulty: 'native',
  },
  {
    id: 'n-n-05',
    han: '環保署監測沿海水質符合標準',
    jp: 'waan4 bou2 cyu5 gaam1 caak3 jyun4 hoi2 seoi2 zat1 fu4 hap6 biu1 zeon2',
    def: 'EPD monitoring finds coastal water quality within standards',
    topic: 'nature',
    difficulty: 'native',
  },
  {
    id: 'n-n-06',
    han: '市民可於週末前往郊遊遠足',
    jp: 'si5 man4 ho2 jyu1 zau1 mut6 cin4 wong5 gaau1 jau4 jyun5 zuk1',
    def: 'Residents may go hiking in the countryside this weekend',
    topic: 'nature',
    difficulty: 'native',
  },
  {
    id: 'n-n-07',
    han: '樹木辦加強颱風後樹木巡查',
    jp: 'syu6 muk6 baan6 gaa1 koeng4 toi4 fung1 hau6 syu6 muk6 ceon4 caa4',
    def: 'Tree office steps up post-typhoon tree inspections',
    topic: 'nature',
    difficulty: 'native',
  },
  {
    id: 'n-n-08',
    han: '日落景色吸引大批攝影愛好者',
    jp: 'jat6 lok6 ging2 sik1 kap1 jan5 daai6 pai1 sip3 jing2 oi3 hou3 ze2',
    def: 'Sunset scenery draws many photography enthusiasts',
    topic: 'nature',
    difficulty: 'native',
  },
  {
    id: 'n-n-09',
    han: '氣溫顯著下降市民添衣保暖',
    jp: 'hei3 wan1 hin2 zoek6 haa6 gong3 si5 man4 tim1 ji1 bou2 nyun5',
    def: 'Temperatures drop sharply; public add layers for warmth',
    topic: 'nature',
    difficulty: 'native',
  },
  {
    id: 'n-n-10',
    han: '濕地公園觀鳥人數創季節新高',
    jp: 'sap1 dei6 gung1 jyun2 gun1 niu5 jan4 sou3 cong3 gwai3 zit3 san1 gou1',
    def: 'Wetland park birdwatching visits hit a seasonal high',
    topic: 'nature',
    difficulty: 'native',
  },
  {
    id: 'n-n-11',
    han: '當局呼籲勿亂拋棄垃圾於海灘',
    jp: 'dong2 guk6 fu1 jyu6 mat6 lyun6 paau1 hei3 laap6 saap3 jyu1 hoi2 taan1',
    def: 'Authorities urge against littering on beaches',
    topic: 'nature',
    difficulty: 'native',
  },
  {
    id: 'n-n-12',
    han: '月食現象將於深夜出現',
    jp: 'jyut6 sik6 jin6 zoeng6 zoeng1 jyu1 sam1 je6 ceot1 jin6',
    def: 'A lunar eclipse will appear late at night',
    topic: 'nature',
    difficulty: 'native',
  },

  // ════════ Food · 食安 / 飲食新聞腔 ════════
  {
    id: 'f-n-01',
    han: '食環署加強抽查街市新鮮食材',
    jp: 'sik6 waan4 cyu5 gaa1 koeng4 cau1 caa4 gaai1 si5 san1 sin1 sik6 coi4',
    def: 'FEHD steps up spot-checks of wet-market fresh food',
    topic: 'food',
    difficulty: 'native',
  },
  {
    id: 'f-n-02',
    han: '業界倡議推廣本地漁農產品',
    jp: 'jip6 gaai3 cong3 ji5 teoi1 gwong2 bun2 dei6 jyu4 nung4 caan2 ban2',
    def: 'Industry advocates promoting local agri-fishery products',
    topic: 'food',
    difficulty: 'native',
  },
  {
    id: 'f-n-03',
    han: '茶餐廳業界反映成本壓力上升',
    jp: 'caa4 caan1 teng1 jip6 gaai3 faan2 jing3 sing4 bun2 aat3 lik6 soeng5 sing1',
    def: 'Cha chaan teng trade reports rising cost pressure',
    topic: 'food',
    difficulty: 'native',
  },
  {
    id: 'f-n-04',
    han: '當局公布月餅抽驗全部合格',
    jp: 'dong2 guk6 gung1 bou3 jyut6 beng2 cau1 jim6 cyun4 bou6 hap6 gaak3',
    def: 'Authorities say all mooncake samples passed testing',
    topic: 'food',
    difficulty: 'native',
  },
  {
    id: 'f-n-05',
    han: '市民選購海鮮時應注意保鮮',
    jp: 'si5 man4 syun2 kau3 hoi2 sin1 si4 jing1 zyu3 ji3 bou2 sin1',
    def: 'Public should mind freshness when buying seafood',
    topic: 'food',
    difficulty: 'native',
  },
  {
    id: 'f-n-06',
    han: '美食節匯聚各地特色小吃',
    jp: 'mei5 sik6 zit3 wui6 zeoi6 gok3 dei6 dak6 sik1 siu2 sik6',
    def: 'Food festival gathers specialty snacks from many places',
    topic: 'food',
    difficulty: 'native',
  },
  {
    id: 'f-n-07',
    han: '奶類製品價格輕微上調',
    jp: 'naai5 leoi6 zai3 ban2 gaa3 gaak3 hing1 mei4 soeng5 tiu4',
    def: 'Dairy product prices rise slightly',
    topic: 'food',
    difficulty: 'native',
  },
  {
    id: 'f-n-08',
    han: '食肆須展示食物敏感原成份',
    jp: 'sik6 si3 seoi1 zin2 si6 sik6 mat6 man5 gam2 jyun4 sing4 fan6',
    def: 'Eateries must display food allergen ingredients',
    topic: 'food',
    difficulty: 'native',
  },
  {
    id: 'f-n-09',
    han: '飲茶傳統獲列入非物質文化遺產',
    jp: 'jam2 caa4 cyun4 tung2 wok6 lit6 jap6 fei1 mat6 zat1 man4 faa3 wai4 caan2',
    def: 'Yum cha tradition listed as intangible cultural heritage',
    topic: 'food',
    difficulty: 'native',
  },
  {
    id: 'f-n-10',
    han: '蔬菜批發價格因天氣波動',
    jp: 'coi3 sok3 paai1 faat3 gaa3 gaak3 jan1 tin1 hei3 bo1 dung6',
    def: 'Wholesale vegetable prices fluctuate with the weather',
    topic: 'food',
    difficulty: 'native',
  },
  {
    id: 'f-n-11',
    han: '食品安全中心公布進口食品抽驗結果',
    jp: 'sik6 mat6 on1 cyun4 zung1 sam1 gung1 bou3 zeon3 hau2 sik6 ban2 cau1 jim6 git3 gwo2',
    def: 'CFS releases imported-food sampling results',
    topic: 'food',
    difficulty: 'native',
  },
  {
    id: 'f-n-12',
    han: '夜市食檔恢復晚間營業',
    jp: 'je6 si5 sik6 dong3 wui4 fuk6 maan5 gaan1 jing4 jip6',
    def: 'Night-market food stalls resume evening trade',
    topic: 'food',
    difficulty: 'native',
  },

  // ════════ Harbor · 海事 / 港口新聞腔 ════════
  {
    id: 'h-n-01',
    han: '海事處呼籲航行人士留意風浪情況',
    jp: 'hoi2 si6 cyu5 fu1 jyu6 hong4 hang4 jan4 si6 lau4 ji3 fung1 long6 cing4 fong3',
    def: 'Marine Department urges mariners to watch wind and waves',
    topic: 'harbor',
    difficulty: 'native',
  },
  {
    id: 'h-n-02',
    han: '渡輪服務因惡劣天氣暫停運作',
    jp: 'dou6 leon4 fuk6 mou6 jan1 ok3 lit6 tin1 hei3 zaam6 ting4 wan6 zok3',
    def: 'Ferry service suspended due to severe weather',
    topic: 'harbor',
    difficulty: 'native',
  },
  {
    id: 'h-n-03',
    han: '貨櫃碼頭吞吐量錄得按年增長',
    jp: 'fo3 gwai6 maa5 tau4 tau4 tou2 loeng6 luk6 dak1 on3 nin4 zang1 zoeng2',
    def: 'Container terminal throughput records year-on-year growth',
    topic: 'harbor',
    difficulty: 'native',
  },
  {
    id: 'h-n-04',
    han: '維港兩岸燈光匯演將如期舉行',
    jp: 'wai4 gong2 loeng5 ngon6 dang1 gwong1 wui6 jin2 zoeng1 jyu4 kei4 geoi2 hang4',
    def: 'Victoria Harbour light show will proceed as scheduled',
    topic: 'harbor',
    difficulty: 'native',
  },
  {
    id: 'h-n-05',
    han: '漁船須於指定避風塘停泊',
    jp: 'jyu4 syun4 seoi1 jyu1 zi2 ding6 bei6 fung1 tong4 ting4 paak3',
    def: 'Fishing boats must berth at designated typhoon shelters',
    topic: 'harbor',
    difficulty: 'native',
  },
  {
    id: 'h-n-06',
    han: '港口交通繁忙當局加強水上巡邏',
    jp: 'gong2 hau2 gaau1 tung1 faan4 mong4 dong2 guk6 gaa1 koeng4 seoi2 soeng6 ceon4 lo4',
    def: 'Busy harbour traffic prompts stepped-up water patrols',
    topic: 'harbor',
    difficulty: 'native',
  },
  {
    id: 'h-n-07',
    han: '郵輪旅客數字較去年同期回升',
    jp: 'jau4 leon4 leoi5 haak3 sou3 zi6 gaau3 heoi3 nin4 tung4 kei4 wui4 sing1',
    def: 'Cruise passenger figures rebound versus last year',
    topic: 'harbor',
    difficulty: 'native',
  },
  {
    id: 'h-n-08',
    han: '橋樑維修工程將分階段進行',
    jp: 'kiu4 loeng4 wai4 sau1 gung1 cing4 zoeng1 fan1 gaai1 dyun6 zeon3 hang4',
    def: 'Bridge maintenance works will proceed in phases',
    topic: 'harbor',
    difficulty: 'native',
  },
  {
    id: 'h-n-09',
    han: '燈塔導航設備完成年度檢測',
    jp: 'dang1 taap3 dou6 hong4 cit3 bei6 jyun4 sing4 nin4 dou6 gim2 caak3',
    def: 'Lighthouse navigation gear completes annual inspection',
    topic: 'harbor',
    difficulty: 'native',
  },
  {
    id: 'h-n-10',
    han: '市民可乘搭渡海小輪前往離島',
    jp: 'si5 man4 ho2 sing4 daap3 dou6 hoi2 siu2 leon4 cin4 wong5 lei4 dou2',
    def: 'Public may take harbour ferries to the outlying islands',
    topic: 'harbor',
    difficulty: 'native',
  },
  {
    id: 'h-n-11',
    han: '航運界關注燃油成本持續高企',
    jp: 'hong4 wan6 gaai3 gwaan1 zyu3 jin4 jau4 sing4 bun2 ci4 zuk6 gou1 kei5',
    def: 'Shipping sector watches persistently high fuel costs',
    topic: 'harbor',
    difficulty: 'native',
  },
  {
    id: 'h-n-12',
    han: '碼頭工人展開新一輪薪酬談判',
    jp: 'maa5 tau4 gung1 jan4 zin2 hoi1 san1 jat1 leon4 san1 cau4 taam4 pun3',
    def: 'Dock workers open a new round of pay talks',
    topic: 'harbor',
    difficulty: 'native',
  },
]
