/** English glosses for common Hong Kong colloquial characters (offline / demo). */
const CHAR_GLOSS: Record<string, string> = {
  你: 'you',
  我: 'I / me',
  佢: 'he / she / they',
  係: 'to be (yes)',
  唔: 'not',
  喺: 'at / in',
  有: 'have / there is',
  冇: 'do not have / none',
  做: 'do / make',
  緊: 'progressive (-ing)',
  咗: 'perfective (already done)',
  住: 'continuous / live',
  咩: 'what (colloquial)',
  乜: 'what',
  嘢: 'thing',
  呀: 'softening particle',
  㗎: 'assertive particle',
  喇: 'change-of-state particle',
  喎: 'hearsay / soft particle',
  嗎: 'question particle',
  呢: 'this / sentence particle',
  個: 'classifier',
  啲: 'some',
  嘅: 'possessive / relative',
  而: 'and / while',
  家: 'home; in 而家 = now',
  度: 'place / degree',
  邊: 'where / which',
  點: 'how',
  好: 'good / very',
  多: 'many / much',
  謝: 'thanks',
  該: 'in 唔該 = thanks / excuse me',
  早: 'early',
  晨: 'morning',
  哈: 'in 哈囉 = hello',
  囉: 'in 哈囉 = hello',
  嗨: 'hi',
  最: 'most',
  近: 'recent / near',
  幾: 'how many / quite',
  請: 'please',
  問: 'ask',
  賣: 'sell',
  錢: 'money',
  樣: 'kind / appearance',
  地: 'in 地鐵 = MTR',
  鐵: 'in 地鐵 = MTR',
  港: 'harbour / HK',
  站: 'station',
  去: 'go',
  嚟: 'come',
  食: 'eat',
  飲: 'drink',
  睇: 'look / watch',
  聽: 'listen',
  講: 'speak',
  話: 'say',
  知: 'know',
  想: 'want / think',
  會: 'will',
  要: 'want / need',
  得: 'can / get',
  可: 'can',
  以: 'so as to',
  人: 'person',
  大: 'big',
  細: 'small',
  今: 'now / today',
  日: 'day',
  時: 'time',
  候: 'time / wait',
  事: 'matter / affair',
  先: 'first / only then',
  再: 'again',
  都: 'also / all',
  同: 'and / with',
  同埋: 'and also',
  真: 'really',
  係咪: 'is it?',
  哋: 'plural (we / they)',
  '？': 'question mark',
  '！': 'exclamation',
  '。': 'full stop',
  '，': 'comma',
}

export function glossForChar(char: string): string {
  return CHAR_GLOSS[char] || (isHanChar(char) ? 'Cantonese character' : '')
}

/** Known-character sense only (empty when unknown — used for drill gating). */
export function charSense(char: string) {
  return CHAR_GLOSS[char]?.trim() || ''
}

export function isHanChar(ch: string) {
  return /[\u3400-\u9fff\uf900-\ufaff]/.test(ch)
}
