/** Auto-seeded primary-language UI glosses (replaces Jyutping in BiText). */
export type PrimaryUiGlossRow = { tl?: string; es?: string; vi?: string; cmn?: string; wuu?: string; sichuan?: string }

export const PRIMARY_UI_GLOSS: Record<string, PrimaryUiGlossRow> = {
  '* Business live hours are a soft fair-use cap (~40 hrs/mo) so speech costs stay sustainable. Family camera is capped at 800 scans/mo; Business camera is unlimited but counted.': { tl: '* Ang Business live hours ay soft fair-use cap (~40 hrs/buwan) para sustainable ang speech costs. Naka-cap ang Family camera sa 800 scans/buwan; unlimited ang Business camera pero binibilang.', es: '* Las horas en vivo Business son un tope blando de uso justo (~40 h/mes) para sostener costos de voz. Family cámara tope 800/mes; Business cámara ilimitada pero contada.', vi: '* Giờ live Business là trần dùng hợp lý mềm (~40 giờ/tháng) để chi phí giọng bền. Camera Family tối đa 800/tháng; camera Business không giới hạn nhưng vẫn đếm.', wuu: '* 商务版即时时数是合理使用上限（大约每月四十小时），等语音成本可以持续。家庭版相机每月 800 次扫描；商务版相机无限但仍计量。', sichuan: '* 商务版即时时数是合理使用上限（大约每月四十小时），等语音成本可以持续。家庭版相机每月 800 次扫描；商务版相机无限但仍计量。' },
  '1': { tl: '1', es: '1', vi: '1', wuu: '1', sichuan: '1' },
  '1 hour': { tl: '1 oras', es: '1 hora', vi: '1 giờ', wuu: '1 小时', sichuan: '1 小时' },
  '10 pooled': { tl: '10 pooled', es: '10 compartidos', vi: '10 dùng chung', wuu: '10 共用', sichuan: '10 共用' },
  '120 cam scans / month': { tl: '120 cam scans / buwan', es: '120 escaneos cam / mes', vi: '120 lần quét cam / tháng', wuu: '每月 120 次相机扫描', sichuan: '每月 120 次相机扫描' },
  '120 camera scans / month': { tl: '120 camera scans / buwan', es: '120 escaneos de cámara / mes', vi: '120 lần quét camera / tháng', wuu: '每月 120 次相机扫描', sichuan: '每月 120 次相机扫描' },
  '120 scans / mo': { tl: '120 scans / buwan', es: '120 escaneos / mes', vi: '120 lần quét / tháng', wuu: '每月 120 次', sichuan: '每月 120 次' },
  '3 Modes': { tl: '3 Modes', es: '3 modos', vi: '3 chế độ', wuu: '三种模式', sichuan: '三种模式' },
  '3–24 characters · letters, numbers, . _ - · once per hour': { tl: '3–24 characters · letters, numbers, . _ - · once per hour', es: '3–24 caracteres · letras, números, . _ - · una vez por hora', vi: '3–24 ký tự · chữ, số, . _ - · mỗi giờ một lần', wuu: '3–24 字符 · 字母数字 . _ - · 每小时一次', sichuan: '3–24 字符 · 字母数字 . _ - · 每小时一次' },
  '4 pooled': { tl: '4 pooled', es: '4 compartidos', vi: '4 dùng chung', wuu: '4 共用', sichuan: '4 共用' },
  '6 tones →': { tl: '6 tones →', es: '6 tonos →', vi: '6 thanh →', wuu: '六个声调 →', sichuan: '六个声调 →' },
  '8 hours': { tl: '8 oras', es: '8 horas', vi: '8 giờ', wuu: '8 小时', sichuan: '8 小时' },
  '800 cam scans / month': { tl: '800 cam scans / buwan', es: '800 escaneos cam / mes', vi: '800 lần quét cam / tháng', wuu: '每月 800 次相机扫描', sichuan: '每月 800 次相机扫描' },
  '800 camera scans / month': { tl: '800 camera scans / buwan', es: '800 escaneos de cámara / mes', vi: '800 lần quét camera / tháng', wuu: '每月 800 次相机扫描', sichuan: '每月 800 次相机扫描' },
  '800 scans / mo': { tl: '800 scans / buwan', es: '800 escaneos / mes', vi: '800 lần quét / tháng', wuu: '每月 800 次', sichuan: '每月 800 次' },
  'AI vision': { tl: 'AI vision', es: 'Visión IA', vi: 'Thị giác AI', wuu: 'AI 视觉', sichuan: 'AI 视觉' },
  'AI vision OCR fallbacks this month (hard cap — Azure OCR still works when exhausted).': { tl: 'AI vision OCR fallbacks ngayong buwan (hard cap — gumagana pa ang Azure OCR kapag naubos).', es: 'Respaldo OCR de visión IA este mes (tope duro — Azure OCR sigue si se agota).', vi: 'OCR dự phòng AI vision tháng này (trần cứng — Azure OCR vẫn chạy khi hết).', wuu: '本月 AI 视觉 OCR 备用（硬上限——用完后 Azure OCR 仍可用）。', sichuan: '本月 AI 视觉 OCR 备用（硬上限——用完后 Azure OCR 仍可用）。' },
  'AR Camera translation': { tl: 'AR Camera translation', es: 'Traducción con cámara AR', vi: 'Dịch camera AR', wuu: 'AR 相机翻译', sichuan: 'AR 相机翻译' },
  'AR translation': { tl: 'AR na salin', es: 'Traducción AR', vi: 'Dịch AR', wuu: 'AR 翻译', sichuan: 'AR 翻译' },
  'Account': { tl: 'Account', es: 'Cuenta', vi: 'Tài khoản', wuu: '账户', sichuan: '账户' },
  'Account deletion': { tl: 'Pag-delete ng account', es: 'Eliminación de cuenta', vi: 'Xoá tài khoản', wuu: '删除账户', sichuan: '删除账户' },
  'Add JyutTranslate to your Home Screen': { tl: 'Idagdag ang JyutTranslate sa Home Screen', es: 'Añade JyutTranslate a tu pantalla de inicio', vi: 'Thêm JyutTranslate vào Màn hình chính', wuu: '把 JyutTranslate 加到主屏幕', sichuan: '把 JyutTranslate 加到主屏幕' },
  'Add a note (optional)': { tl: 'Magdagdag ng note (opsyonal)', es: 'Añade una nota (opcional)', vi: 'Thêm ghi chú (tuỳ chọn)', wuu: '补充说明（可选）', sichuan: '补充说明（可选）' },
  'Add to Home Screen': { tl: 'Idagdag sa Home Screen', es: 'Añadir a pantalla de inicio', vi: 'Thêm vào Màn hình chính', wuu: '加到主屏幕', sichuan: '加到主屏幕' },
  'All translations, top of image to bottom': { tl: 'Lahat ng salin, mula taas ng image pababa', es: 'Todas las traducciones, de arriba abajo', vi: 'Mọi bản dịch, từ trên ảnh xuống dưới', wuu: '从图像顶到底个全部翻译', sichuan: '从图像顶到底的全部翻译' },
  'Allow send screenshot': { tl: 'Payagan ang pag-send ng screenshot', es: 'Permitir enviar captura', vi: 'Cho phép gửi ảnh chụp màn hình', wuu: '允许发送截图', sichuan: '允许发送截图' },
  'Annual': { tl: 'Taunan', es: 'Anual', vi: 'Hàng năm', wuu: '按年', sichuan: '按年' },
  'Auto': { tl: 'Auto', es: 'Auto', vi: 'Tự động', wuu: '自动', sichuan: '自动' },
  'Auto-speak': { tl: 'Auto-speak', es: 'Auto-voz', vi: 'Tự đọc', wuu: '自动朗读', sichuan: '自动朗读' },
  'Auto-speak (Family)': { tl: 'Auto-speak (Family)', es: 'Auto-voz (Family)', vi: 'Tự đọc (Family)', wuu: '自动朗读（家庭版）', sichuan: '自动朗读（家庭版）' },
  'Auto-speak + unlimited voice': { tl: 'Auto-speak + walang limit na voice', es: 'Auto-voz + voz ilimitada', vi: 'Tự đọc + giọng không giới hạn', wuu: '自动朗读＋无限语音', sichuan: '自动朗读＋无限语音' },
  'Auto-speak after translate': { tl: 'Auto-speak pagkatapos mag-translate', es: 'Auto-voz tras traducir', vi: 'Tự đọc sau khi dịch', wuu: '翻译后自动朗读', sichuan: '翻译后自动朗读' },
  'BUY': { tl: 'BILI', es: 'COMPRAR', vi: 'MUA', wuu: '买', sichuan: '买' },
  'Back': { tl: 'Bumalik', es: 'Atrás', vi: 'Quay lại', wuu: '返回', sichuan: '返回' },
  'Back to JyutTranslate home': { tl: 'Bumalik sa home ng JyutTranslate', es: 'Volver al inicio de JyutTranslate', vi: 'Về trang chủ JyutTranslate', wuu: '回 JyutTranslate 首页', sichuan: '回 JyutTranslate 首页' },
  'Back to the app': { tl: 'Bumalik sa app', es: 'Volver a la app', vi: 'Về app', wuu: '回应用', sichuan: '回应用' },
  'Badge shows': { tl: 'Ipinapakita ng badge', es: 'La insignia muestra', vi: 'Huy hiệu hiện', wuu: '徽章显示', sichuan: '徽章显示' },
  'Billing': { tl: 'Billing', es: 'Facturación', vi: 'Thanh toán', wuu: '账单', sichuan: '账单' },
  'Building a unified entry…': { tl: 'Bumubuo ng unified entry…', es: 'Armando una entrada unificada…', vi: 'Đang dựng mục từ thống nhất…', wuu: '正在整理统一词条…', sichuan: '正在整理统一词条…' },
  'Business': { tl: 'Business', es: 'Business', vi: 'Business', wuu: '商务版', sichuan: '商务版' },
  'By continuing, you agree to our': { tl: 'Sa pagpapatuloy, sumasang-ayon ka sa aming', es: 'Al continuar, aceptas nuestros', vi: 'Tiếp tục nghĩa là bạn đồng ý với', wuu: '继续即表示侬同意我伲个', sichuan: '继续即表示你同意我们的' },
  'Cam': { tl: 'Cam', es: 'Cámara', vi: 'Camera', wuu: '相机', sichuan: '相机' },
  'Camera': { tl: 'Camera', es: 'Cámara', vi: 'Camera', wuu: '相机', sichuan: '相机' },
  'Camera scan credits this month (each AR shutter or upload translate). Session time is logged separately for admin.': { tl: 'Camera scan credits ngayong buwan (bawat AR shutter o upload translate). Hiwalay ang session time para sa admin.', es: 'Créditos de escaneo este mes (cada obturador AR o subida). El tiempo de sesión se registra aparte para admin.', vi: 'Lượt quét camera tháng này (mỗi lần chụp AR hoặc tải lên dịch). Thời gian phiên ghi riêng cho admin.', wuu: '本月相机扫描额度（每次 AR 快门或上传翻译）。使用时长另作管理纪录。', sichuan: '本月相机扫描额度（每次 AR 快门或上传翻译）。使用时长另作管理纪录。' },
  'Camera scan credits used up this month.': { tl: 'Naubos na ang camera scan credits ngayong buwan.', es: 'Se agotaron los créditos de escaneo este mes.', vi: 'Hết lượt quét camera tháng này.', wuu: '本月相机扫描额度用完哉。', sichuan: '本月相机扫描额度用完了。' },
  'Camera translation': { tl: 'Pagsasalin sa camera', es: 'Traducción con cámara', vi: 'Dịch bằng camera', wuu: '相机翻译', sichuan: '相机翻译' },
  'Can I cancel anytime?': { tl: 'Puwede ba akong mag-cancel anytime?', es: '¿Puedo cancelar en cualquier momento?', vi: 'Tôi có thể huỷ bất cứ lúc nào không?', wuu: '随时好取消伐？', sichuan: '随时都可以取消不？' },
  'Can I run it on my own server?': { tl: 'Puwede ko ba itong i-run sa sarili kong server?', es: '¿Puedo ejecutarlo en mi propio servidor?', vi: 'Tôi có thể chạy trên máy chủ riêng không?', wuu: '好垃自家服务器跑伐？', sichuan: '可以在自己服务器上跑不？' },
  'Cancel': { tl: 'Cancel', es: 'Cancelar', vi: 'Huỷ', wuu: '取消', sichuan: '取消' },
  'Cantonese': { tl: 'Cantonese', es: 'Cantonés', vi: 'Tiếng Quảng Đông', wuu: '广东话', sichuan: '广东话' },
  'Cantonese Language Tool': { tl: 'Kagamitan sa Wikang Cantonese', es: 'Herramienta de cantonés', vi: 'Công cụ tiếng Quảng Đông', wuu: '广东话工具', sichuan: '广东话工具' },
  'Cantonese quality': { tl: 'Cantonese quality', es: 'Calidad del cantonés', vi: 'Chất lượng Quảng Đông', wuu: '广东话质量', sichuan: '广东话质量' },
  'Cantonese tones': { tl: 'Mga tono ng Cantonese', es: 'Tonos del cantonés', vi: 'Thanh điệu Quảng Đông', wuu: '广东话声调', sichuan: '广东话声调' },
  'Cantonese translation': { tl: 'Salin sa Cantonese', es: 'Traducción al cantonés', vi: 'Bản dịch Quảng Đông', wuu: '广东话翻译', sichuan: '广东话翻译' },
  'Capture & translate': { tl: 'Kunan at isalin', es: 'Capturar y traducir', vi: 'Chụp và dịch', wuu: '拍摄并翻译', sichuan: '拍摄并翻译' },
  'Character breakdown': { tl: 'Character breakdown', es: 'Desglose de caracteres', vi: 'Phân tích chữ', wuu: '单字拆解', sichuan: '单字拆解' },
  'Character detail': { tl: 'Detalye ng character', es: 'Detalle del carácter', vi: 'Chi tiết chữ', wuu: '单字详情', sichuan: '单字详情' },
  'Characters spoken with tap-to-play or auto-speak. Family/Business are unlimited but still counted.': { tl: 'Mga character na sinasalita gamit ang tap-to-play o auto-speak. Unlimited ang Family/Business pero binibilang pa rin.', es: 'Caracteres hablados con tap-to-play o auto-voz. Family/Business son ilimitados pero se cuentan.', vi: 'Ký tự phát bằng chạm phát hoặc tự đọc. Family/Business không giới hạn nhưng vẫn đếm.', wuu: '点喇叭或自动朗读个字数。家庭／商务无限但仍计量。', sichuan: '点喇叭或自动朗读的字数。家庭／商务无限但仍计量。' },
  'Choose a document': { tl: 'Pumili ng dokumento', es: 'Elige un documento', vi: 'Chọn tài liệu', wuu: '选择文件', sichuan: '选择文件' },
  'Choose a username': { tl: 'Pumili ng username', es: 'Elige un nombre de usuario', vi: 'Chọn tên người dùng', wuu: '设定用户名', sichuan: '设定用户名' },
  'Choose what appears under your plan badge': { tl: 'Piliin kung ano ang lalabas sa ilalim ng plan badge', es: 'Elige qué aparece bajo la insignia de tu plan', vi: 'Chọn nội dung dưới huy hiệu gói', wuu: '选择方案徽章下头显示啥', sichuan: '选择方案徽章下面显示啥子' },
  'Clear': { tl: 'I-clear', es: 'Borrar', vi: 'Xoá', wuu: '清除', sichuan: '清除' },
  'Clear history': { tl: 'I-clear ang history', es: 'Borrar historial', vi: 'Xoá lịch sử', wuu: '清除历史', sichuan: '清除历史' },
  'Clear translations': { tl: 'I-clear ang mga salin', es: 'Borrar traducciones', vi: 'Xóa bản dịch', wuu: '清除翻译', sichuan: '清除翻译' },
  'Click on results to open a detailed character breakdown. Learn how to say every word.': { tl: 'I-click ang results para buksan ang detailed character breakdown. Matutong bigkasin ang bawat salita.', es: 'Haz clic en resultados para el desglose de caracteres. Aprende a decir cada palabra.', vi: 'Nhấp kết quả để mở phân tích chữ. Học cách đọc từng từ.', wuu: '点结果打开单字拆解。学会每个字哪能讲。', sichuan: '点结果打开单字拆解。学会每个字咋个讲。' },
  'Close': { tl: 'Isara', es: 'Cerrar', vi: 'Đóng', wuu: '关闭', sichuan: '关闭' },
  'Close account': { tl: 'Isara ang account', es: 'Cerrar cuenta', vi: 'Đóng tài khoản', wuu: '关闭账户', sichuan: '关闭账户' },
  'Collapse': { tl: 'I-collapse', es: 'Contraer', vi: 'Thu gọn', wuu: '收起', sichuan: '收起' },
  'Colloquial 粵語': { tl: 'Colloquial 粵語', es: '粵語 coloquial', vi: '粵語 khẩu ngữ', wuu: '口语粤语', sichuan: '口语粤语' },
  'Community': { tl: 'Community', es: 'Comunidad', vi: 'Cộng đồng', wuu: '社区', sichuan: '社区' },
  'Compare': { tl: 'Ihambing', es: 'Comparar', vi: 'So sánh', wuu: '比较', sichuan: '比较' },
  'Compare all plans →': { tl: 'Ihambing ang lahat ng plans →', es: 'Compara todos los planes →', vi: 'So sánh mọi gói →', wuu: '比较全部方案 →', sichuan: '比较全部方案 →' },
  'Confirm Add — JyutTranslate appears on your Home Screen with this icon.': { tl: 'I-confirm ang Add — lalabas ang JyutTranslate sa Home Screen gamit ang icon na ito.', es: 'Confirma Añadir — JyutTranslate aparece en tu pantalla de inicio con este icono.', vi: 'Xác nhận Thêm — JyutTranslate hiện trên Màn hình chính với biểu tượng này.', wuu: '确认添加——JyutTranslate 会以搿个图标出现垃主屏幕。', sichuan: '确认添加——JyutTranslate 会以这个图标出现在主屏幕。' },
  'Connecting…': { tl: 'Kumokonekta…', es: 'Conectando…', vi: 'Đang kết nối…', wuu: '连接中…', sichuan: '连接中…' },
  'Contact': { tl: 'Contact', es: 'Contacto', vi: 'Liên hệ', wuu: '联系', sichuan: '联系' },
  'Continue with Apple': { tl: 'Magpatuloy gamit ang Apple', es: 'Continuar con Apple', vi: 'Tiếp tục với Apple', wuu: '用 Apple 继续', sichuan: '用 Apple 继续' },
  'Continue with Google': { tl: 'Magpatuloy gamit ang Google', es: 'Continuar con Google', vi: 'Tiếp tục với Google', wuu: '用 Google 继续', sichuan: '用 Google 继续' },
  'Conversation': { tl: 'Usapan', es: 'Conversación', vi: 'Hội thoại', wuu: '对话', sichuan: '对话' },
  'Copied': { tl: 'Nakopya', es: 'Copiado', vi: 'Đã sao chép', wuu: '已复制', sichuan: '已复制' },
  'Copy': { tl: 'Kopyahin', es: 'Copiar', vi: 'Sao chép', wuu: '复制', sichuan: '复制' },
  'Copy text': { tl: 'Kopyahin ang text', es: 'Copiar texto', vi: 'Sao chép chữ', wuu: '复制文字', sichuan: '复制文字' },
  'Copy translations to clipboard': { tl: 'Kopyahin ang mga salin sa clipboard', es: 'Copiar traducciones al portapapeles', vi: 'Sao chép bản dịch vào clipboard', wuu: '复制翻译到剪贴板', sichuan: '复制翻译到剪贴板' },
  'Could not save photo — try again': { tl: 'Hindi ma-save ang larawan — subukan ulit', es: 'No se pudo guardar la foto — inténtalo de nuevo', vi: 'Không lưu được ảnh — thử lại', wuu: '无法保存相片——请再试', sichuan: '无法保存相片——请再试' },
  'Could not send invite': { tl: 'Hindi maipadala ang invite', es: 'No se pudo enviar la invitación', vi: 'Không gửi được lời mời', wuu: '发不出邀请', sichuan: '发不出邀请' },
  'Create account': { tl: 'Gumawa ng account', es: 'Crear cuenta', vi: 'Tạo tài khoản', wuu: '创建账户', sichuan: '创建账户' },
  'Dark': { tl: 'Dark', es: 'Oscuro', vi: 'Tối', wuu: '深色', sichuan: '深色' },
  'Definition': { tl: 'Kahulugan', es: 'Definición', vi: 'Định nghĩa', wuu: '释义', sichuan: '释义' },
  'Delete account': { tl: 'I-delete ang account', es: 'Eliminar cuenta', vi: 'Xoá tài khoản', wuu: '删除账户', sichuan: '删除账户' },
  'Delete box': { tl: 'Tanggalin ang box', es: 'Eliminar recuadro', vi: 'Xóa khung', wuu: '删除选框', sichuan: '删除选框' },
  'Demo mode: no model key loaded. Add OPENAI_API_KEY (and OPENAI_BASE_URL if needed) to apps/api/.env, then restart npm run dev:api.': { tl: 'Demo mode: walang model key. Idagdag ang OPENAI_API_KEY (at OPENAI_BASE_URL kung kailangan) sa apps/api/.env, tapos i-restart ang npm run dev:api.', es: 'Modo demo: sin clave de modelo. Añade OPENAI_API_KEY (y OPENAI_BASE_URL si hace falta) en apps/api/.env y reinicia npm run dev:api.', vi: 'Chế độ demo: chưa có khoá model. Thêm OPENAI_API_KEY (và OPENAI_BASE_URL nếu cần) vào apps/api/.env, rồi restart npm run dev:api.', wuu: '演示模式：未载入翻译密钥。垃 apps/api/.env 加 OPENAI_API_KEY（搭需要个 OPENAI_BASE_URL），再重启 npm run dev:api。', sichuan: '演示模式：未载入翻译密钥。在 apps/api/.env 加 OPENAI_API_KEY（搭需要个 OPENAI_BASE_URL），再重启 npm run dev:api。' },
  'Details': { tl: 'Detalye', es: 'Detalles', vi: 'Chi tiết', wuu: '详情', sichuan: '详情' },
  'Dictionary': { tl: 'Diksyunaryo', es: 'Diccionario', vi: 'Từ điển', wuu: '词典', sichuan: '词典' },
  'Direction': { tl: 'Direksyon', es: 'Dirección', vi: 'Hướng', wuu: '方向', sichuan: '方向' },
  'Dismiss Home Screen tip': { tl: 'I-dismiss ang Home Screen tip', es: 'Descartar tip de pantalla de inicio', vi: 'Tắt gợi ý Màn hình chính', wuu: '关掉主屏幕提示', sichuan: '关掉主屏幕提示' },
  'Do I need my own API keys?': { tl: 'Kailangan ko ba ng sariling API keys?', es: '¿Necesito mis propias claves API?', vi: 'Tôi có cần khoá API riêng không?', wuu: '要自家 API 密钥伐？', sichuan: '要自己的 API 密钥不？' },
  'Do you have any suggestions?': { tl: 'May suggestions ka ba?', es: '¿Tienes sugerencias?', vi: 'Bạn có góp ý không?', wuu: '侬有啥建议？', sichuan: '你有啥子建议？' },
  'Document page quota exhausted. Upgrade for more pages.': { tl: 'Naubos na ang document page quota. Mag-upgrade para sa more pages.', es: 'Cuota de páginas agotada. Mejora tu plan para más páginas.', vi: 'Hết hạn mức trang tài liệu. Nâng cấp để thêm trang.', wuu: '文件页数用完哉。升级好加页数。', sichuan: '文件页数用完了。升级好加页数。' },
  'Document pages translated in Cam → Documents this month.': { tl: 'Mga document pages na naisalin sa Cam → Documents ngayong buwan.', es: 'Páginas de documentos traducidas en Cámara → Documentos este mes.', vi: 'Số trang tài liệu dịch trong Cam → Tài liệu tháng này.', wuu: '本月垃相机 → 文件翻译个页数。', sichuan: '本月在相机 → 文件翻译个页数。' },
  'Documents': { tl: 'Mga dokumento', es: 'Documentos', vi: 'Tài liệu', wuu: '文件', sichuan: '文件' },
  'Done': { tl: 'Tapos', es: 'Listo', vi: 'Xong', wuu: '好哉', sichuan: '好了' },
  'Double-tap a chart for details': { tl: 'I-double-tap ang chart para sa detalye', es: 'Toca dos veces un gráfico para detalles', vi: 'Chạm đúp biểu đồ để xem chi tiết', wuu: '双击图表看详情', sichuan: '双击图表看详情' },
  'Download the photo with translations': { tl: 'I-download ang larawan na may mga salin', es: 'Descarga la foto con traducciones', vi: 'Tải ảnh kèm bản dịch', wuu: '下载带翻译个相片', sichuan: '下载带翻译个相片' },
  'Download translation': { tl: 'I-download ang salin', es: 'Descargar traducción', vi: 'Tải bản dịch', wuu: '下载译文', sichuan: '下载译文' },
  'Draw and adjust boxes': { tl: 'Mag-draw at i-adjust ang mga box', es: 'Dibuja y ajusta recuadros', vi: 'Vẽ và chỉnh khung', wuu: '手动画框再翻译', sichuan: '手动画框再翻译' },
  'Draw box': { tl: 'Mag-draw ng box', es: 'Dibujar recuadro', vi: 'Vẽ khung', wuu: '画框', sichuan: '画框' },
  'Each Cam shutter or upload translate uses one scan credit (Azure Vision OCR once — not continuous polling). Free includes 120 scans per month. Family includes 800. Business is unlimited but still tracked. Time spent in the Cam UI is logged for admin only and does not spend scan credits.': { tl: 'Bawat Cam shutter o upload translate ay gumagamit ng isang scan credit (isang beses na Azure Vision OCR — hindi continuous polling). May 120 scans/buwan ang Free. May 800 ang Family. Unlimited ang Business pero tracked pa rin. Ang oras sa Cam UI ay para sa admin lang at hindi gumagamit ng scan credits.', es: 'Cada obturador Cam o subida usa un crédito de escaneo (OCR Azure Vision una vez — sin sondeo continuo). Free incluye 120/mes. Family 800. Business es ilimitado pero se rastrea. El tiempo en la UI Cam es solo admin y no gasta créditos.', vi: 'Mỗi lần chụp Cam hoặc tải lên dịch dùng một lượt quét (OCR Azure Vision một lần — không polling liên tục). Free có 120/tháng. Family 800. Business không giới hạn nhưng vẫn theo dõi. Thời gian trong UI Cam chỉ ghi cho admin, không trừ lượt.', wuu: '每次相机快门或上传翻译用一格扫描额度（一次 Azure Vision OCR——勿会持续轮询）。免费版每月 120 次。家庭版 800 次。商务版无限但仍计量。垃相机界面个时间只作管理纪录，勿扣扫描额度。', sichuan: '每次相机快门或上传翻译用一格扫描额度（一次 Azure Vision OCR——不会持续轮询）。免费版每月 120 次。家庭版 800 次。商务版无限但仍计量。在相机界面个时间只作管理纪录，不扣扫描额度。' },
  'Edit username': { tl: 'I-edit ang username', es: 'Editar nombre de usuario', vi: 'Sửa tên người dùng', wuu: '编辑用户名', sichuan: '编辑用户名' },
  'Effective September 1, 2026': { tl: 'Effective September 1, 2026', es: 'Vigente desde el 1 de septiembre de 2026', vi: 'Có hiệu lực từ 1 tháng 9, 2026', wuu: '自 2026 年 9 月 1 日起生效', sichuan: '自 2026 年 9 月 1 日起生效' },
  'Email': { tl: 'Email', es: 'Correo', vi: 'Email', wuu: '邮件', sichuan: '邮件' },
  'English': { tl: 'English', es: 'Inglés', vi: 'Tiếng Anh', wuu: '英文', sichuan: '英语' },
  'English translation': { tl: 'Salin sa English', es: 'Traducción al inglés', vi: 'Bản dịch tiếng Anh', wuu: '英文翻译', sichuan: '英文翻译' },
  'Every plan, side by side': { tl: 'Bawat plan, magkatabi', es: 'Cada plan, lado a lado', vi: 'Mọi gói, cạnh nhau', wuu: '每个方案，并排比较', sichuan: '每个方案，并排比较' },
  'Everyone shares one monthly allowance for live mic, camera, and documents.': { tl: 'Lahat ay may shared monthly allowance para sa live mic, camera, at documents.', es: 'Todos comparten un cupo mensual de mic en vivo, cámara y documentos.', vi: 'Mọi người dùng chung hạn mức tháng cho mic, camera và tài liệu.', wuu: '全家人共用一个月额度——即时咪、相机搭文件一道。', sichuan: '全家人共用一个月额度——即时咪、相机搭文件一道。' },
  'Everything in Family': { tl: 'Lahat sa Family', es: 'Todo lo de Family', vi: 'Mọi thứ trong Family', wuu: '包含家庭版全部', sichuan: '包含家庭版全部' },
  'Everything in Free': { tl: 'Lahat sa Free', es: 'Todo lo de Free', vi: 'Mọi thứ trong Free', wuu: '包含免费版全部', sichuan: '包含免费版全部' },
  'Examples': { tl: 'Mga halimbawa', es: 'Ejemplos', vi: 'Ví dụ', wuu: '例句', sichuan: '例句' },
  'Expand': { tl: 'I-expand', es: 'Expandir', vi: 'Mở rộng', wuu: '展开', sichuan: '展开' },
  'FAQ': { tl: 'FAQ', es: 'FAQ', vi: 'Câu hỏi thường gặp', wuu: '常见问题', sichuan: '常见问题' },
  'Family': { tl: 'Family', es: 'Family', vi: 'Family', wuu: '家庭版', sichuan: '家庭版' },
  'Features': { tl: 'Mga feature', es: 'Funciones', vi: 'Tính năng', wuu: '功能', sichuan: '功能' },
  'For regular conversations': { tl: 'Para sa regular na usapan', es: 'Para conversaciones habituales', vi: 'Cho hội thoại thường ngày', wuu: '日常闲聊用', sichuan: '日常闲聊用' },
  'For teams & heavy live use': { tl: 'Para sa teams at heavy live use', es: 'Para equipos y uso intenso en vivo', vi: 'Cho nhóm & dùng live nhiều', wuu: '团队搭重度即时使用', sichuan: '团队搭重度即时使用' },
  'For trying it out': { tl: 'Para subukan', es: 'Para probarlo', vi: 'Để dùng thử', wuu: '用来试试', sichuan: '用来试试' },
  'Free': { tl: 'Free', es: 'Gratis', vi: 'Miễn phí', wuu: '免费', sichuan: '免费' },
  'Friend faces this side': { tl: 'Dito nakaharap ang kaibigan', es: 'Tu amigo mira este lado', vi: 'Bạn bè hướng phía này', wuu: '朋友对牢搿边', sichuan: '朋友朝这边' },
  'From': { tl: 'Mula', es: 'De', vi: 'Từ', wuu: '原文', sichuan: '原文' },
  'Get started': { tl: 'Magsimula', es: 'Empezar', vi: 'Bắt đầu', wuu: '开始用', sichuan: '开始用' },
  'Go Business': { tl: 'Pumunta sa Business', es: 'Pasar a Business', vi: 'Chọn Business', wuu: '选商务版', sichuan: '选商务版' },
  'Go Family': { tl: 'Pumunta sa Family', es: 'Pasar a Family', vi: 'Chọn Family', wuu: '选家庭版', sichuan: '选家庭版' },
  'Good questions': { tl: 'Magagandang tanong', es: 'Buenas preguntas', vi: 'Câu hỏi hay', wuu: '好问题', sichuan: '好问题' },
  'Got it': { tl: 'Nakuha ko', es: 'Entendido', vi: 'Đã hiểu', wuu: '晓得哉', sichuan: '晓得了' },
  'Guest': { tl: 'Bisita', es: 'Invitado', vi: 'Khách', wuu: '访客', sichuan: '访客' },
  'Guest camera scans used up. Sign in to continue on Free.': { tl: 'Naubos na ang guest camera scans. Mag-sign in para magpatuloy sa Free.', es: 'Se agotaron los escaneos de invitado. Inicia sesión para seguir en Free.', vi: 'Hết lượt quét khách. Đăng nhập để tiếp tục Free.', wuu: '访客相机扫描用完哉。登录后用免费版继续。', sichuan: '访客相机扫描用完了。登录后用免费版继续。' },
  'Guest live time used up. Sign in to continue on Free.': { tl: 'Naubos na ang guest live time. Mag-sign in para magpatuloy sa Free.', es: 'Se acabó el tiempo en vivo de invitado. Inicia sesión para seguir en Free.', vi: 'Hết thời gian live khách. Đăng nhập để tiếp tục Free.', wuu: '访客即时时间用完哉。登录后用免费版继续。', sichuan: '访客即时时间用完了。登录后用免费版继续。' },
  'Headroom for Conversation Mode & long talks': { tl: 'May headroom para sa Conversation Mode at mahahabang usapan', es: 'Margen para Conversación y charlas largas', vi: 'Dư địa cho Hội thoại & nói lâu', wuu: '对话模式搭长对话有足够空间', sichuan: '对话模式搭长对话有足够空间' },
  'Hear tones while you speak': { tl: 'Marinig ang tones habang nagsasalita', es: 'Escucha tonos mientras hablas', vi: 'Nghe thanh khi bạn nói', wuu: '一边讲一边听到声调', sichuan: '一边讲一边听到声调' },
  'Here are our currently supported languages.': { tl: 'Narito ang mga currently supported languages namin.', es: 'Estos son los idiomas que actualmente admitimos.', vi: 'Đây là các ngôn ngữ hiện hỗ trợ.', wuu: '搿些是目前支持个语言。', sichuan: '这些是目前支持的语言。' },
  'History': { tl: 'Kasaysayan', es: 'Historial', vi: 'Lịch sử', wuu: '历史', sichuan: '历史' },
  'Hit capture and watch the translations update!': { tl: 'Pindutin ang capture at panoorin ang update ng mga salin!', es: '¡Captura y mira actualizarse las traducciones!', vi: 'Bấm chụp và xem bản dịch cập nhật!', wuu: '按拍摄，看翻译更新！', sichuan: '按拍摄，看翻译更新！' },
  'Hold or tap the button and speak': { tl: 'Pindutin o i-tap ang button at magsalita', es: 'Mantén o toca el botón y habla', vi: 'Giữ hoặc chạm nút và nói', wuu: '按牢或点按钮讲话', sichuan: '按牢或点按钮讲话' },
  'Hold or tap to speak': { tl: 'Pindutin o i-tap para magsalita', es: 'Mantén o toca para hablar', vi: 'Giữ hoặc chạm để nói', wuu: '按牢或点一下讲话', sichuan: '按牢或点一下讲话' },
  'Hold phone facing you': { tl: 'Harapin sa iyo ang telepono', es: 'Sostén el teléfono mirándote', vi: 'Hướng điện thoại về phía bạn', wuu: '手机对牢自家', sichuan: '手机对着自己' },
  'Hong Kong Cantonese': { tl: 'Hong Kong Cantonese', es: 'Cantonés de Hong Kong', vi: 'Quảng Đông Hồng Kông', wuu: '香港广东话', sichuan: '香港广东话' },
  'Household seats': { tl: 'Mga upuan sa household', es: 'Asientos del hogar', vi: 'Ghế gia đình', wuu: '家庭座位', sichuan: '家庭座位' },
  'Hover for exact time · double-click for details': { tl: 'I-hover para sa exact time · i-double-click para sa detalye', es: 'Pasa el cursor para el tiempo exacto · doble clic para detalles', vi: 'Di chuột xem thời gian chính xác · nhấp đúp xem chi tiết', wuu: '滑过看精确时间 · 双击看详情', sichuan: '滑过看精确时间 · 双击看详情' },
  'How': { tl: 'Paano', es: 'Cómo', vi: 'Cách', wuu: '哪能', sichuan: '咋个' },
  'IPA pronunciation': { tl: 'IPA pronunciation', es: 'Pronunciación IPA', vi: 'Phát âm IPA', wuu: 'IPA 发音', sichuan: 'IPA 发音' },
  'Install JyutTranslate to your Home Screen — Open like any other app!': { tl: 'I-install ang JyutTranslate sa Home Screen — Buksan tulad ng ibang app!', es: 'Instala JyutTranslate en tu pantalla de inicio — ¡ábrelo como cualquier app!', vi: 'Cài JyutTranslate vào Màn hình chính — mở như app khác!', wuu: '把 JyutTranslate 装到主屏幕——像其他应用一样打开！', sichuan: '把 JyutTranslate 装到主屏幕——像其他应用一样打开！' },
  'Install on iPhone': { tl: 'I-install sa iPhone', es: 'Instalar en iPhone', vi: 'Cài trên iPhone', wuu: '装到 iPhone', sichuan: '装到 iPhone' },
  'Invite by email': { tl: 'Mag-invite sa email', es: 'Invitar por correo', vi: 'Mời bằng email', wuu: '用邮件邀请', sichuan: '用邮件邀请' },
  'Invite sent': { tl: 'Naipadala ang invite', es: 'Invitación enviada', vi: 'Đã gửi lời mời', wuu: '邀请已发送', sichuan: '邀请已发送' },
  'JyutTranslate': { tl: 'JyutTranslate', es: 'JyutTranslate', vi: 'JyutTranslate', wuu: 'JyutTranslate', sichuan: 'JyutTranslate' },
  'JyutTranslate draws Jyutping under every Cantonese line.': { tl: 'Naglalagay ang JyutTranslate ng Jyutping sa ilalim ng bawat Cantonese line.', es: 'JyutTranslate pone Jyutping bajo cada línea en cantonés.', vi: 'JyutTranslate hiện Jyutping dưới mỗi dòng Quảng Đông.', wuu: 'JyutTranslate 会垃每句广东话下头画粤拼。', sichuan: 'JyutTranslate 会在每句广东话下面画粤拼。' },
  'JyutTranslate © 2026': { tl: 'JyutTranslate © 2026', es: 'JyutTranslate © 2026', vi: 'JyutTranslate © 2026', wuu: 'JyutTranslate © 2026', sichuan: 'JyutTranslate © 2026' },
  'Jyutping built in': { tl: 'Built-in ang Jyutping', es: 'Jyutping integrado', vi: 'Jyutping tích hợp', wuu: '内置粤拼', sichuan: '内置粤拼' },
  'Jyutping on every line': { tl: 'Jyutping sa bawat line', es: 'Jyutping en cada línea', vi: 'Jyutping trên mọi dòng', wuu: '每行都有粤拼', sichuan: '每行都有粤拼' },
  'Jyutping romanization': { tl: 'Jyutping romanization', es: 'Romanización Jyutping', vi: 'Phiên âm Jyutping', wuu: '粤拼罗马化', sichuan: '粤拼罗马化' },
  'Keep the translated photo, or copy every translation from top to bottom.': { tl: 'I-keep ang translated photo, o kopyahin ang bawat salin mula taas pababa.', es: 'Guarda la foto traducida o copia cada traducción de arriba abajo.', vi: 'Giữ ảnh đã dịch, hoặc sao chép mọi bản dịch từ trên xuống.', wuu: '保存带翻译个相片，或从上到下复制全部翻译。', sichuan: '保存带翻译个相片，或从上到下复制全部翻译。' },
  'Latest': { tl: 'Pinakabago', es: 'Más reciente', vi: 'Mới nhất', wuu: '最新', sichuan: '最新' },
  'Launch app': { tl: 'Buksan ang app', es: 'Abrir la app', vi: 'Mở app', wuu: '打开应用', sichuan: '打开应用' },
  'Launch translator': { tl: 'Buksan ang translator', es: 'Abrir traductor', vi: 'Mở trình dịch', wuu: '打开翻译器', sichuan: '打开翻译器' },
  'Learn Spanish(MX)': { tl: 'Matuto ng Spanish(MX)', es: 'Aprende español (MX)', vi: 'Học Spanish(MX)', wuu: '学西班牙语（MX）', sichuan: '学西班牙语（MX）' },
  'Learn as you speak': { tl: 'Matuto habang nagsasalita', es: 'Aprende mientras hablas', vi: 'Học khi nói', wuu: '边讲边学', sichuan: '边讲边学' },
  'Light': { tl: 'Light', es: 'Claro', vi: 'Sáng', wuu: '浅色', sichuan: '浅色' },
  'Listening — pause or tap to stop': { tl: 'Nakikinig — tumigil o i-tap para huminto', es: 'Escuchando — pausa o toca para parar', vi: 'Đang nghe — tạm dừng hoặc chạm để dừng', wuu: '听牢——停顿或再点停', sichuan: '听牢——停顿或再点停' },
  'Listening — release when done': { tl: 'Nakikinig — bitawan kapag tapos na', es: 'Escuchando — suelta al terminar', vi: 'Đang nghe — thả khi xong', wuu: '听牢——好了就放', sichuan: '听牢——好了就放' },
  'Live API not reachable from here — this runs against your deployed backend.': { tl: 'Hindi ma-reach ang Live API mula rito — tumatakbo ito laban sa deployed backend mo.', es: 'La API en vivo no es alcanzable aquí — corre contra tu backend desplegado.', vi: 'Không tới được Live API từ đây — chạy với backend đã triển khai của bạn.', wuu: '从这里碰勿着 Live API——对牢侬部署个后端跑。', sichuan: '从这里连不上 Live API——对着你部署的后端跑。' },
  'Live AR overlay': { tl: 'Live AR overlay', es: 'Overlay AR en vivo', vi: 'Lớp phủ AR trực tiếp', wuu: '即时 AR 覆盖', sichuan: '即时 AR 覆盖' },
  'Live AR, upload a photo, or translate a document with layout kept.': { tl: 'Live AR, mag-upload ng larawan, o isalin ang dokumento nang naka-preserve ang layout.', es: 'AR en vivo, sube una foto o traduce un documento conservando el formato.', vi: 'AR trực tiếp, tải ảnh, hoặc dịch tài liệu giữ bố cục.', wuu: '即时 AR、上传相片，或翻译文件并尽量保留排版。', sichuan: '即时 AR、上传相片，或翻译文件并尽量保留排版。' },
  'Live Cantonese translation with Jyutping — Use Conversation mode to help you bridge the communication!': { tl: 'Live Cantonese translation with Jyutping — Gamitin ang Conversation mode para tulungan kang magtulay sa komunikasyon!', es: 'Traducción cantonés en vivo con Jyutping — ¡usa Conversación para tender el puente!', vi: 'Dịch Quảng Đông trực tiếp kèm Jyutping — dùng Hội thoại để cầu nối giao tiếp!', wuu: '即时英粤翻译连粤拼——用对话模式帮侬打通沟通！', sichuan: '即时英粤翻译连粤拼——用对话模式帮你打通沟通！' },
  'Live camera · overlay on signs': { tl: 'Live camera · overlay sa mga karatula', es: 'Cámara en vivo · overlay en letreros', vi: 'Camera trực tiếp · phủ lên biển báo', wuu: '即时镜头 · 覆盖路牌文字', sichuan: '即时镜头 · 覆盖路牌文字' },
  'Live mic': { tl: 'Live mic', es: 'Mic en vivo', vi: 'Mic trực tiếp', wuu: '即时麦克风', sichuan: '即时麦克风' },
  'Live translation / month': { tl: 'Live translation / buwan', es: 'Traducción en vivo / mes', vi: 'Dịch trực tiếp / tháng', wuu: '每月即时翻译', sichuan: '每月即时翻译' },
  'Loading other variations…': { tl: 'Naglo-load ng iba pang variations…', es: 'Cargando otras variantes…', vi: 'Đang tải biến thể khác…', wuu: '加载其他说法…', sichuan: '加载其他说法…' },
  'Look for this row in the share sheet': { tl: 'Hanapin ang row na ito sa share sheet', es: 'Busca esta fila en la hoja de compartir', vi: 'Tìm dòng này trong bảng chia sẻ', wuu: '垃分享列表里寻搿一行', sichuan: '在分享列表里找这一行' },
  'Mandarin': { tl: 'Mandarin', es: 'Mandarín', vi: 'Tiếng Phổ Thông', wuu: '普通话', sichuan: '普通话' },
  'Metered': { tl: 'Metered', es: 'Medido', vi: 'Đo lường', wuu: '计量', sichuan: '计量' },
  'Spanish(MX)': { tl: 'Spanish(MX)', es: 'Español (MX)', vi: 'Spanish(MX)', wuu: '西班牙语（MX）', sichuan: '西班牙语（MX）' },
  'Mode': { tl: 'Mode', es: 'Modo', vi: 'Chế độ', wuu: '模式', sichuan: '模式' },
  'Monthly': { tl: 'Buwanan', es: 'Mensual', vi: 'Hàng tháng', wuu: '按月', sichuan: '按月' },
  'Most popular': { tl: 'Pinakasikat', es: 'Más popular', vi: 'Phổ biến nhất', wuu: '最受欢迎', sichuan: '最受欢迎' },
  'Multi-Language Support': { tl: 'Multi-Language Support', es: 'Soporte multiidioma', vi: 'Hỗ trợ đa ngôn ngữ', wuu: '多语言支持', sichuan: '多语言支持' },
  'Multi-Language support coming soon': { tl: 'Malapit na ang Multi-Language support', es: 'Soporte multiidioma próximamente', vi: 'Sắp hỗ trợ đa ngôn ngữ', wuu: '多语言支持即将到来', sichuan: '多语言支持即将到来' },
  'Need an account? Register': { tl: 'Kailangan ng account? Mag-register', es: '¿Necesitas cuenta? Regístrate', vi: 'Cần tài khoản? Đăng ký', wuu: '要账户？注册', sichuan: '要账户？注册' },
  'Next tone story': { tl: 'Next tone story', es: 'Siguiente historia de tono', vi: 'Câu chuyện thanh sau', wuu: '下一个声调故事', sichuan: '下一个声调故事' },
  'No extra details for this turn.': { tl: 'Walang karagdagang detalye para sa turn na ito.', es: 'No hay más detalles para este turno.', vi: 'Không có chi tiết thêm cho lượt này.', wuu: '这趟无额外详情。', sichuan: '这趟无额外详情。' },
  'No text found — try again closer or with better light': { tl: 'Walang nakitang text — subukang mas malapit o mas magandang ilaw', es: 'No se encontró texto — acércate o mejora la luz', vi: 'Không thấy chữ — thử gần hơn hoặc sáng hơn', wuu: '没侦测到文字——靠近点或改善光线再试', sichuan: '没侦测到文字——靠近点或改善光线再试' },
  'No word details available.': { tl: 'Walang available na word details.', es: 'No hay detalles de palabras.', vi: 'Không có chi tiết từng từ.', wuu: '暂无逐词资料。', sichuan: '暂无逐词资料。' },
  'No. Guests can try tap-to-play voice; Free includes a monthly voice-char limit. Family/Business add unlimited voice, auto-speak, and more live mic time. If you self-host, plug in your own Azure/OpenAI keys.': { tl: 'Hindi. Puwedeng subukan ng guests ang tap-to-play voice; may monthly voice-char limit ang Free. May unlimited voice, auto-speak, at mas maraming live mic time ang Family/Business. Kung self-host, gamitin ang sarili mong Azure/OpenAI keys.', es: 'No. Los invitados pueden probar voz al tocar; Free tiene límite mensual de caracteres de voz. Family/Business añaden voz ilimitada, auto-voz y más mic en vivo. Si autoalojas, usa tus claves Azure/OpenAI.', vi: 'Không. Khách có thể thử chạm phát; Free có hạn ký tự giọng/tháng. Family/Business thêm giọng không giới hạn, tự đọc và thêm thời gian mic. Nếu tự host, dùng khoá Azure/OpenAI của bạn.', wuu: '勿使。访客可以试点喇叭播语音；免费版有每月语音字数上限。家庭／商务版有无限语音、自动朗读搭更多即时麦克风时间。如果自家托管，可以改用侬个 Azure／OpenAI 密钥。', sichuan: '不用。访客可以试点喇叭播语音；免费版有每月语音字数上限。家庭／商务版有无限语音、自动朗读和更多即时麦克风时间。如果自己托管，可以用你的 Azure／OpenAI 密钥。' },
  'Not enough pages left for this PDF.': { tl: 'Hindi sapat ang natitirang pages para sa PDF na ito.', es: 'No quedan páginas suficientes para este PDF.', vi: 'Không đủ trang còn lại cho PDF này.', wuu: '剩余页数不够这份 PDF。', sichuan: '剩余页数不够这份 PDF。' },
  'OCR credentials invalid — set AZURE_VISION_KEY and AZURE_VISION_ENDPOINT on the server. Draw boxes manually for now.': { tl: 'Invalid ang OCR credentials — i-set ang AZURE_VISION_KEY at AZURE_VISION_ENDPOINT sa server. Mag-draw muna ng boxes manually.', es: 'Credenciales OCR inválidas — configura AZURE_VISION_KEY y AZURE_VISION_ENDPOINT en el servidor. Dibuje recuadros manualmente por ahora.', vi: 'OCR không hợp lệ — đặt AZURE_VISION_KEY và AZURE_VISION_ENDPOINT trên máy chủ. Tạm vẽ khung thủ công.', wuu: 'OCR 凭证无效——请在服务器设定 AZURE_VISION_KEY 与 AZURE_VISION_ENDPOINT。可先手动画框。', sichuan: 'OCR 凭证无效——请在服务器设定 AZURE_VISION_KEY 与 AZURE_VISION_ENDPOINT。可先手动画框。' },
  'OCR is rate-limited — wait a few seconds, then capture again': { tl: 'Na-rate-limit ang OCR — maghintay ng ilang segundo, tapos kunan ulit', es: 'OCR con límite de ritmo — espera unos segundos y captura de nuevo', vi: 'OCR bị giới hạn tốc độ — đợi vài giây rồi chụp lại', wuu: 'OCR 请求太密——等几秒再拍', sichuan: 'OCR 请求太密——等几秒再拍' },
  'One app, 3 translation methods': { tl: 'Isang app, 3 paraan ng pagsasalin', es: 'Una app, 3 métodos de traducción', vi: 'Một app, 3 cách dịch', wuu: '一个应用，三种翻译方式', sichuan: '一个应用，三种翻译方式' },
  'One phone. Two languages, split screen — perfect for conversations!': { tl: 'Isang telepono. Dalawang wika, split screen — sakto sa usapan!', es: 'Un teléfono. Dos idiomas, pantalla dividida — ideal para conversar.', vi: 'Một điện thoại. Hai ngôn ngữ, chia màn — lý tưởng để trò chuyện!', wuu: '一部手机，双语分屏——顶适合对话！', sichuan: '一部手机，双语分屏——顶适合对话！' },
  'Open JyutTranslate and have your first bilingual conversation in seconds.': { tl: 'Buksan ang JyutTranslate at magkaroon ng unang bilingual conversation sa loob ng ilang segundo.', es: 'Abre JyutTranslate y ten tu primera conversación bilingüe en segundos.', vi: 'Mở JyutTranslate và có cuộc hội thoại song ngữ đầu tiên trong vài giây.', wuu: '打开 JyutTranslate，几秒钟就可以开始双语对话。', sichuan: '打开 JyutTranslate，几秒钟就可以开始双语对话。' },
  'Open a slangy line (órale, ahorita, ¿mande?) for a culture note.': { tl: 'Buksan ang isang slangy line (órale, ahorita, ¿mande?) para sa culture note.', es: 'Abre una frase coloquial (órale, ahorita, ¿mande?) para una nota cultural.', vi: 'Mở một câu lóng (órale, ahorita, ¿mande?) để xem ghi chú văn hoá.', wuu: '点一句口语（órale, ahorita, ¿mande?）看文化说明。', sichuan: '点一句口语（órale, ahorita, ¿mande?）看文化说明。' },
  'Open the app to try it, or head back to the homepage for features.': { tl: 'Buksan ang app para subukan, o bumalik sa homepage para sa features.', es: 'Abre la app para probarla, o vuelve a la home para ver funciones.', vi: 'Mở app để thử, hoặc về trang chủ xem tính năng.', wuu: '打开应用试试，或者回首页看功能。', sichuan: '打开应用试试，或者回首页看功能。' },
  'Open the translator (not the homepage), then tap Share in Safari (box with an arrow up).': { tl: 'Buksan ang translator (hindi ang homepage), tapos i-tap ang Share sa Safari (box na may arrow pataas).', es: 'Abre el traductor (no la home), luego toca Compartir en Safari (caja con flecha arriba).', vi: 'Mở trình dịch (không phải trang chủ), rồi chạm Chia sẻ trong Safari (ô mũi tên lên).', wuu: '先打开翻译器（勿在首页），再垃 Safari 点「分享」（方框向上箭头）。', sichuan: '先打开翻译器（不在首页），再在 Safari 点「分享」（方框向上箭头）。' },
  'Open translator': { tl: 'Buksan ang translator', es: 'Abrir traductor', vi: 'Mở trình dịch', wuu: '打开翻译器', sichuan: '打开翻译器' },
  'Other variations': { tl: 'Iba pang variations', es: 'Otras variantes', vi: 'Biến thể khác', wuu: '其他说法', sichuan: '其他说法' },
  'Owner': { tl: 'Owner', es: 'Propietario', vi: 'Chủ', wuu: '主人', sichuan: '主人' },
  'PDF · Word · Excel · PowerPoint · text': { tl: 'PDF · Word · Excel · PowerPoint · text', es: 'PDF · Word · Excel · PowerPoint · texto', vi: 'PDF · Word · Excel · PowerPoint · văn bản', wuu: 'PDF · Word · Excel · PowerPoint · 文字', sichuan: 'PDF · Word · Excel · PowerPoint · 文字' },
  'PDF, DOCX, PPTX, XLSX, TXT · max 8 MB': { tl: 'PDF, DOCX, PPTX, XLSX, TXT · max 8 MB', es: 'PDF, DOCX, PPTX, XLSX, TXT · máx. 8 MB', vi: 'PDF, DOCX, PPTX, XLSX, TXT · tối đa 8 MB', wuu: 'PDF、DOCX、PPTX、XLSX、TXT · 最大 8 MB', sichuan: 'PDF、DOCX、PPTX、XLSX、TXT · 最大 8 MB' },
  'Pages left this month': { tl: 'Mga page na natitira ngayong buwan', es: 'Páginas restantes este mes', vi: 'Số trang còn lại tháng này', wuu: '本月剩余页数', sichuan: '本月剩余页数' },
  'Past translations will show up here as cards.': { tl: 'Lalabas dito ang mga nakaraang salin bilang cards.', es: 'Las traducciones pasadas aparecerán aquí como tarjetas.', vi: 'Các bản dịch trước sẽ hiện ở đây dạng thẻ.', wuu: '过去个翻译会以卡片显示垃该。', sichuan: '过去的翻译会以卡片显示在该。' },
  'Pending': { tl: 'Pending', es: 'Pendiente', vi: 'Đang chờ', wuu: '待处理', sichuan: '待处理' },
  'Pick what went wrong': { tl: 'Piliin kung ano ang nangyari', es: 'Elige qué falló', vi: 'Chọn vấn đề', wuu: '选啥出问题', sichuan: '选啥出问题' },
  'Pinch or dial to zoom, tap to focus, then capture': { tl: 'Pinch o dial para mag-zoom, i-tap para mag-focus, tapos kunan', es: 'Pellizca o gira para zoom, toca para enfocar y captura', vi: 'Chụm hoặc xoay để zoom, chạm lấy nét, rồi chụp', wuu: '双指或滑杆放大，点牢对焦，再拍摄', sichuan: '双指或滑杆放大，点牢对焦，再拍摄' },
  'Pinch or scroll to zoom · Draw box to add · drag boxes until Translate locks them': { tl: 'Mag-pinch o mag-scroll para mag-zoom · Mag-draw ng box para magdagdag · i-drag ang boxes hanggang i-lock ng Translate', es: 'Pellizca o desplaza para zoom · Dibuja para añadir · arrastra hasta que Traducir los fije', vi: 'Chụm hoặc cuộn để zoom · Vẽ khung để thêm · kéo khung đến khi Dịch khoá', wuu: '双指或滚动缩放 · 画框加选区 · 翻译前可拖动，翻译后锁定', sichuan: '双指或滚动缩放 · 画框加选区 · 翻译前可拖动，翻译后锁定' },
  'Plan': { tl: 'Plan', es: 'Plan', vi: 'Gói', wuu: '方案', sichuan: '方案' },
  'Play translations aloud automatically after each turn.': { tl: 'Awtomatikong basahin ang salin pagkatapos ng bawat turn.', es: 'Reproduce la traducción en voz alta tras cada turno.', vi: 'Tự đọc bản dịch sau mỗi lượt.', wuu: '每次翻译后自动朗读。', sichuan: '每次翻译后自动朗读。' },
  'Play voice': { tl: 'I-play ang boses', es: 'Reproducir voz', vi: 'Phát giọng', wuu: '播放语音', sichuan: '播放语音' },
  'Point at text, then tap the camera to translate': { tl: 'Itutok sa text, tapos i-tap ang camera para isalin', es: 'Apunta al texto y toca la cámara para traducir', vi: 'Hướng vào chữ, rồi chạm camera để dịch', wuu: '对准文字，再点相机翻译', sichuan: '对准文字，再点相机翻译' },
  'Point or upload -- translate signs and documents quickly!': { tl: 'Itutok o mag-upload — mabilis na isalin ang karatula at dokumento!', es: 'Apunta o sube — traduce letreros y documentos rápido.', vi: 'Hướng hoặc tải lên — dịch biển báo và tài liệu nhanh!', wuu: '对准或上传——快速翻译路牌搭文件！', sichuan: '对准或上传——快速翻译路牌搭文件！' },
  'Powered by DeepSeek AI': { tl: 'Powered by DeepSeek AI', es: 'Con tecnología DeepSeek AI', vi: 'Hỗ trợ bởi DeepSeek AI', wuu: '由 DeepSeek AI 驱动', sichuan: '由 DeepSeek AI 驱动' },
  'Preserving layout…': { tl: 'Pinapanatili ang layout…', es: 'Conservando el formato…', vi: 'Đang giữ bố cục…', wuu: '保留排版中…', sichuan: '保留排版中…' },
  'Preview': { tl: 'Preview', es: 'Vista previa', vi: 'Xem trước', wuu: '预览', sichuan: '预览' },
  'Previous tone story': { tl: 'Previous tone story', es: 'Historia de tono anterior', vi: 'Câu chuyện thanh trước', wuu: '上一个声调故事', sichuan: '上一个声调故事' },
  'Pricing': { tl: 'Presyo', es: 'Precios', vi: 'Giá', wuu: '价钱', sichuan: '价钱' },
  'Pricing that scales with your conversations': { tl: 'Presyong tumutugma sa iyong mga usapan', es: 'Precios que crecen con tus conversaciones', vi: 'Giá theo kịp hội thoại của bạn', wuu: '价钱跟着侬个对话增长', sichuan: '价钱跟着你的对话涨' },
  'Primary language': { tl: 'Pangunahing wika', es: 'Idioma principal', vi: 'Ngôn ngữ chính', wuu: '主要语言', sichuan: '主要语言' },
  'Priority': { tl: 'Priority', es: 'Prioritario', vi: 'Ưu tiên', wuu: '优先', sichuan: '优先' },
  'Priority Cantonese quality': { tl: 'Priority Cantonese quality', es: 'Calidad cantonés prioritaria', vi: 'Chất lượng Quảng Đông ưu tiên', wuu: '优先广东话质量', sichuan: '优先广东话质量' },
  'Priority support': { tl: 'Priority support', es: 'Soporte prioritario', vi: 'Hỗ trợ ưu tiên', wuu: '优先支持', sichuan: '优先支持' },
  'Priority, natural Cantonese quality': { tl: 'Priority, natural Cantonese quality', es: 'Calidad cantonés prioritaria y natural', vi: 'Chất lượng Quảng Đông ưu tiên, tự nhiên', wuu: '优先、自然个广东话质量', sichuan: '优先、自然个广东话质量' },
  'Privacy': { tl: 'Privacy', es: 'Privacidad', vi: 'Quyền riêng tư', wuu: '隐私', sichuan: '隐私' },
  'Ready to be understood?': { tl: 'Handa ka nang maunawaan?', es: '¿Listo para que te entiendan?', vi: 'Sẵn sàng để được hiểu?', wuu: '准备好被听懂伐？', sichuan: '准备好被听懂了不？' },
  'Ready to download': { tl: 'Handa nang i-download', es: 'Listo para descargar', vi: 'Sẵn sàng tải', wuu: '好下载哉', sichuan: '好下载了' },
  'Refresher on the 6 tones': { tl: 'Refresher sa 6 tones', es: 'Repaso de los 6 tonos', vi: 'Ôn lại 6 thanh', wuu: '温习六个声调', sichuan: '温习六个声调' },
  'Remove': { tl: 'Alisin', es: 'Quitar', vi: 'Gỡ', wuu: '移除', sichuan: '移除' },
  'Report a bug': { tl: 'Mag-report ng bug', es: 'Reportar un error', vi: 'Báo lỗi', wuu: '报告漏洞', sichuan: '报告漏洞' },
  'Report a problem': { tl: 'Mag-report ng problema', es: 'Reportar un problema', vi: 'Báo cáo sự cố', wuu: '报告问题', sichuan: '报告问题' },
  'Result': { tl: 'Resulta', es: 'Resultado', vi: 'Kết quả', wuu: '结果', sichuan: '结果' },
  'Results': { tl: 'Mga resulta', es: 'Resultados', vi: 'Kết quả', wuu: '结果', sichuan: '结果' },
  'Revoke': { tl: 'I-revoke', es: 'Revocar', vi: 'Thu hồi', wuu: '撤销', sichuan: '撤销' },
  'Role': { tl: 'Role', es: 'Rol', vi: 'Vai trò', wuu: '角色', sichuan: '角色' },
  'Romanization and chao tones under every Cantonese line, so you can learn as you speak.': { tl: 'May romanization at chao tones sa ilalim ng bawat Cantonese line, para matuto habang nagsasalita.', es: 'Romanización y tonos Chao bajo cada línea cantonés, para aprender al hablar.', vi: 'Phiên âm và thanh Chao dưới mỗi dòng Quảng Đông, học khi nói.', wuu: '每句广东话下头有粤拼搭声调，一边讲一边学。', sichuan: '每句广东话下面有粤拼搭声调，一边讲一边学。' },
  'SELL': { tl: 'BENTA', es: 'VENDER', vi: 'BÁN', wuu: '卖', sichuan: '卖' },
  'Same word. Different tone.': { tl: 'Parehong salita. Ibang tono.', es: 'Misma palabra. Distinto tono.', vi: 'Cùng từ. Khác thanh.', wuu: '一样个字。勿同声调。', sichuan: '一样个字。不同声调。' },
  'Sandhi domain': { tl: 'Sandhi domain', es: 'Dominio sandhi', vi: 'Miền sandhi', wuu: '连读变调域', sichuan: '连读变调域' },
  'Save': { tl: 'I-save', es: 'Guardar', vi: 'Lưu', wuu: '保存', sichuan: '保存' },
  'Save or copy': { tl: 'I-save o kopyahin', es: 'Guardar o copiar', vi: 'Lưu hoặc sao chép', wuu: '保存或复制', sichuan: '保存或复制' },
  'Save photo': { tl: 'I-save ang larawan', es: 'Guardar foto', vi: 'Lưu ảnh', wuu: '保存相片', sichuan: '保存相片' },
  'Saving pages…': { tl: 'Sine-save ang mga page…', es: 'Guardando páginas…', vi: 'Đang lưu trang…', wuu: '保存页面中…', sichuan: '保存页面中…' },
  'Say something…': { tl: 'Magsabi ng kahit ano…', es: 'Di algo…', vi: 'Nói gì đó…', wuu: '讲点啥…', sichuan: '讲点啥…' },
  'Scanning…': { tl: 'Sina-scan…', es: 'Escaneando…', vi: 'Đang quét…', wuu: '扫描中…', sichuan: '扫描中…' },
  'Seats': { tl: 'Mga upuan', es: 'Asientos', vi: 'Ghế', wuu: '座位', sichuan: '座位' },
  'Select Add to Home Screen.': { tl: 'Piliin ang Add to Home Screen.', es: 'Selecciona Añadir a pantalla de inicio.', vi: 'Chọn Thêm vào Màn hình chính.', wuu: '选择加到主屏幕。', sichuan: '选择加到主屏幕。' },
  'Send invite': { tl: 'Ipadala ang invite', es: 'Enviar invitación', vi: 'Gửi lời mời', wuu: '发送邀请', sichuan: '发送邀请' },
  'Send report': { tl: 'Ipadala ang report', es: 'Enviar reporte', vi: 'Gửi báo cáo', wuu: '发送报告', sichuan: '发送报告' },
  'Sending…': { tl: 'Ipinapadala…', es: 'Enviando…', vi: 'Đang gửi…', wuu: '发送中…', sichuan: '发送中…' },
  'Senses': { tl: 'Mga kahulugan', es: 'Acepciones', vi: 'Nghĩa', wuu: '义项', sichuan: '义项' },
  'Sets Solo, Conversation (your side), Cam translations, and the label under the logo.': { tl: 'Itinatakda ang Solo, Conversation (sa panig mo), Cam, at label sa ilalim ng logo.', es: 'Define Solo, Conversación (tu lado), Cámara y la etiqueta bajo el logo.', vi: 'Đặt Solo, Hội thoại (phía bạn), Cam và nhãn dưới logo.', wuu: '设定 Solo、对话（侬搿边）、Cam，以及标志下头名字。', sichuan: '设定 Solo、对话（你这边）、Cam，以及标志下面名字。' },
  'Shanghainese': { tl: 'Shanghainese', es: 'Shanghainés', vi: 'Tiếng Thượng Hải', wuu: '上海话', sichuan: '上海话' },
  'Sichuanese': { tl: 'Sichuanese', es: 'Sichuanés', vi: 'Tiếng Tứ Xuyên', wuu: '四川话', sichuan: '四川话' },
  'Sichuanese Language Tool': { tl: 'Kagamitan sa Wikang Sichuanese', es: 'Herramienta de sichuanés', vi: 'Công cụ tiếng Tứ Xuyên', wuu: '四川话工具', sichuan: '四川话语言工具' },
  'Shared this month': { tl: 'Shared ngayong buwan', es: 'Compartido este mes', vi: 'Dùng chung tháng này', wuu: '本月共用', sichuan: '本月共用' },
  'Sign in': { tl: 'Mag-sign in', es: 'Iniciar sesión', vi: 'Đăng nhập', wuu: '登录', sichuan: '登录' },
  'Sign in required for live mic': { tl: 'Kailangan mag-sign in para sa live mic', es: 'Inicia sesión para el mic en vivo', vi: 'Cần đăng nhập để dùng mic trực tiếp', wuu: '即时麦克风要登录', sichuan: '即时麦克风要登录' },
  'Sign in to send a report': { tl: 'Mag-sign in para magpadala ng report', es: 'Inicia sesión para enviar un reporte', vi: 'Đăng nhập để gửi báo cáo', wuu: '登录后发送报告', sichuan: '登录后发送报告' },
  'Sign in to translate documents.': { tl: 'Mag-sign in para isalin ang mga dokumento.', es: 'Inicia sesión para traducir documentos.', vi: 'Đăng nhập để dịch tài liệu.', wuu: '登录后翻译文件。', sichuan: '登录后翻译文件。' },
  'Sign in to use camera translation': { tl: 'Mag-sign in para gamitin ang camera translation', es: 'Inicia sesión para usar la traducción con cámara', vi: 'Đăng nhập để dùng dịch camera', wuu: '登录后用相机翻译', sichuan: '登录后用相机翻译' },
  'Sign out': { tl: 'Mag-sign out', es: 'Cerrar sesión', vi: 'Đăng xuất', wuu: '退出登录', sichuan: '退出登录' },
  'Situations': { tl: 'Mga sitwasyon', es: 'Situaciones', vi: 'Tình huống', wuu: '情境', sichuan: '情境' },
  'Solo': { tl: 'Solo', es: 'Solo', vi: 'Solo', wuu: '独白', sichuan: '单人' },
  'Solo mode': { tl: 'Solo mode', es: 'Modo Solo', vi: 'Chế độ Solo', wuu: '独白模式', sichuan: '独白模式' },
  'Solo · Conversation · Cam': { tl: 'Solo · Usapan · Cam', es: 'Solo · Conversación · Cámara', vi: 'Solo · Hội thoại · Cam', wuu: '独白 · 对话 · 相机', sichuan: '独白 · 对话 · 相机' },
  'Solo, Conversation & Camera': { tl: 'Solo, Conversation & Camera', es: 'Solo, Conversación y Cámara', vi: 'Solo, Hội thoại & Camera', wuu: '独白、对话搭相机', sichuan: '独白、对话搭相机' },
  'Speaking…': { tl: 'Nagsasalita…', es: 'Hablando…', vi: 'Đang nói…', wuu: '讲牢…', sichuan: '讲牢…' },
  'Standard': { tl: 'Standard', es: 'Estándar', vi: 'Tiêu chuẩn', wuu: '标准', sichuan: '标准' },
  'Start free. Upgrade for more live talk-time and cam translations!': { tl: 'Magsimula nang libre. Mag-upgrade para sa mas maraming live talk-time at cam translations!', es: 'Empieza gratis. ¡Mejora el plan para más tiempo en vivo y traducciones con cámara!', vi: 'Bắt đầu miễn phí. Nâng cấp để có thêm thời gian live và dịch camera!', wuu: '免费开始。升级享更多即时通话时间搭相机翻译！', sichuan: '免费开始。升级享更多即时通话时间搭相机翻译！' },
  'Start free. Upgrade for more talk-time.': { tl: 'Magsimula nang libre. Mag-upgrade para sa mas maraming talk-time.', es: 'Empieza gratis. Mejora el plan para más tiempo de habla.', vi: 'Bắt đầu miễn phí. Nâng cấp để nói lâu hơn.', wuu: '免费开始。升级享更多通话时间。', sichuan: '免费开始。升级享更多通话时间。' },
  'Starting…': { tl: 'Nagsisimula…', es: 'Iniciando…', vi: 'Đang bắt đầu…', wuu: '开始中…', sichuan: '开始中…' },
  'Still have questions?': { tl: 'May tanong pa ba?', es: '¿Aún tienes preguntas?', vi: 'Vẫn còn câu hỏi?', wuu: '还有问题伐？', sichuan: '还有问题不？' },
  'Stop voice': { tl: 'Ihinto ang boses', es: 'Detener voz', vi: 'Dừng giọng', wuu: '停止语音', sichuan: '停止语音' },
  'Support': { tl: 'Support', es: 'Soporte', vi: 'Hỗ trợ', wuu: '支持', sichuan: '支持' },
  'Supported': { tl: 'Supported', es: 'Admitido', vi: 'Được hỗ trợ', wuu: '已支持', sichuan: '已支持' },
  'Swipe or tap the arrows': { tl: 'Mag-swipe o i-tap ang arrows', es: 'Desliza o toca las flechas', vi: 'Vuốt hoặc chạm mũi tên', wuu: '左右滑或点箭头', sichuan: '左右滑或点箭头' },
  'Tagalog': { tl: 'Tagalog', es: 'Tagalo', vi: 'Tagalog', wuu: '他加禄语', sichuan: '他加禄语' },
  'Tap a box to hear it': { tl: 'I-tap ang box para marinig', es: 'Toca una caja para oírlo', vi: 'Chạm ô để nghe', wuu: '点盒子听声音', sichuan: '点盒子听声音' },
  'Tap any word': { tl: 'I-tap ang kahit anong salita', es: 'Toca cualquier palabra', vi: 'Chạm bất kỳ từ nào', wuu: '点任何一个字', sichuan: '点任何一个字' },
  'Tap for exact time · double-tap for details': { tl: 'I-tap para sa exact time · i-double-tap para sa detalye', es: 'Toca para el tiempo exacto · doble toque para detalles', vi: 'Chạm xem thời gian chính xác · chạm đúp xem chi tiết', wuu: '轻触看精确时间 · 双击看详情', sichuan: '轻触看精确时间 · 双击看详情' },
  'Tap to type in English': { tl: 'I-tap para mag-type sa English', es: 'Toca para escribir en inglés', vi: 'Chạm để gõ tiếng Anh', wuu: '点一下输入英文', sichuan: '点一下输入英文' },
  'Tap translation for character details': { tl: 'I-tap ang salin para sa detalye ng character', es: 'Toca la traducción para ver detalles de caracteres', vi: 'Chạm bản dịch để xem chi tiết chữ', wuu: '点翻译看单字详情', sichuan: '点翻译看单字详情' },
  'Tap-to-play voice': { tl: 'Tap-to-play voice', es: 'Voz al tocar', vi: 'Chạm phát giọng', wuu: '点喇叭播语音', sichuan: '点喇叭播语音' },
  'Tap-to-play voice — free with limitations': { tl: 'Tap-to-play voice — libre pero may limitasyon', es: 'Voz al tocar — gratis con límites', vi: 'Chạm phát giọng — miễn phí có giới hạn', wuu: '点喇叭播语音——免费但有限制', sichuan: '点喇叭播语音——免费但有限制' },
  'Terms': { tl: 'Terms', es: 'Términos', vi: 'Điều khoản', wuu: '条款', sichuan: '条款' },
  'Text translation': { tl: 'Text translation', es: 'Traducción de texto', vi: 'Dịch chữ', wuu: '文字翻译', sichuan: '文字翻译' },
  'Thanks — we got it': { tl: 'Salamat — nakuha na namin', es: 'Gracias — lo recibimos', vi: 'Cảm ơn — đã nhận', wuu: '谢谢——收到哉', sichuan: '谢谢——收到了' },
  'The importance of using the right tone': { tl: 'Kahalagahan ng tamang tono', es: 'La importancia del tono correcto', vi: 'Tầm quan trọng của đúng thanh', wuu: '用对声调有多重要', sichuan: '用对声调有多重要' },
  'These meters reset each calendar month. Unlimited meters still track use so you can see activity.': { tl: 'Nagre-reset ang meters tuwing calendar month. Binibilang pa rin ang unlimited meters para makita ang activity.', es: 'Estos medidores se reinician cada mes. Los ilimitados siguen midiendo para que veas la actividad.', vi: 'Các đồng hồ reset mỗi tháng dương lịch. Gói không giới hạn vẫn đếm để bạn xem hoạt động.', wuu: '这些计量每月重置。无限额度仍会计量，方便侬看活动。', sichuan: '这些计量每月重置。无限额度仍会计量，方便你看活动。' },
  'This month': { tl: 'Ngayong buwan', es: 'Este mes', vi: 'Tháng này', wuu: '本月', sichuan: '本月' },
  'Time the live mic is actively listening in Solo or Conversation.': { tl: 'Oras na actively nakikinig ang live mic sa Solo o Conversation.', es: 'Tiempo que el mic en vivo escucha en Solo o Conversación.', vi: 'Thời gian mic trực tiếp đang nghe trong Solo hoặc Hội thoại.', wuu: '独白或对话里，即时麦克风正在听个时间。', sichuan: '独白或对话里，即时麦克风正在听个时间。' },
  'Time the microphone is actively listening in Solo or Conversation Mode. Text never uses live minutes. Camera uses its own monthly scan credits (session time is logged separately).': { tl: 'Oras na actively nakikinig ang microphone sa Solo o Conversation Mode. Hindi gumagamit ng live minutes ang text. May sariling monthly scan credits ang Camera (hiwalay ang session time).', es: 'Tiempo que el micrófono escucha en Solo o Conversación. El texto nunca usa minutos en vivo. La cámara usa sus créditos mensuales (el tiempo de sesión se registra aparte).', vi: 'Thời gian micro đang nghe trong Solo hoặc Hội thoại. Chữ không dùng phút live. Camera dùng hạn quét tháng riêng (thời gian phiên ghi riêng).', wuu: '独白或对话模式里，麦克风正在听个时间。文字翻译勿用即时分钟。相机用自家每月扫描额度（使用时长另作纪录）。', sichuan: '独白或对话模式里，麦克风正在听个时间。文字翻译不用即时分钟。相机用自己每月扫描额度（使用时长另作纪录）。' },
  'To': { tl: 'Papunta', es: 'A', vi: 'Sang', wuu: '译文', sichuan: '译文' },
  'To Cantonese': { tl: 'Sa Cantonese', es: 'Al cantonés', vi: 'Sang tiếng Quảng Đông', wuu: '译成广东话', sichuan: '译成广东话' },
  'To English': { tl: 'Sa English', es: 'Al inglés', vi: 'Sang tiếng Anh', wuu: '译成英文', sichuan: '译成英文' },
  'To Mandarin': { tl: 'Sa Mandarin', es: 'Al mandarín', vi: 'Sang tiếng Phổ Thông', wuu: '译成普通话', sichuan: '译成普通话' },
  'To Spanish(MX)': { tl: 'Sa Spanish(MX)', es: 'Al español (MX)', vi: 'Sang Spanish(MX)', wuu: '译成西班牙语（MX）', sichuan: '译成西班牙语（MX）' },
  'To Shanghainese': { tl: 'Sa Shanghainese', es: 'Al shanghainés', vi: 'Sang tiếng Thượng Hải', wuu: '译成上海话', sichuan: '译成上海话' },
  'To Sichuanese': { tl: 'Sa Sichuanese', es: 'Al sichuanés', vi: 'Sang tiếng Tứ Xuyên', wuu: '译成四川话', sichuan: '译成四川话' },
  'To Tagalog': { tl: 'Sa Tagalog', es: 'Al tagalo', vi: 'Sang tiếng Tagalog', wuu: '译成他加禄语', sichuan: '译成他加禄语' },
  'To Vietnamese': { tl: 'Sa Vietnamese', es: 'Al vietnamita', vi: 'Sang tiếng Việt', wuu: '译成越南话', sichuan: '译成越南话' },
  'To 中文': { tl: 'Sa 中文', es: 'Al chino', vi: 'Sang tiếng Trung', wuu: '译成中文', sichuan: '译成中文' },
  'Tone 5 climbs — soft rise on 買': { tl: 'Tone 5 umaakyat — soft rise sa 買', es: 'El tono 5 sube — ascenso suave en 買', vi: 'Thanh 5 lên — tăng nhẹ trên 買', wuu: '声调 5 往上——買轻轻升', sichuan: '声调 5 往上——買轻轻升' },
  'Tone 6 stays low — flat 賣': { tl: 'Tone 6 nananatiling mababa — flat 賣', es: 'El tono 6 se queda bajo — 賣 plano', vi: 'Thanh 6 giữ thấp — 賣 bằng', wuu: '声调 6 保持低——賣平', sichuan: '声调 6 保持低——賣平' },
  'Tones': { tl: 'Mga tono', es: 'Tonos', vi: 'Thanh điệu', wuu: '声调', sichuan: '声调' },
  'Translate': { tl: 'Isalin', es: 'Traducir', vi: 'Dịch', wuu: '翻译', sichuan: '翻译' },
  'Translate all': { tl: 'Isalin lahat', es: 'Traducir todo', vi: 'Dịch tất cả', wuu: '全部翻译', sichuan: '全部翻译' },
  'Translating': { tl: 'Isinasalin', es: 'Traduciendo', vi: 'Đang dịch', wuu: '翻译中', sichuan: '翻译中' },
  'Translating document…': { tl: 'Isinasalin ang dokumento…', es: 'Traduciendo documento…', vi: 'Đang dịch tài liệu…', wuu: '翻译文件中…', sichuan: '翻译文件中…' },
  'Translation detail': { tl: 'Detalye ng salin', es: 'Detalle de traducción', vi: 'Chi tiết bản dịch', wuu: '翻译详情', sichuan: '翻译详情' },
  'Translations copied': { tl: 'Nakopya ang mga salin', es: 'Traducciones copiadas', vi: 'Đã sao chép bản dịch', wuu: '已复制翻译', sichuan: '已复制翻译' },
  'Translations start after 2 second pause — or press Enter': { tl: 'Magsisimula ang salin pagkatapos ng 2 segunding pause — o pindutin ang Enter', es: 'La traducción inicia tras 2 s de pausa — o pulsa Enter', vi: 'Bản dịch bắt đầu sau 2 giây dừng — hoặc nhấn Enter', wuu: '停 2 秒后开始翻译——或按 Enter', sichuan: '停 2 秒后开始翻译——或按 Enter' },
  'Try Solo mode, live': { tl: 'Subukan ang Solo mode, live', es: 'Prueba Solo en vivo', vi: 'Thử Solo trực tiếp', wuu: '试用独白模式，即时见', sichuan: '试用独白模式，即时见' },
  'Try it now': { tl: 'Subukan ngayon', es: 'Pruébalo ahora', vi: 'Thử ngay', wuu: '现在就试', sichuan: '现在就试' },
  'Try the demo ↓': { tl: 'Subukan ang demo ↓', es: 'Prueba la demo ↓', vi: 'Thử demo ↓', wuu: '试试演示 ↓', sichuan: '试试演示 ↓' },
  'Tuned for colloquial 粵語 (係, 唔, 喺, 咗) — not Mandarin or formal written Chinese.': { tl: 'Naka-tune para sa colloquial 粵語 (係, 唔, 喺, 咗) — hindi Mandarin o formal written Chinese.', es: 'Afinado al 粵語 coloquial (係, 唔, 喺, 咗) — no mandarín ni chino escrito formal.', vi: 'Chỉnh cho 粵語 khẩu ngữ (係, 唔, 喺, 咗) — không phải Phổ Thông hay văn viết trang trọng.', wuu: '针对口语粤语（係, 唔, 喺, 咗）——勿是普通话或书面中文。', sichuan: '针对口语粤语（係, 唔, 喺, 咗）——不是普通话或书面中文。' },
  'Type Cantonese…': { tl: 'Mag-type ng Cantonese…', es: 'Escribe en cantonés…', vi: 'Gõ tiếng Quảng Đông…', wuu: '打广东话…', sichuan: '打广东话…' },
  'Type English': { tl: 'Mag-type ng English', es: 'Escribe en inglés', vi: 'Gõ tiếng Anh', wuu: '打英文', sichuan: '打英文' },
  'Type English…': { tl: 'Mag-type ng English…', es: 'Escribe en inglés…', vi: 'Gõ tiếng Anh…', wuu: '打英文…', sichuan: '打英文…' },
  'Type in English — the Cantonese line updates below. Tap a sample to start.': { tl: 'Mag-type sa English — mag-u-update ang Cantonese line sa ibaba. I-tap ang sample para magsimula.', es: 'Escribe en inglés — la línea cantonés se actualiza abajo. Toca un ejemplo para empezar.', vi: 'Gõ tiếng Anh — dòng Quảng Đông cập nhật bên dưới. Chạm mẫu để bắt đầu.', wuu: '打英文——广东话会垃下头更新。点样本试试。', sichuan: '打英文——广东话会在下面更新。点样本试试。' },
  'Type or speak — English and Cantonese side by side.': { tl: 'Mag-type o magsalita — English at Cantonese magkatabi.', es: 'Escribe o habla — inglés y cantonés lado a lado.', vi: 'Gõ hoặc nói — Anh và Quảng Đông cạnh nhau.', wuu: '打字或讲话——英文搭广东话并排。', sichuan: '打字或讲话——英文搭广东话并排。' },
  'Unlimited': { tl: 'Walang limit', es: 'Ilimitado', vi: 'Không giới hạn', wuu: '无限', sichuan: '无限' },
  'Unlimited (metered)': { tl: 'Walang limit (metered)', es: 'Ilimitado (medido)', vi: 'Không giới hạn (đo)', wuu: '无限（仍计量）', sichuan: '无限（仍计量）' },
  'Unlimited camera translation (metered)': { tl: 'Walang limit na camera translation (metered)', es: 'Traducción con cámara ilimitada (medida)', vi: 'Dịch camera không giới hạn (vẫn đếm)', wuu: '无限相机翻译（仍计量）', sichuan: '无限相机翻译（仍计量）' },
  'Unlimited pages (usage still counted)': { tl: 'Walang limit sa pages (binibilang pa rin)', es: 'Páginas ilimitadas (el uso se cuenta)', vi: 'Không giới hạn trang (vẫn đếm)', wuu: '页数无上限（仍计量）', sichuan: '页数无上限（仍计量）' },
  'Unlimited tap-to-play + auto-speak': { tl: 'Walang limit na tap-to-play + auto-speak', es: 'Tap-to-play + auto-voz ilimitados', vi: 'Chạm phát + tự đọc không giới hạn', wuu: '无限点喇叭播语音＋自动朗读', sichuan: '无限点喇叭播语音＋自动朗读' },
  'Unlimited text': { tl: 'Walang limit sa text', es: 'Texto ilimitado', vi: 'Chữ không giới hạn', wuu: '无限文字', sichuan: '无限文字' },
  'Unlimited text translation': { tl: 'Walang limit sa text translation', es: 'Traducción de texto ilimitada', vi: 'Dịch chữ không giới hạn', wuu: '无限文字翻译', sichuan: '无限文字翻译' },
  'Up to 10 shared users': { tl: 'Hanggang 10 shared users', es: 'Hasta 10 usuarios compartidos', vi: 'Tối đa 10 người dùng chung', wuu: '最多 10 个共用用户', sichuan: '最多 10 个共用用户' },
  'Up to 4 shared users': { tl: 'Hanggang 4 shared users', es: 'Hasta 4 usuarios compartidos', vi: 'Tối đa 4 người dùng chung', wuu: '最多 4 个共用用户', sichuan: '最多 4 个共用用户' },
  'Upgrade': { tl: 'Mag-upgrade', es: 'Mejorar plan', vi: 'Nâng cấp', wuu: '升级', sichuan: '升级' },
  'Upload image': { tl: 'Mag-upload ng larawan', es: 'Subir imagen', vi: 'Tải ảnh lên', wuu: '上传相片', sichuan: '上传相片' },
  'Usage': { tl: 'Paggamit', es: 'Uso', vi: 'Cách dùng', wuu: '用法', sichuan: '用法' },
  'Usage details': { tl: 'Mga detalye ng usage', es: 'Detalles de uso', vi: 'Chi tiết dùng', wuu: '用量详情', sichuan: '用量详情' },
  'Usage meters. Tap or hover for exact time. Double-tap or press Enter for details. Space toggles exact time.': { tl: 'Usage meters. I-tap o i-hover para sa exact time. I-double-tap o Enter para sa detalye. Space para i-toggle ang exact time.', es: 'Medidores de uso. Toca o pasa el cursor para el tiempo exacto. Doble toque o Enter para detalles. Espacio alterna el tiempo exacto.', vi: 'Đồng hồ dùng. Chạm hoặc di chuột xem thời gian chính xác. Chạm đúp hoặc Enter xem chi tiết. Phím cách bật/tắt thời gian chính xác.', wuu: '用量图表。轻触或滑过看精确时间。双击或按 Enter 看详情。空格切换精确时间。', sichuan: '用量图表。轻触或滑过看精确时间。双击或按 Enter 看详情。空格切换精确时间。' },
  'Username': { tl: 'Username', es: 'Nombre de usuario', vi: 'Tên người dùng', wuu: '用户名', sichuan: '用户名' },
  'Vietnamese': { tl: 'Vietnamese', es: 'Vietnamita', vi: 'Tiếng Việt', wuu: '越南话', sichuan: '越南话' },
  'Voice': { tl: 'Boses', es: 'Voz', vi: 'Giọng', wuu: '语音', sichuan: '语音' },
  'Voice playback': { tl: 'Pag-play ng boses', es: 'Reproducción de voz', vi: 'Phát giọng nói', wuu: '语音播放', sichuan: '语音播放' },
  'Voice settings': { tl: 'Mga setting ng boses', es: 'Ajustes de voz', vi: 'Cài đặt giọng', wuu: '语音设置', sichuan: '语音设置' },
  'What are camera scans?': { tl: 'Ano ang camera scans?', es: '¿Qué son los escaneos de cámara?', vi: 'Quét camera là gì?', wuu: '啥是相机扫描？', sichuan: '啥是相机扫描？' },
  'What counts as a “live minute”?': { tl: 'Ano ang bilang na “live minute”?', es: '¿Qué cuenta como un “minuto en vivo”?', vi: '“Phút live” tính thế nào?', wuu: '啥算“即时分钟”？', sichuan: '啥算“即时分钟”？' },
  'What went wrong? We attach route and settings — not your translations.': { tl: 'Ano ang nangyari? Kasama ang route at settings — hindi ang mga salin mo.', es: '¿Qué falló? Adjuntamos ruta y ajustes — no tus traducciones.', vi: 'Chuyện gì xảy ra? Đính kèm route và cài đặt — không kèm bản dịch của bạn.', wuu: '出啥问题？会附带路由搭设置——勿会带侬个翻译。', sichuan: '出啥子问题？会附带路由和设置——不会带你的翻译。' },
  'Word, Excel, and PowerPoint keep their formatting. PDFs place the translation back on the page — including scans.': { tl: 'Pinapanatili ng Word, Excel, at PowerPoint ang format. Nilalagay ng PDF ang salin pabalik sa page — kasama ang scans.', es: 'Word, Excel y PowerPoint conservan el formato. Los PDF colocan la traducción en la página — también escaneos.', vi: 'Word, Excel và PowerPoint giữ định dạng. PDF đặt bản dịch lại trên trang — kể cả bản scan.', wuu: 'Word、Excel、PowerPoint 会保留排版。PDF 译文放回原位，扫描也行。', sichuan: 'Word、Excel、PowerPoint 会保留排版。PDF 译文放回原位，扫描也行。' },
  'Word breakdown': { tl: 'Paghiwa-hiwalay ng salita', es: 'Desglose de palabras', vi: 'Tách từng từ', wuu: '逐词拆解', sichuan: '逐词拆解' },
  'Wugniu romanization': { tl: 'Wugniu romanization', es: 'Romanización Wugniu', vi: 'Phiên âm Wugniu', wuu: '吴语罗马字', sichuan: '吴语罗马字' },
  'Yes — you can self-host the Vite app + Express API with your own Azure Speech, Azure Vision, and OpenAI/DeepSeek keys.': { tl: 'Oo — puwede mong i-self-host ang Vite app + Express API gamit ang sarili mong Azure Speech, Azure Vision, at OpenAI/DeepSeek keys.', es: 'Sí — puedes autoalojar la app Vite + API Express con tus claves Azure Speech, Azure Vision y OpenAI/DeepSeek.', vi: 'Có — bạn có thể tự host app Vite + API Express với khoá Azure Speech, Azure Vision và OpenAI/DeepSeek của bạn.', wuu: '好——侬可以自家托管 Vite 应用＋Express API，用自家 Azure Speech、Azure Vision 搭 OpenAI/DeepSeek 密钥。', sichuan: '要得——你可以自己托管 Vite 应用＋Express API，用自己的 Azure Speech、Azure Vision 和 OpenAI/DeepSeek 密钥。' },
  'Yes, but refunds are up to my discretion. No refunds guaranteed.': { tl: 'Oo, pero nasa discretion ko ang refunds. Walang guaranteed refunds.', es: 'Sí, pero los reembolsos quedan a mi criterio. No hay reembolsos garantizados.', vi: 'Có, nhưng hoàn tiền do tôi quyết định. Không bảo đảm hoàn tiền.', wuu: '好，但退款由我决定。勿保证退款。', sichuan: '好，但退款由我决定。不保证退款。' },
  'You': { tl: 'Ikaw', es: 'Tú', vi: 'Bạn', wuu: '侬', sichuan: '你' },
  'You walk up to the stall…': { tl: 'Lumapit ka sa stall…', es: 'Te acercas al puesto…', vi: 'Bạn bước tới quầy…', wuu: '侬走到摊头…', sichuan: '你走到摊头…' },
  'Zoom': { tl: 'Zoom', es: 'Zoom', vi: 'Zoom', wuu: '放大', sichuan: '放大' },
  'and': { tl: 'at', es: 'y', vi: 'và', wuu: '搭', sichuan: '搭' },
  'at / in': { tl: 'sa / nasa', es: 'en / dentro', vi: 'ở / trong', wuu: '垃 / 里', sichuan: '在 / 里' },
  'billed annually': { tl: 'billed annually', es: 'facturado anualmente', vi: 'thanh toán theo năm', wuu: '按年计费', sichuan: '按年计费' },
  'buy': { tl: 'bili', es: 'comprar', vi: 'mua', wuu: '买', sichuan: '买' },
  'family@email.com': { tl: 'family@email.com', es: 'familia@email.com', vi: 'family@email.com', wuu: 'family@email.com', sichuan: 'family@email.com' },
  'from $8.99/mo billed yearly': { tl: 'mula $8.99/mo na billed yearly', es: 'desde $8.99/mes facturado al año', vi: 'từ $8.99/tháng thanh toán theo năm', wuu: '从 $8.99/月（年付）', sichuan: '从 $8.99/月（年付）' },
  'help@jyuttranslate.com': { tl: 'help@jyuttranslate.com', es: 'help@jyuttranslate.com', vi: 'help@jyuttranslate.com', wuu: 'help@jyuttranslate.com', sichuan: 'help@jyuttranslate.com' },
  'is / yes': { tl: 'ay / oo', es: 'es / sí', vi: 'là / vâng', wuu: '是 / 对', sichuan: '是 / 对' },
  'modes': { tl: 'modes', es: 'modos', vi: 'chế độ', wuu: '种模式', sichuan: '种模式' },
  'not': { tl: 'hindi', es: 'no', vi: 'không', wuu: '勿', sichuan: '不' },
  'or': { tl: 'o', es: 'o', vi: 'hoặc', wuu: '或者', sichuan: '或者' },
  'past tense marker': { tl: 'past tense marker', es: 'marcador de pasado', vi: 'dấu quá khứ', wuu: '过去时标记', sichuan: '过去时标记' },
  'save ~20%': { tl: 'makatipid ~20%', es: 'ahorra ~20%', vi: 'tiết kiệm ~20%', wuu: '省约 20%', sichuan: '省约 20%' },
  'sell': { tl: 'benta', es: 'vender', vi: 'bán', wuu: '卖', sichuan: '卖' },
  '~1 hour of live translation / month': { tl: '~1 oras ng live translation / buwan', es: '~1 hora de traducción en vivo / mes', vi: '~1 giờ dịch trực tiếp / tháng', wuu: '每月约 1 小时即时翻译', sichuan: '每月约 1 小时即时翻译' },
  '~1 hr live / month': { tl: '~1 oras live / buwan', es: '~1 h en vivo / mes', vi: '~1 giờ live / tháng', wuu: '每月约 1 小时即时', sichuan: '每月约 1 小时即时' },
  '~40 hours of live translation / month (fair use)': { tl: '~40 oras ng live translation / buwan (fair use)', es: '~40 horas de traducción en vivo / mes (uso justo)', vi: '~40 giờ dịch trực tiếp / tháng (sử dụng hợp lý)', wuu: '每月约 40 小时即时翻译（合理使用）', sichuan: '每月约 40 小时即时翻译（合理使用）' },
  '~40 hours*': { tl: '~40 oras*', es: '~40 horas*', vi: '~40 giờ*', wuu: '约 40 小时*', sichuan: '约 40 小时*' },
  '~8 hours live / month': { tl: '~8 oras live / buwan', es: '~8 horas en vivo / mes', vi: '~8 giờ live / tháng', wuu: '每月约 8 小时即时', sichuan: '每月约 8 小时即时' },
  '~8 hours of live translation / month': { tl: '~8 oras ng live translation / buwan', es: '~8 horas de traducción en vivo / mes', vi: '~8 giờ dịch trực tiếp / tháng', wuu: '每月约 8 小时即时翻译', sichuan: '每月约 8 小时即时翻译' },
  '輕按輸入中文': { tl: 'I-tap para mag-type sa Chinese', es: 'Toca para escribir en chino', vi: 'Chạm để gõ tiếng Trung', wuu: '点一下输入中文', sichuan: '点一下输入中文' },
  'This line is informal Spanish(MX).': { tl: 'Ang linya na ito ay informal na Spanish(MX).', es: 'Esta línea es español (MX) informal.', vi: 'Câu này là Spanish(MX) thân mật.', wuu: '搿句是非正式西班牙语（MX）。', sichuan: '这句是非正式西班牙语（MX）。' },
  'Make formal': { tl: 'Gawing pormal', es: 'Hacer formal', vi: 'Chuyển sang trang trọng', wuu: '改成正式', sichuan: '改成正式' },
  'Open details from a full turn to formalize from the source.': { tl: 'Buksan ang details mula sa full turn para ma-formalize mula sa source.', es: 'Abre los detalles de un turno completo para formalizar desde el original.', vi: 'Mở chi tiết từ một lượt đầy đủ để chuyển sang trang trọng từ bản gốc.', wuu: '由完整对话打开详情，先可以用原文改正式。', sichuan: '由完整对话打开详情，先可以用原文改正式。' },
}
