/** Bilingual UI copy: English + 粵語 + Jyutping under the Chinese. */
export type Bi = { en: string; zh: string; jp: string }

export const ui = {
  brandTag: { en: 'English ↔ Cantonese', zh: '英文 ↔ 粵語', jp: 'jing1 man2 ↔ jyut6 jyu5' },
  backHome: { en: 'Back to JyutTranslate home', zh: '返 JyutTranslate 首頁', jp: 'faan1 JyutTranslate sau2 jap6' },

  modeSolo: { en: 'Solo', zh: '獨白', jp: 'duk6 baak6' },
  modeFace: { en: 'Conversation Mode', zh: '對話模式', jp: 'deoi3 waa6 mou4 sik1' },
  modeText: { en: 'Text', zh: '文字', jp: 'man4 zi6' },
  modeTablist: { en: 'Mode', zh: '模式', jp: 'mou4 sik1' },

  holdOrTapToSpeak: {
    en: 'Hold or tap to speak',
    zh: '按住或輕按講',
    jp: 'on3 zyu6 waak6 hing1 on3 gong2',
  },
  liveMicSignIn: {
    en: 'Sign in required for live mic',
    zh: '即時咪高峰需要登入',
    jp: 'zik1 si4 mai1 gou1 fung1 seoi1 jiu3 dang1 jap6',
  },
  releaseWhenDone: {
    en: 'Listening — release when done',
    zh: '聽緊——鬆手就翻譯',
    jp: 'teng1 gan2 — sung1 sau2 zau6 faan1 jik6',
  },
  /** Sticky tap: auto-stops after a sentence pause, or tap again to finish now. */
  tapListening: {
    en: 'Listening — pause or tap to stop',
    zh: '聽緊——停頓或再撳停',
    jp: 'teng1 gan2 — ting4 dyun6 waak6 zoi3 gam2 ting4',
  },
  speaking: { en: 'Speaking…', zh: '講緊…', jp: 'gong2 gan2…' },
  translating: { en: 'Translating', zh: '翻譯緊', jp: 'faan1 jik6 gan2' },

  direction: { en: 'Direction', zh: '方向', jp: 'fong1 hoeng3' },
  dirEnglish: { en: 'English', zh: '英文', jp: 'jing1 man2' },
  dirJyutjyu: { en: 'Cantonese', zh: '粵語', jp: 'jyut6 jyu5' },
  dirMandarin: { en: 'Mandarin', zh: '普通話', jp: 'pou2 tung1 waa2' },
  autoSpeak: { en: 'Auto-speak', zh: '自動朗讀', jp: 'zi6 dung6 long5 duk6' },
  autoSpeakPro: { en: 'Auto-speak (Pro)', zh: '自動朗讀（專業版）', jp: 'zi6 dung6 long5 duk6 (zyun1 jip6 baan2)' },
  speak: { en: 'Play voice', zh: '播放語音', jp: 'bo3 fong3 jyu5 jam1' },
  stopSpeak: { en: 'Stop voice', zh: '停止語音', jp: 'ting4 zi2 jyu5 jam1' },
  speakPro: { en: 'Voice playback', zh: '語音播放', jp: 'jyu5 jam1 bo3 fong3' },
  clear: { en: 'Clear', zh: '清除', jp: 'cing1 ceoi4' },

  historyTitle: { en: 'History', zh: '紀錄', jp: 'gei3 luk6' },
  historyEmpty: {
    en: 'Past translations will show up here as cards.',
    zh: '以前嘅翻譯會喺呢度以卡片顯示。',
    jp: 'ji5 cin4 ge3 faan1 jik6 wui5 hai2 ni1 dou6 ji5 kaa1 pin3 hin2 si6.',
  },
  historyLatest: { en: 'Latest', zh: '最新', jp: 'zeoi3 san1' },
  historyExpand: { en: 'Expand', zh: '展開', jp: 'zin2 hoi1' },
  historyCollapse: { en: 'Collapse', zh: '收起', jp: 'sau1 hei2' },
  historyVariations: { en: 'Other variations', zh: '其他講法', jp: 'kei4 taa1 gong2 faat3' },
  historyBreakdown: {
    en: 'Character breakdown',
    zh: '逐字拆解',
    jp: 'zuk6 zi6 caak3 gaai2',
  },
  loadingVariations: {
    en: 'Loading other variations…',
    zh: '載入其他講法…',
    jp: 'zoi3 jap6 kei4 taa1 gong2 faat3…',
  },
  historyNoDetails: {
    en: 'No extra details for this turn.',
    zh: '呢輪冇額外詳情。',
    jp: 'ni1 leon4 mou5 ngoi6 ngoi6 coeng4 cing4.',
  },

  english: { en: 'English', zh: '英文', jp: 'jing1 man2' },
  cantonese: { en: 'Cantonese', zh: '粵語', jp: 'jyut6 jyu5' },
  speakToTranslate: {
    en: 'Hold or tap the button and speak',
    zh: '按住或輕按掣講嘢',
    jp: 'on3 zyu6 waak6 hing1 on3 zai3 gong2 je5',
  },
  holdFacingYou: { en: 'Hold phone facing you', zh: '手機對住自己', jp: 'sau2 gei1 deoi3 zyu6 zi6 gei2' },
  friendLooksHere: {
    en: 'Friend faces this side',
    zh: '對面朋友望住呢度',
    jp: 'deoi3 min6 pang4 jau5 mong6 zyu6 nei1 dou6',
  },
  yueTranslation: { en: 'Cantonese translation', zh: '粵語翻譯', jp: 'jyut6 jyu5 faan1 jik6' },
  enTranslation: { en: 'English translation', zh: '英文翻譯', jp: 'jing1 man2 faan1 jik6' },

  typeEnglish: { en: 'Type English…', zh: '輸入英文…', jp: 'syu1 jap6 jing1 man2…' },
  typeCantonese: { en: 'Type Cantonese…', zh: '輸入粵語…', jp: 'syu1 jap6 jyut6 jyu5…' },
  translate: { en: 'Translate', zh: '翻譯', jp: 'faan1 jik6' },
  autoTranslateHint: {
    en: 'Pauses 2 seconds after you stop typing — or press Enter',
    zh: '停打兩秒就翻譯——或者撳 Enter',
    jp: 'ting4 daa2 loeng5 miu5 zau6 faan1 jik6 — waak6 ze2 gam2 Enter',
  },
  result: { en: 'Result', zh: '結果', jp: 'git3 gwo2' },
  definition: { en: 'Definition', zh: '釋義', jp: 'sik1 ji6' },
  close: { en: 'Close', zh: '關閉', jp: 'gwaan1 bai3' },
  charDetail: { en: 'Character detail', zh: '單字詳情', jp: 'daan1 zi6 coeng4 cing4' },

  connecting: { en: 'Connecting…', zh: '連接中…', jp: 'lin4 zip3 zung1…' },
  planFree: { en: 'Free', zh: '免費', jp: 'min5 fai3' },
  planPro: { en: 'Pro', zh: '專業版', jp: 'zyun1 jip6 baan2' },
  planGuest: { en: 'Guest', zh: '訪客', jp: 'fong2 haak3' },
  signIn: { en: 'Sign in', zh: '登入', jp: 'dang1 jap6' },
  signInGoogle: { en: 'Continue with Google', zh: '使用 Google 登入', jp: 'jau6 Google dang1 jap6' },
  signInApple: { en: 'Continue with Apple', zh: '使用 Apple 登入', jp: 'jau6 Apple dang1 jap6' },
  signInOr: { en: 'or', zh: '或', jp: 'waak6' },
  register: { en: 'Create account', zh: '註冊', jp: 'zyu3 caak1' },
  createAccount: { en: 'Need an account? Register', zh: '未有帳戶？註冊', jp: 'mei6 jau5 zoeng3 wu6？zyu3 caak1' },
  signOut: { en: 'Sign out', zh: '登出', jp: 'dang1 ceot1' },
  manageBilling: { en: 'Billing', zh: '帳單', jp: 'zoeng3 daan1' },
  upgrade: { en: 'Upgrade', zh: '升級', jp: 'sing1 kap1' },
  accountHub: { en: 'Account', zh: '帳戶', jp: 'zoeng3 wu6' },
  accountClose: { en: 'Close account', zh: '關閉帳戶', jp: 'gwaan1 bai3 zoeng3 wu6' },
  accountPlan: { en: 'Plan', zh: '計劃', jp: 'gai3 waak6' },
  accountUsage: { en: 'This month', zh: '今個月', jp: 'gam1 go3 jyut6' },
  accountLive: { en: 'Live time left', zh: '即時剩餘', jp: 'zik1 si4 ceoi4 jyu4' },
  accountVoice: { en: 'Voice', zh: '語音', jp: 'jyu5 jam1' },
  addToHomeScreen: {
    en: 'Add to Home Screen',
    zh: '加到主畫面',
    jp: 'gaa1 dou3 zyu2 waa2 min6',
  },
  iosHomescreenTipTitle: {
    en: 'Add JyutTranslate to your Home Screen',
    zh: '將 JyutTranslate 加到主畫面',
    jp: 'zoeng1 JyutTranslate gaa1 dou3 zyu2 waa2 min6',
  },
  iosHomescreenTipBody: {
    en: 'Install JyutTranslate to your Home Screen — Open like any other app!',
    zh: '將 JyutTranslate 裝到主畫面——好似其他應用咁開！',
    jp: 'zoeng1 JyutTranslate zong1 dou3 zyu2 waa2 min6 — hou2 ci5 kei4 taa1 jing3 jung6 gam2 hoi1!',
  },
  iosHomescreenShowSteps: {
    en: 'How',
    zh: '點樣',
    jp: 'dim2 joeng2',
  },
  iosHomescreenGotIt: {
    en: 'Got it',
    zh: '知道喇',
    jp: 'zi1 dou3 laa3',
  },
  iosHomescreenDismiss: {
    en: 'Dismiss Home Screen tip',
    zh: '關閉主畫面提示',
    jp: 'gwaan1 bai3 zyu2 waa2 min6 tai4 si6',
  },
  iosHomescreenStep1: {
    en: 'Tap Share in the Safari toolbar (box with an arrow up).',
    zh: '喺 Safari 工具列撳「分享」（方框向上箭嘴）。',
    jp: 'hai2 Safari gung1 geoi6 lit6 gam2 “fan1 hoeng2” (fong1 kwaang1 hoeng3 soeng6 zin3 zeoi2).',
  },
  iosHomescreenStep2: {
    en: 'Select Add to Home Screen.',
    zh: '揀「加到主畫面」。',
    jp: 'gaan2 “gaa1 dou3 zyu2 waa2 min6”.',
  },
  iosHomescreenSheetHint: {
    en: 'Look for this row in the share sheet',
    zh: '喺分享清單搵呢一行',
    jp: 'hai2 fan1 hoeng2 cing1 daan1 wan2 ni1 jat1 hong4',
  },
  iosHomescreenStep3: {
    en: 'Confirm Add — JyutTranslate appears on your Home Screen with this icon.',
    zh: '確認「加入」——JyutTranslate 會用呢個圖示出現喺主畫面。',
    jp: 'kok3 jing6 “gaa1 jap6” — JyutTranslate wui5 jung6 ni1 go3 tou4 si6 ceot1 jin6 hai2 zyu2 waa2 min6.',
  },
  iosHomescreenGuideTitle: {
    en: 'Install on iPhone',
    zh: '裝到 iPhone',
    jp: 'zong1 dou3 iPhone',
  },
  charsLeft: (formatted: string): Bi => ({
    en: `${formatted} chars left`,
    zh: `剩 ${formatted} 字`,
    jp: `sing6 ${formatted} zi6`,
  }),
  charsUsedUnlimited: (formatted: string): Bi => ({
    en: `${formatted} used / unlimited`,
    zh: `已用 ${formatted}／無限`,
    jp: `ji5 jung6 ${formatted} / mou4 haan6`,
  }),
  hoursLeft: (n: number): Bi => ({
    en: `${n}h left`,
    zh: `剩 ${n} 小時`,
    jp: `sing6 ${n} siu2 si4`,
  }),
  minsLeft: (n: number): Bi => ({
    en: `${n}m left`,
    zh: `剩 ${n} 分鐘`,
    jp: `sing6 ${n} fan1 zung1`,
  }),
  secsLeft: (n: number): Bi => ({
    en: `${n}s left`,
    zh: `剩 ${n} 秒`,
    jp: `sing6 ${n} miu5`,
  }),

  lightTheme: { en: 'Light', zh: '淺色', jp: 'cin2 sik1' },
  darkTheme: { en: 'Dark', zh: '深色', jp: 'sam1 sik1' },

  navFeatures: { en: 'Features', zh: '功能', jp: 'gung1 nang4' },
  navPricing: { en: 'Pricing', zh: '價錢', jp: 'gaa3 cin4' },
  navLaunch: { en: 'Launch app', zh: '開啟應用', jp: 'hoi1 kai2 jing3 jung6' },

  heroEyebrow: {
    enLang: 'English',
    zhLang: '英文',
    jpLang: 'jing1 man4',
    enYue: 'Cantonese',
    zhYue: '廣東話',
    jpYue: 'gwong2 dung1 waa2',
    enLive: 'Live translator',
    zhLive: '實時翻譯器',
    jpLive: 'sat6 si4 faan1 jik6 hei3',
  },
  heroTitle: {
    en: 'JyutTranslate',
    zh: '口語粵語／英文翻譯器',
    jp: 'hau2 jyu5 jyut6 jyu5 / jing1 man2 faan1 jik6 hei3',
  },
  heroSub: {
    en: 'Live English/Cantonese translation with Jyutping — Use Conversation mode to help you bridge the communication!',
    zh: '即時英粵翻譯連粵拼——用對話模式幫你打通溝通橋梁！',
    jp: 'zik1 si4 jing1 jyut6 faan1 jik6 lin4 jyut6 ping3 — jung6 deoi3 waa6 mou4 sik1 bong1 nei5 daa2 tung1 kau3 tung1 kiu4 loeng4!',
  },
  launchTranslator: { en: 'Launch translator', zh: '開啟翻譯器', jp: 'hoi1 kai2 faan1 jik6 hei3' },
  tryDemo: { en: 'Try the demo ↓', zh: '試用示範 ↓', jp: 'si3 jung6 si6 faan6 ↓' },
  statDeepseek: {
    en: 'Powered by DeepSeek AI',
    zh: '由 DeepSeek AI 驅動',
    jp: 'jau4 DeepSeek AI keoi1 dung6',
  },
  statModes: { en: 'modes', zh: '種模式', jp: 'zung2 mou4 sik1' },
  statJyutping: { en: 'Jyutping on every line', zh: '每句都有粵拼', jp: 'mui5 geoi3 dou1 jau5 jyut6 ping3' },

  modesKicker: { en: '3 Modes', zh: '三種模式', jp: 'saam1 zung2 mou4 sik1' },
  modesTitle: {
    en: 'One app, 3 translation methods',
    zh: '一個應用，三種翻譯方式',
    jp: 'jat1 go3 jing3 jung6, saam1 zung2 faan1 jik6 fong1 sik1',
  },
  soloDesc: {
    en: 'Speak English or Cantonese and watch the translation appear full-screen, instantly.',
    zh: '講英文或者粵語，翻譯即刻全螢幕出現。',
    jp: 'gong2 jing1 man2 waak6 ze2 jyut6 jyu5, faan1 jik6 zik1 hak1 cyun4 jing4 mok6 ceot1 jin6.',
  },
  faceDesc: {
    en: 'One phone between two people — a split, mirrored view so each side reads their language.',
    zh: '一部手機兩個人用——上下對分，各自睇自己嘅語言。',
    jp: 'jat1 bou6 sau2 gei1 loeng5 go3 jan4 jung6 — soeng6 haa6 deoi3 fan1, gok3 zi6 tai2 zi6 gei2 ge3 jyu5 jin4.',
  },
  textDesc: {
    en: 'Type either direction. Perfect for menus, signs, and messages you want to get right.',
    zh: '雙向打字。睇餐牌、路牌、訊息都啱用。',
    jp: 'soeng1 hoeng3 daa2 zi6. tai2 caan1 paai2, lou6 paai2, seon3 sik1 dou1 aam1 jung6.',
  },

  featJpTitle: { en: 'Jyutping built in', zh: '內建粵拼', jp: 'noi6 gin3 jyut6 ping3' },
  featJpDesc: {
    en: 'Romanization and chao tones under every Cantonese line, so you can learn as you speak.',
    zh: '每句粵語下面都有粵拼同聲調，一邊講一邊學。',
    jp: 'mui5 geoi3 jyut6 jyu5 haa6 min6 dou1 jau5 jyut6 ping3 tung4 sing1 diu6, jat1 bin1 gong2 jat1 bin1 hok6.',
  },
  featJpAside: {
    en: '(And for my ABC’s)',
    zh: '（同埋我啲 ABC）',
    jp: '(tung4 maai4 ngo5 di1 ABC)',
  },
  featHkTitle: { en: 'Hong Kong Cantonese', zh: '香港粵語', jp: 'hoeng1 gong2 jyut6 jyu5' },
  featHkDesc: {
    en: 'Tuned for colloquial 粵語 (係, 唔, 喺, 咗) — not Mandarin or formal written Chinese.',
    zh: '專為口語粵語調校（係、唔、喺、咗）——唔係普通話，亦唔係書面語。',
    jp: 'zyun1 wai6 hau2 jyu5 jyut6 jyu5 tiu4 gaau3 (hai6, m4, hai2, zo2) — m4 hai6 pou2 tung1 waa2, jik6 m4 hai6 syu1 min2 jyu5.',
  },
  featFastTitle: { en: 'Speak, then translate', zh: '講完先翻譯', jp: 'gong2 jyun4 sin1 faan1 jik6' },
  featFastDesc: {
    en: 'Hold or tap the mic, finish your thought, then get one polished line — with Jyutping — when you’re done.',
    zh: '按住或輕按咪高峰，講完先出一句精修翻譯——連粵拼一齊出現。',
    jp: 'on3 zyu6 waak6 hing1 on3 mai1 gou1 fung1, gong2 jyun4 sin1 ceot1 jat1 geoi3 zing1 sau1 faan1 jik6 — lin4 jyut6 ping3 jat1 cai4 ceot1 jin6.',
  },
  featHostTitle: { en: 'Yours to host', zh: '自己托管', jp: 'zi6 gei2 tok3 gun2' },
  featHostDesc: {
    en: 'Built to run on WordPress or fully self-hosted. You will need your own API keys!',
    zh: '可以跑喺 WordPress，又或者完全自己托管。你需要自己嘅 API 密鑰！',
    jp: 'ho2 ji5 paau2 hai2 WordPress, jau6 waak6 ze2 jyun4 cyun4 zi6 gei2 tok3 gun2. nei5 seoi1 jiu3 zi6 gei2 ge3 API mat6 joek6!',
  },

  demoKicker: { en: 'Try it now', zh: '而家試吓', jp: 'ji4 gaa1 si3 haa5' },
  demoTitle: {
    en: 'Translate a phrase, live',
    zh: '翻譯一句，即時見',
    jp: 'faan1 jik6 jat1 geoi3, zik1 si4 gin3',
  },
  demoBody: {
    en: 'Play with our demo! Type anything or tap a sample.',
    zh: '玩吓我哋嘅示範！打任何嘢或者撳樣本。',
    jp: 'waan2 haa5 ngo5 dei6 ge3 si6 faan6! daa2 jam6 ho4 je5 waak6 ze2 gam2 joeng6 bun2.',
  },
  openFullApp: { en: 'Open the full app', zh: '開啟完整應用', jp: 'hoi1 kai2 jyun4 zing2 jing3 jung6' },
  demoTypeEn: { en: 'Type English', zh: '打英文', jp: 'daa2 jing1 man2' },
  demoPlaceholder: { en: 'Say something…', zh: '講啲咩…', jp: 'gong2 di1 me1…' },
  demoLive: { en: 'JyutTranslate · live', zh: 'JyutTranslate · 即時', jp: 'JyutTranslate · zik1 si4' },
  demoCantonese: { en: 'Cantonese', zh: '廣東話', jp: 'gwong2 dung1 waa2' },
  demoApiError: {
    en: 'Live API not reachable from here — this runs against your deployed backend.',
    zh: '即時 API 喺度連唔到——呢個要對住你部署嘅後端先得。',
    jp: 'zik1 si4 API hai2 dou6 lin4 m4 dou3 — ni1 go3 jiu3 deoi3 zyu6 nei5 bou3 syu2 ge3 hau6 dyun1 sin1 dak1.',
  },
  demoModeBanner: {
    en: 'Demo mode: no model key loaded. Add OPENAI_API_KEY (and OPENAI_BASE_URL if needed) to apps/api/.env, then restart npm run dev:api.',
    zh: '示範模式：未載入翻譯密鑰。喺 apps/api/.env 加 OPENAI_API_KEY（同埋需要嘅 OPENAI_BASE_URL），再重啟 npm run dev:api。',
    jp: 'si6 faan6 mou4 sik1: mei6 zoi3 jap6 faan1 jik6 mat6 joek6. hai2 apps/api/.env gaa1 OPENAI_API_KEY (tung4 maai4 seoi1 jiu3 ge3 OPENAI_BASE_URL), zoi3 cung4 hei2 npm run dev:api.',
  },

  pricingKicker: { en: 'Pricing', zh: '價錢', jp: 'gaa3 cin4' },
  pricingTitle: {
    en: 'Start free. Upgrade for more talk-time.',
    zh: '免費開始。升級享更多通話時間。',
    jp: 'min5 fai3 hoi1 ci2. sing1 kap1 hoeng2 gang3 do1 tung1 waa6 si4 gaan3.',
  },
  mostPopular: { en: 'Most popular', zh: '最受歡迎', jp: 'zeoi3 sau6 fun1 jing4' },
  perMonth: { en: '/month', zh: '/月', jp: '/jyut6' },
  getStarted: { en: 'Get started', zh: '立即開始', jp: 'laap6 zik1 hoi1 ci2' },
  goPro: { en: 'Go Pro', zh: '升級專業版', jp: 'sing1 kap1 zyun1 jip6 baan2' },
  comparePlans: { en: 'Compare all plans →', zh: '比較全部計劃 →', jp: 'bei2 gaau3 cyun4 bou6 gai3 waak6 →' },

  freeFeatLive20: {
    en: '~5 minutes of live translation / month',
    zh: '每月大約五分鐘即時翻譯',
    jp: 'mui5 jyut6 daai6 joek3 ng5 fan1 zung1 zik1 si4 faan1 jik6',
  },
  freeFeatText: {
    en: 'Unlimited text translation',
    zh: '無限文字翻譯',
    jp: 'mou4 haan6 man4 zi6 faan1 jik6',
  },
  freeFeatJp: {
    en: 'Jyutping on every line',
    zh: '每句都有粵拼',
    jp: 'mui5 geoi3 dou1 jau5 jyut6 ping3',
  },
  freeFeatModes: {
    en: 'Solo, Conversation Mode & Text',
    zh: '獨白、對話模式同文字',
    jp: 'duk6 baak6, deoi3 waa6 mou4 sik1 tung4 man4 zi6',
  },
  freeFeatTts: {
    en: 'Tap-to-play voice — free with limitations',
    zh: '撳喇叭播語音——免費但有限制',
    jp: 'gam2 laa3 baa1 bo3 jyu5 jam1 — min5 fai3 daan6 jau5 haan6 zai3',
  },
  proFeatLive10: {
    en: '~20 minutes of live translation / month',
    zh: '每月大約廿分鐘即時翻譯',
    jp: 'mui5 jyut6 daai6 joek3 jaa6 fan1 zung1 zik1 si4 faan1 jik6',
  },
  proFeatTts: {
    en: 'Unlimited tap-to-play + auto-speak',
    zh: '無限撳喇叭播語音＋自動朗讀',
    jp: 'mou4 haan6 gam2 laa3 baa1 bo3 jyu5 jam1 + zi6 dung6 long5 duk6',
  },
  proFeatQuality: {
    en: 'Priority, natural Cantonese quality',
    zh: '優先、自然嘅粵語質素',
    jp: 'jau4 sin1, zi6 jin4 ge3 jyut6 jyu5 zat1 sou3',
  },
  proFeatEverything: {
    en: 'Everything in Free',
    zh: '包含免費版全部功能',
    jp: 'bau1 ham4 min5 fai3 baan2 cyun4 bou6 gung1 nang4',
  },

  ctaReady: {
    en: 'Ready to be understood?',
    zh: '準備好俾人聽明未？',
    jp: 'zeon2 bei6 hou2 bei2 jan4 teng1 ming4 mei6?',
  },
  ctaBody: {
    en: 'Open JyutTranslate and have your first bilingual conversation in seconds.',
    zh: '開啟 JyutTranslate，幾秒之內就可以開始雙語對話。',
    jp: 'hoi1 kai2 JyutTranslate, gei2 miu5 zi1 noi6 zau6 ho2 ji5 hoi1 ci2 soeng1 jyu5 deoi3 waa6.',
  },
  footerEnLang: { en: 'English', zh: '英文', jp: 'jing1 man2' },
  footerYueLang: { en: 'Cantonese', zh: '粵語', jp: 'jyut6 jyu5' },

  ppEyebrow: { en: 'Pricing', zh: '價錢', jp: 'gaa3 cin4' },
  ppTitle: {
    en: 'Pricing that scales with your conversations',
    zh: '價錢跟住你嘅對話增長',
    jp: 'gaa3 cin4 gan1 zyu6 nei5 ge3 deoi3 waa6 zang1 zoeng2',
  },
  ppSub: {
    en: 'Start free. Upgrade for more live talk-time and unlimited tap-to-play voice. Guests can try voice without an account.',
    zh: '免費開始。升級享更多即時通話時間同無限撳喇叭播語音。訪客唔使帳戶都可以試語音。',
    jp: 'min5 fai3 hoi1 ci2. sing1 kap1 hoeng2 gang3 do1 zik1 si4 tung1 waa6 si4 gaan3 tung4 mou4 haan6 gam2 laa3 baa1 bo3 jyu5 jam1. fong2 haak3 m4 sai2 zoeng3 wu6 dou1 ho2 ji5 si3 jyu5 jam1.',
  },
  monthly: { en: 'Monthly', zh: '月費', jp: 'jyut6 fai3' },
  annual: { en: 'Annual', zh: '年費', jp: 'nin4 fai3' },
  save20: { en: 'save ~20%', zh: '慳大約兩成', jp: 'haan1 daai6 joek3 loeng5 sing4' },
  billedAnnually: { en: 'billed annually', zh: '按年收費', jp: 'on3 nin4 sau1 fai3' },
  planMax: { en: 'Max', zh: '旗艦版', jp: 'kei4 gaam3 baan2' },
  tagFree: { en: 'For trying it out', zh: '試用啱啱好', jp: 'si3 jung6 aam1 aam1 hou2' },
  tagPro: { en: 'For regular conversations', zh: '日常傾計用', jp: 'jat6 soeng4 king1 gai2 jung6' },
  tagMax: {
    en: 'For long sessions & heavy live use',
    zh: '長時間、高用量即時翻譯',
    jp: 'coeng4 si4 gaan3, gou1 jung6 loeng6 zik1 si4 faan1 jik6',
  },
  goMax: { en: 'Go Max', zh: '升級旗艦版', jp: 'sing1 kap1 kei4 gaam3 baan2' },
  maxPlanUnavailable: {
    en: "We're sorry, the MAX plan is currently not available",
    zh: '抱歉，MAX 計劃暫時未能提供',
    jp: 'm4 goi1, MAX gai3 waak6 zaam6 si6 mut6 nang4 tai4 gung1',
  },
  maxFeatLive40: {
    en: '~40 hours of live translation / month (fair use)',
    zh: '每月大約四十小時即時翻譯（合理使用）',
    jp: 'mui5 jyut6 daai6 joek3 sei3 sap6 siu2 si4 zik1 si4 faan1 jik6 (hap6 lei5 si2 jung6)',
  },
  maxFeatPower: {
    en: 'Headroom for Conversation Mode & long talks',
    zh: '對話模式同長對話有足夠空間',
    jp: 'deoi3 waa6 mou4 sik1 tung4 coeng4 deoi3 waa6 jau5 kau3 gau3 hung1 gaan1',
  },
  maxFeatEverything: {
    en: 'Everything in Pro',
    zh: '包含專業版全部功能',
    jp: 'bau1 ham4 zyun1 jip6 baan2 cyun4 bou6 gung1 nang4',
  },
  maxFeatSupport: {
    en: 'Priority support',
    zh: '優先支援',
    jp: 'jau4 sin1 zi1 wun4',
  },

  compareKicker: { en: 'Compare', zh: '比較', jp: 'bei2 gaau3' },
  compareTitle: {
    en: 'Every plan, side by side',
    zh: '每個計劃，並排睇',
    jp: 'mui5 go3 gai3 waak6, bing6 paai4 tai2',
  },
  cmpLive: { en: 'Live translation / month', zh: '每月即時翻譯', jp: 'mui5 jyut6 zik1 si4 faan1 jik6' },
  cmpText: { en: 'Text translation', zh: '文字翻譯', jp: 'man4 zi6 faan1 jik6' },
  cmpJp: { en: 'Jyutping romanization', zh: '粵拼羅馬拼音', jp: 'jyut6 ping3 lo4 maa5 ping3 jam1' },
  cmpModes: { en: 'Solo · Conversation Mode · Text', zh: '獨白 · 對話模式 · 文字', jp: 'duk6 baak6 · deoi3 waa6 mou4 sik1 · man4 zi6' },
  cmpTts: { en: 'Tap-to-play voice', zh: '撳喇叭播語音', jp: 'gam2 laa3 baa1 bo3 jyu5 jam1' },
  cmpAutoSpeak: { en: 'Auto-speak after translate', zh: '翻譯後自動朗讀', jp: 'faan1 jik6 hau6 zi6 dung6 long5 duk6' },
  cmpQuality: { en: 'Cantonese quality', zh: '粵語質素', jp: 'jyut6 jyu5 zat1 sou3' },
  cmpSeats: { en: 'Seats', zh: '座位', jp: 'zo6 wai2' },
  cmpSupport: { en: 'Support', zh: '支援', jp: 'zi1 wun4' },
  valMetered: { en: 'Metered', zh: '有上限', jp: 'jau5 soeng6 haan6' },
  val5m: { en: '5 minutes', zh: '五分鐘', jp: 'ng5 fan1 zung1' },
  val20m: { en: '20 minutes', zh: '廿分鐘', jp: 'jaa6 fan1 zung1' },
  val10h: { en: '10 hours', zh: '十小時', jp: 'sap6 siu2 si4' },
  val40h: { en: '~40 hours*', zh: '大約四十小時*', jp: 'daai6 joek3 sei3 sap6 siu2 si4*' },
  valUnlimitedPlain: { en: 'Unlimited', zh: '無限', jp: 'mou4 haan6' },
  valStandard: { en: 'Standard', zh: '標準', jp: 'biu1 zeon2' },
  valPriority: { en: 'Priority', zh: '優先', jp: 'jau4 sin1' },
  valCommunity: { en: 'Community', zh: '社區', jp: 'se5 keoi1' },
  valEmail: { en: 'Email', zh: '電郵', jp: 'din6 jau4' },
  fairUseNote: {
    en: '* Max live hours are a soft fair-use cap (~40 hrs/mo) so speech costs stay sustainable.',
    zh: '* 旗艦版即時時數係合理使用上限（大約每月四十小時），等語音成本可以持續。',
    jp: '* kei4 gaam3 baan2 zik1 si4 si4 sou3 hai6 hap6 lei5 si2 jung6 soeng6 haan6 (daai6 joek3 mui5 jyut6 sei3 sap6 siu2 si4), dang2 jyu5 jam1 sing4 bun2 ho2 ji5 ci4 zuk6.',
  },

  faqKicker: { en: 'FAQ', zh: '常見問題', jp: 'soeng4 gin3 man6 tai4' },
  faqTitle: { en: 'Good questions', zh: '好問題', jp: 'hou2 man6 tai4' },
  faq1q: {
    en: 'Do I need my own API keys?',
    zh: '我需唔需要自己嘅 API 密鑰？',
    jp: 'ngo5 seoi1 m4 seoi1 jiu3 zi6 gei2 ge3 API mat6 joek6?',
  },
  faq1a: {
    en: 'No. Guests can try tap-to-play voice; Free includes a monthly voice-char limit. Pro/Max add unlimited voice, auto-speak, and more live mic time. If you self-host, plug in your own Azure/OpenAI keys.',
    zh: '唔使。訪客可以試撳喇叭播語音；免費版有每月語音字數上限。專業版／旗艦版有無限語音、自動朗讀同更多即時咪高峰時間。如果自己托管，可以改用你嘅 Azure／OpenAI 密鑰。',
    jp: 'm4 sai2. fong2 haak3 ho2 ji5 si3 gam2 laa3 baa1 bo3 jyu5 jam1; min5 fai3 baan2 jau5 mui5 jyut6 jyu5 jam1 zi6 sou3 soeng6 haan6. zyun1 jip6 / kei4 gaam3 baan2 jau5 mou4 haan6 jyu5 jam1, zi6 dung6 long5 duk6 tung4 gang3 do1 zik1 si4 mai1 gou1 fung1 si4 gaan3. jyu4 gwo2 zi6 gei2 tok3 gun2, ho2 ji5 goi2 jung6 nei5 ge3 Azure / OpenAI mat6 joek6.',
  },
  faq2q: {
    en: 'What counts as a “live minute”?',
    zh: '咩叫做「即時分鐘」？',
    jp: 'me1 giu3 zou6 “zik1 si4 fan1 zung1”?',
  },
  faq2a: {
    en: 'Time the microphone is actively listening in Solo or Conversation Mode. Text translation never uses live minutes.',
    zh: '喺獨白或者對話模式，咪高峰開啟聽緊嘅時間。文字翻譯唔計即時分鐘。',
    jp: 'hai2 duk6 baak6 waak6 ze2 deoi3 waa6 mou4 sik1, mai1 gou1 fung1 hoi1 kai2 teng1 gan2 ge3 si4 gaan3. man4 zi6 faan1 jik6 m4 gai3 zik1 si4 fan1 zung1.',
  },
  faq3q: {
    en: 'Can I run it on my own server?',
    zh: '可唔可以喺自己伺服器跑？',
    jp: 'ho2 m4 ho2 ji5 hai2 zi6 gei2 si1 fuk6 hei3 paau2?',
  },
  faq3a: {
    en: 'Yes — JyutTranslate can run fully self-hosted (open-source speech + translation) or on WordPress with cloud APIs.',
    zh: '可以——JyutTranslate 可以完全自己托管（開源語音同翻譯），又或者用 WordPress 加雲端 API。',
    jp: 'ho2 ji5 — JyutTranslate ho2 ji5 jyun4 cyun4 zi6 gei2 tok3 gun2 (hoi1 jyun4 jyu5 jam1 tung4 faan1 jik6), jau6 waak6 ze2 jung6 WordPress gaa1 wan4 dyun1 API.',
  },
  faq4q: {
    en: 'Can I cancel anytime?',
    zh: '可唔可以隨時取消？',
    jp: 'ho2 m4 ho2 ji5 ceoi4 si4 ceoi2 siu1?',
  },
  faq4a: {
    en: 'Yes, but refunds are up to my discretion. No refunds guaranteed.',
    zh: '可以，不過退款由我決定，唔保證退款。',
    jp: 'ho2 ji5, bat1 gwo3 teoi3 fun2 jau4 ngo5 kyut3 ding6, m4 bou2 zing3 teoi3 fun2.',
  },
  stillQuestions: { en: 'Still have questions?', zh: '仍然有問題？', jp: 'jing4 jin4 jau5 man6 tai4?' },
  stillBody: {
    en: 'Open the app to try it, or head back to the homepage for features.',
    zh: '開啟應用試吓，或者返去首頁睇功能。',
    jp: 'hoi1 kai2 jing3 jung6 si3 haa5, waak6 ze2 faan1 heoi3 sau2 jap6 tai2 gung1 nang4.',
  },
  backToApp: { en: 'Back to the app', zh: '返去應用', jp: 'faan1 heoi3 jing3 jung6' },
}

export function biPlain(b: Bi): string {
  return `${b.en} ${b.zh}`
}
